### ISSUE TITLE
azure site cert  commands do not work with xplat cli version 0.8.13

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-xplat-cli#1512]
The site cert commands work well with xplat cli version 0.8.12

Another problem I’d like to mention is that we are currently forced to run Xplat-CLI 0.8.12 due to a bug introduced with 0.8.13. Whenever we attempt to manage certificates using “azure site cert” we receive errors.
While getting a list of the certs:
 
```
D:\sdk\xplat1\azure-xplat-cli>azure site cert list --slot production mytestsite99
info:    Executing command site cert list
+ Getting site information
info:    No certificates defined yet
info:    site cert list command OK
```
When trying to add a cert:

```
D:\sdk\xplat1\azure-xplat-cli>azure site cert add -c ..\cert\mycert.pfx -k amarzavery mytestsite99
info:    Executing command site cert add
+ Getting site information
>>>>>>>>>>>>>>>>>>>> siteConfigurations
{ enabledHostNames:
   [ 'mytestsite99.azurewebsites.net',
     'mytestsite99.scm.azurewebsites.net' ],
  hostNames: [ 'mytestsite99.azurewebsites.net' ],
  hostNameSslStates:
   [ { name: 'mytestsite99.azurewebsites.net', sslState: 'Disabled' },
     { name: 'mytestsite99.scm.azurewebsites.net',
       sslState: 'Disabled' } ],
  adminEnabled: true,
  availabilityState: 'Normal',
  sku: 'Standard',
  enabled: true,
  lastModifiedTimeUtc: Tue Dec 30 2014 13:55:31 GMT-0800 (Pacific Standard Time),
  name: 'mytestsite99',
  repositorySiteName: 'mytestsite99',
  runtimeAvailabilityState: 'Normal',
  uri: 'https://waws-prod-bay-013.api.azurewebsites.windows.net:454/subscriptions/c9cbd920-c00c-427c-852b-8aaf38badaeb/webspaces/westuswebspace/sites/mytestsite99',
  serverFarm: 'Default1',
  siteProperties:
   { appSettings: {},
     metadata: {},
     properties:
      { RepositoryUri: 'https://mytestsite99.scm.azurewebsites.net',
        PublishingUsername: '$mytestsite99',
        PublishingPassword: 'MDXTER8WfTjF90gFbXDpciQkcPho8b1BmK0NunBPg7pTXDlZwnWqvWMMmjZq' } },
  state: 'Running',
  usageState: 'Normal',
  webSpace: 'westuswebspace' }
error:   Cannot call method 'push' of undefined
info:    Error information has been recorded to azure.err
error:   site cert add command failed


Tue Dec 30 2014 16:22:45 GMT-0800 (Pacific Standard Time):
{ [TypeError: Cannot call method 'push' of undefined]
  stack: [Getter/Setter],
  __frame:
   { name: '__2',
     line: 72,
     file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\site.cert._js',
     prev: undefined,
     active: true,
     offset: 25,
     col: 31 },
  rawStack: [Getter] }
TypeError: Cannot call method 'push' of undefined
    at ___ (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:107:52)
    at ___ (D:\sdk\xplat1\azure-xplat-cli\node_modules\streamline\lib\callbacks\runtime.js:85:13)
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
    at __2 (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:97:31)
```
 
When getting info on a cert with the thumbprint:
```
D:\sdk\xplat1\azure-xplat-cli>azure site cert show --slot production -t 50D58D5EEC01DE5BA360A0B81EEC94CD34FED0AB mytestsite99
info:    Executing command site cert show
+ Getting site information
error:   Cannot call method 'filter' of undefined
info:    Error information has been recorded to azure.err
error:   site cert show command failed

D:\sdk\xplat1\azure-xplat-cli>type azure.err
Tue Dec 30 2014 16:20:59 GMT-0800 (Pacific Standard Time):
{ [TypeError: Cannot call method 'filter' of undefined]
  stack: [Getter/Setter],
  __frame:
   { name: '__4',
     line: 161,
     file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\site.cert._js',
     prev: undefined,
     active: true,
     offset: 14,
     col: 31 },
  rawStack: [Getter] }
TypeError: Cannot call method 'filter' of undefined
    at ___ (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:179:56)
    at ___ (D:\sdk\xplat1\azure-xplat-cli\node_modules\streamline\lib\callbacks\runtime.js:85:13)
    at getSite__8 (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\websites\websitesclient._js:513:18)
    at __4 (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:175:31)
```
 
And when deleting a cert:

```
D:\sdk\xplat1\azure-xplat-cli>azure site cert delete --slot production -t 50D58D5EEC01DE5BA360A0B81EEC94CD34FED0AB mytestsite99 -q
info:    Executing command site cert delete
+ Getting site information
error:   Cannot call method 'filter' of undefined
info:    Error information has been recorded to azure.err
error:   site cert delete command failed


Tue Dec 30 2014 16:22:14 GMT-0800 (Pacific Standard Time):
{ [TypeError: Cannot call method 'filter' of undefined]
  stack: [Getter/Setter],
  __frame:
   { name: '__3',
     line: 121,
     file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\site.cert._js',
     prev: undefined,
     active: true,
     offset: 14,
     col: 31 },
  rawStack: [Getter] }
TypeError: Cannot call method 'filter' of undefined
    at ___ (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:138:56)
    at ___ (D:\sdk\xplat1\azure-xplat-cli\node_modules\streamline\lib\callbacks\runtime.js:85:13)
    at getSite__8 (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\websites\websitesclient._js:513:18)
    at __3 (D:\sdk\xplat1\azure-xplat-cli\lib\commands\asm\site.cert._js:135:31)


```

**Comment by NaveenGoli** [comment]
This commands are no longer supported

**Comment by NaveenGoli** [comment]
can u please close this issue as we removed the functionality

**Comment by matt-gibbs** [comment]
@NaveenGoli, please provide info on how to achieve the same now that the script has been removed.

**Comment by cicorias** [comment]
Could you update the release / changes log too as it is not indicated as removed. A breaking change like this should provide more clarity on the removal. Also, what is the alternate approach?  The command is still listing in the help.

**Comment by amarzavery** [comment]
@NaveenGoli @cicorias 
Server side does not support this functionality. This command will be removed in the next release. Hence, the changelog does not reflect this change. We will update you shortly with the alternate approach.

**Comment by cicorias** [comment]
for now, here's an alternate approach: [Azure Resource Manager – Adding and Assigning Certificates to a Website] (http://blogs.msdn.com/b/scicoria/archive/2015/01/31/azure-resource-manager-adding-and-assigning-certificates-to-a-website.aspx)

**Comment by jeffwilcox** [comment]
@amarzavery is the original issue fixed or otherwise addresses? Although it feels like this discussion thread has morphed, it's a very old thread...

**Comment by amarzavery** [comment]
The Websites team has removed this functionality from ASM. @cicorias provides the alternate approach in ARM, which is not usable for a site created in ASM mode. Website team needs to provide a good set of website commands in ARM mode.
