### ISSUE TITLE
Add support for Get-AzureDeploymentEvent 

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-xplat-cli#1567]
We need to add support for Get-AzureDeploymentEvent similar to Powershell so customers can see when their VMs are rebooted due to Planned Maintenance events.

**Comment by kenazk** [comment]
Can we up the Priority to P1? This is one of the top Redzone items for customers to see why their VMs are rebooted.

**Comment by anuchandy** [comment]
The fix is merged to dev branch.

**Comment by sreekanthbs** [comment]
ASM get-deployment-event command is not working in MSOpenTech dev branch. 
<pre>
<code>
C:\Aug2015\10Aug\azure-xplat-cli-dev>node bin/azure service get-deployment-event DndLinuxVM 2015-01-01 2015-12-31
info:    Executing command service get-deployment-event
+ Getting deployment events of deployments in the cloud service "DndLinuxVM"
error:   undefined is not a function
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   service get-deployment-event command failed
</code>
</pre>

**Comment by BastienSemene** [comment]
Same issue here with a slightly different output message but the cause seems to be the same.
Executed on Linux.
```
$ azure service get-deployment-event es-fingerprint --start-time 2015-08-13T12:32:01.000Z --end-time 2015-08-13T12:32:27.000Z
info:    Executing command service get-deployment-event
+ Getting deployment events of deployments in the cloud service "es-fingerprint"
error:   Object 2015-08-13T12:32:01.000Z has no method 'toISOString'
info:    Error information has been recorded to /*****/.azure/azure.err
error:   service get-deployment-event command failed

$ azure service get-deployment-event es-fingerprint --start-time 2015-08-13 --end-time 2015-08-13T12:32:27.000Z
info:    Executing command service get-deployment-event
+ Getting deployment events of deployments in the cloud service "es-fingerprint"
error:   Object 2015-08-13 has no method 'toISOString'
info:    Error information has been recorded to /*****/.azure/azure.err
error:   service get-deployment-event command failed
```

**Comment by sauryadas** [comment]
@anuchandy is this actually fixed?

**Comment by amarzavery** [comment]
@sauryadas @huangpf - I have verified this ASM command and there are bugs at multiple level. It would be nice if you can check this from the service side and let us know what is it that the service actually expects. That will help us in getting this issue fixed.

1. The user provides the date-time as a string as explained in the help. The command passes this string as is  to the hyak generated node sdk which expects it to be a Date object. (This is a simple fix).
2. The following is a bigger problem. I modified the command with a fix for the problem in step 1 and now the service returns a 400. 

As per the [MSDN REST API doc](https://msdn.microsoft.com/en-us/library/azure/dn848372.aspx), the following request looks correct. However the server sends back a **400 response with the error message**

**"The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation"**.

I tried the request with and without url encoding and received the same response from the server.

- **https://management.core.windows.net/11977897-163f-435f-2d32-39ec83451f4d/services/hostedservices/foobarservice/deploymentslots/Production/events?starttime=2016-07-14T18%3A05%3A36.853Z&endtime=2016-07-15T19%3A05%3A36.853Z**

- **https://management.core.windows.net/11977897-163f-435f-2d32-39ec83451f4d/services/hostedservices/foobarservice/deploymentslots/Production/events?starttime=2016-07-14T18:05:36.853Z&endtime=2016-07-15T19:05:36.853Z**


 ```
D:\sdk\azure-xplat-cli>node bin/azure service get-deployment-event foobarservice 2016-07-14T18:05:36.853Z  2016-07-15T19:05:36.853Z -vv
info:    Executing command service get-deployment-event
verbose: Getting deployment events of deployments in the cloud service "foobarservice"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2016-03-01' },
silly:       url: 'https://management.core.windows.net/11977897-163f-435f-2d32-39ec83451f4d/services/hostedservices/foobarservice/deploymentslots/Production/events?starttime=2016-07-14T18%3A05%3A36.853Z&endtime=2016-07-15T19%3A05%3A36.853Z'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '291',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.398 (rd_rdfe_stable.160705-1740) Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'ussouth3',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-ms-request-id: '79b6256a0e2aa1c984c8f64006a2b241',
silly:           date: 'Fri, 15 Jul 2016 19:21:50 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.</Message></Error>'
silly:   }
error:   The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.
silly:   {
silly:       stack: 'Error: The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.\n  <<< async stack >>>\n  at __5 (D:\\sdk\\azure-xplat-cli\\lib\\commands\\asm\\service.js:207:50)\n  <<< raw stack >>>\n    at Function.ServiceClient._normalizeError (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)',
silly:       message: 'The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.',
silly:       code: 'BadRequest',
silly:       statusCode: 400,
silly:       requestId: '79b6256a0e2aa1c984c8f64006a2b241',
silly:       __frame: {
silly:           name: '__5',
silly:           line: 189,
silly:           file: 'D:\\sdk\\azure-xplat-cli\\lib\\commands\\asm\\service.js',
silly:           prev: undefined,
silly:           calls: 0,
silly:           active: false,
silly:           offset: 18,
silly:           col: 49
silly:       },
silly:       rawStack: 'Error: The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.\n    at Function.ServiceClient._normalizeError (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (D:\\sdk\\azure-xplat-cli\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)'
silly:   }
error:   Error information has been recorded to C:\Users\amzavery\.azure\azure.err
verbose: Error: The time format specified for parameter StartTime is invalid. Accepted time formats can be found in the Windows Azure documentation.
  <<< async stack >>>
  at __5 (D:\sdk\azure-xplat-cli\lib\commands\asm\service.js:207:50)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (D:\sdk\azure-xplat-cli\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at D:\sdk\azure-xplat-cli\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (D:\sdk\azure-xplat-cli\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (D:\sdk\azure-xplat-cli\node_modules\azure-common\node_modules\request\request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\sdk\azure-xplat-cli\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\sdk\azure-xplat-cli\node_modules\azure-common\node_modules\request\request.js:1111:12)
error:   service get-deployment-event command failed
```
