### ISSUE TITLE
error: undefined is not a function

### ISSUE THREAD

**Issue by crawford** [Azure/azure-xplat-cli#1575]
This command:

```
azure vm image create \
        --blob-url=<url> \
        --label=<label> \
        --description=<description> \
        --os="linux" \
        --source-key=<key> \
        <name> \
        <url-to-storage-blob>
```

results in the following "azure.err":
```
Tue Feb 10 2015 03:14:01 GMT+0000 (UTC):
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at signBlobUri (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/pageBlob.js:187:23)
    at Object.copyBlob (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/pageBlob.js:122:17)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/uploadVMImage.js:125:16
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/uploadVMImage.js:65:5
    at callbacks.(anonymous function) (/usr/local/lib/node_modules/azure-cli/lib/util/callbackAggregator.js:81:30)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure/node_modules/azure-mgmt-storage/lib/storageManagementClient.js:915:16
    at Parser.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/lib/xml2js.js:246:20)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/node_modules/sax/lib/sax.js:589:33)
```

**Comment by crawford** [comment]
Version 0.8.12.

**Comment by crawford** [comment]
Updating to version 0.8.14 results in something very similar.

```
Tue Feb 10 2015 03:20:36 GMT+0000 (UTC):
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at signBlobUri (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/pageBlob.js:187:23)
    at Object.copyBlob (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/pageBlob.js:122:17)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/uploadVMImage.js:125:16
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/iaas/upload/uploadVMImage.js:65:5
    at callbacks.(anonymous function) (/usr/local/lib/node_modules/azure-cli/lib/util/callbackAggregator.js:81:30)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure/node_modules/azure-mgmt-storage/lib/storageManagementClient.js:905:16
    at Parser.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/lib/xml2js.js:246:20)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/xml2js/node_modules/sax/lib/sax.js:589:33)
```

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
