### ISSUE TITLE
azure network vnet create - Error - Cannot read property

### ISSUE THREAD

**Issue by jangelfdez** [Azure/azure-xplat-cli#1589]
Hi!

When trying to create a new VNet using the xplat-cli tools (0.8.14) an error is generated. I have tried with several combinations of the parameters with the same result.

C:\Users\user>**azure network vnet create --location "West Europe" azure4linux -v**
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
verbose: Address Space [Starting IP/CIDR (Max VM Count)]: 10.0.0.0/8 (16777216)
verbose: Subnet [Starting IP/CIDR (Max VM Count)]: 10.0.0.0/11 (2097152)
verbose: Getting network configuration
verbose: Registering sqlserver with function registerProvider
verbose: Registering resource sqlserver with subscription b124a859-8d87-4791-9aa1-946ce20b68a6
**error:   Cannot read property 'length' of undefined
error:   Cannot read property 'Symbol(formatted stack trace)' of undefined**
verbose: stack TypeError: Cannot read property 'Symbol(formatted stack trace)' of undefined
    at TypeError.stack (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:224:27)
    at C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:183:19
    at Array.forEach (native)
    at stringifyObject (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:181:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:129:38
    at stringify (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:131:7)
    at Object.eyes.inspect (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:53:16)
    at Object.log.json (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\lib\util\logging.js:84:22)
    at callback (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\lib\cli.js:216:17)
    at __propagate (C:\Users\user\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:124:4)
info:    Error information has been recorded to C:\Users\user\.azure\azure.err

**Comment by jangelfdez** [comment]
The command fails when a "Local Network" is defined inside the portal, if no local networks are present it works.

**Comment by anuchandy** [comment]
Thanks @jangelfdez  for reporting this. Investigating this issue, this is related to https://github.com/Azure/azure-xplat-cli/issues/1416

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
