### ISSUE TITLE
Object #<StorageAccountOperations> has no method 'delete'

### ISSUE THREAD

**Issue by errordeveloper** [Azure/azure-xplat-cli#1615]
```
> ./node_modules/.bin/azure storage account create --location='West Europe' 4c599a9bfb9
info:    Executing command storage account create
+ Creating storage account                                                     
info:    storage account create command OK

> ./node_modules/.bin/azure storage account delete 4c599a9bfb9
info:    Executing command storage account delete
Delete storage account 4c599a9bfb9? [y/n] y
+ Deleting storage account                                                     
error:   Object #<StorageAccountOperations> has no method 'delete'
info:    Error information has been recorded to /Users/ilya/.azure/azure.err
error:   storage account delete command failed

> cat ~/.azure/azure.err
Wed Mar 25 2015 11:36:37 GMT+0000 (GMT):
[TypeError: Object #<StorageAccountOperations> has no method 'delete']
TypeError: Object #<StorageAccountOperations> has no method 'delete'
    at __$storageAccount_deleteCommand__5 (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:208:54)
    at __tryCatch (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:141:4)
    at ___ (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:206:129)
    at ___ (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:208:170)
    at __$storageAccount_deleteCommand__5 (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:210:163)
    at __$storageAccount_deleteCommand__5 (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:202:412)
    at ___ (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/lib/commands/asm/storage.account._js:202:428)
    at ___ (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:85:13)
    at /Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:77:14
    at Object.__g.trampoline.flush (/Users/ilya/Code/kubernetes/docs/getting-started-guides/coreos/azure/node_modules/azure-cli/node_modules/kuduscript/node_modules/streamline/lib/callbacks/runtime.js:20:29)
```

Azure CLI version: 0.8.15
Node version: 0.10.33

**Comment by markcowl** [comment]
@errordeveloper thank you for the feedback.  Assigning this issue to the appropriate service team

**Comment by amarzavery** [comment]
@errordeveloper - I think this issue is fixed in the newer version of CLI 0.8.16.
However, can you please post the details of azure.err file ?

**Comment by errordeveloper** [comment]
@amarzavery I've update the issue to included the `~/.azure/azure.err`.

**Comment by errordeveloper** [comment]
I can confirm that it works on 0.8.16, thank you.
