### ISSUE TITLE
Unable to create a vnet due to the error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-xplat-cli#1632]
Found this issue in creating vnet with an affinity-group as a part of recording tests:

Scenario: There are no vnets in the subscription. This is the first one to be created in the subscription. We get this error:

```
'--Start--    cli vm Load balancer : Vm should create with vnet: '
'node cli.js vm image list --json'
'node cli.js network vnet list --json'
'node cli.js account affinity-group list --json'
'node cli.js network vnet create testvnet4117 -a tdstnodetest --json'

Sun Mar 15 2015 19:06:04 GMT-0700 (Pacific Daylight Time):
{ [TypeError: Cannot read property 'length' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'createVNet',
     line: 439,
     file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js',
     prev: 
      { name: '__1',
        line: 34,
        file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\account.affinitygroup._js',
        prev: 
         { name: 'listVNet',
           line: 349,
           file: 'D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js',
           prev: undefined,
           calls: 1,
           active: false,
           offset: 4,
           col: 28 },
        calls: 1,
        active: false,
        offset: 7,
        col: 48 },
     calls: 1,
     active: true,
     offset: 298,
     col: 31 },
  rawStack: [Getter] }
'TypeError: Cannot read property \'length\' of undefined\n  <<< async stack >>>\n  at createVNet (D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js:737:32)\n  at __1 (D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\account.affinitygroup._js:41:49)\n  at listVNet (D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js:353:29)\n  <<< raw stack >>>\n    at ___ (D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js:744:25)\n    at ___ (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\commands\\asm\\network._js:1141:16\n    at D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\azure\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:7290:14\n    at handleRedirect (D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\util\\utils.js:158:9)\n    at D:\\sdk\\xplat1\\azure-xplat-cli\\lib\\util\\logging.js:244:7\n    at handleRedirect (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:49:7\n    at Request._callback (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\request\\request.js:129:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\request\\request.js:873:14)\n    at Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous> (D:\\sdk\\xplat1\\azure-xplat-cli\\node_modules\\request\\request.js:824:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)\n'
```

buggy code:
```
var networkConfiguration = getNetworkConfig(options, _);
    if (!networkConfiguration.VirtualNetworkConfiguration) {
      networkConfiguration.VirtualNetworkConfiguration = {};
    }

    var vnetConfiguration = networkConfiguration.VirtualNetworkConfiguration;

    for (var i = 0; i < vnetConfiguration.VirtualNetworkSites.length; i++) {
      var site = vnetConfiguration.VirtualNetworkSites[i];
      if (utils.ignoreCaseEquals(site.Name, vnetInput.name)) {
        throw new Error(util.format($('A virtual network with name %s already exists'), vnetInput.name));
      }
    }
```

vnetConfiguration does not have **VirtualNetworkSites** defined... Hence we see the error:

Cannot read property 'length' of undefined

**Comment by amarzavery** [comment]
Console.logs for more info:
```
D:\sdk\xplat1\azure-xplat-cli>node bin/azure network vnet create testvnet4117 -a tdstnodetest
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Getting network configuration
>>>>>>>>>>>>>>>>>>>>>vnetConfiguration{ Dns: { DnsServers: [ { Name: 'DNS-c976a04519c31ab8', IPAddress: '10.0.0.1' } ] } }
error:   Cannot read property 'length' of undefined
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   network vnet create command failed
```

```
D:\sdk\xplat1\azure-xplat-cli>node bin/azure network vnet create testvnet4117 -a tdstnodetest
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Getting network configuration
>>>>>>>>>>>>>>>>>>>>>vnetConfiguration{ Dns: { DnsServers: [ { Name: 'DNS-c976a04519c31ab8', IPAddress: '10.0.0.1' } ] } }
+ Getting or creating affinity group
+ Getting affinity groups
info:    Using affinity group tdstnodetest
>>>>>>>>>>>>>>>>>>>>>virtualNetworkSite{ Name: 'testvnet4117',
  AddressSpace: [ '10.0.0.0/8' ],
  Subnets: [ { AddressPrefix: '10.0.0.0/11', Name: 'Subnet-1' } ],
  DnsServersRef: [],
  AffinityGroup: 'tdstnodetest' }
error:   Cannot call method 'push' of undefined
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   network vnet create command failed
```


After making the right fix:

```
D:\sdk\xplat1\azure-xplat-cli>node bin/azure network vnet create testvnet4117 -a tdstnodetest
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Getting network configuration
>>>>>>>>>>>>>>>>>>>>>vnetConfiguration{ Dns: { DnsServers: [ { Name: 'DNS-c976a04519c31ab8', IPAddress: '10.0.0.1' } ] } }
+ Getting or creating affinity group
+ Getting affinity groups
info:    Using affinity group tdstnodetest
>>>>>>>>>>>>>>>>>>>>>virtualNetworkSite{ Name: 'testvnet4117',
  AddressSpace: [ '10.0.0.0/8' ],
  Subnets: [ { AddressPrefix: '10.0.0.0/11', Name: 'Subnet-1' } ],
  DnsServersRef: [],
  AffinityGroup: 'tdstnodetest' }
after pushing >>>>>>>>>>>>>>>>>>>>>vnetConfiguration{ Dns: { DnsServers: [ { Name: 'DNS-c976a04519c31ab8', IPAddress: '10.0.0.1' } ] },
  VirtualNetworkSites:
   [ { Name: 'testvnet4117',
       AddressSpace: [ '10.0.0.0/8' ],
       Subnets: [ { AddressPrefix: '10.0.0.0/11', Name: 'Subnet-1' } ],
       DnsServersRef: [],
       AffinityGroup: 'tdstnodetest' } ] }
+ Updating Network Configuration
info:    network vnet create command OK

D:\sdk\xplat1\azure-xplat-cli>node bin/azure network vnet create testvnet4 -a tdstnodetest
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Getting network configuration
+ Getting or creating affinity group
+ Getting affinity groups
info:    Using affinity group tdstnodetest
+ Updating Network Configuration
info:    network vnet create command OK

D:\sdk\xplat1\azure-xplat-cli>
```

**Comment by amarzavery** [comment]
fixed.
