### ISSUE TITLE
Cannot find Webspace with name westuswebspace

### ISSUE THREAD

**Issue by ashelley** [Azure/azure-xplat-cli#1646]
Hello,

I'm trying to use azure-cli to check settings on my site:

Note: using azure site appsetting list results in the same error.

```
$ azure --version
0.8.16 (node: 0.10.36)
```

```
$ azure site show
info:    Executing command site show
Web site name: mysitename
Web site slot [enter for none]: 
+ Getting sites                                                                
error:   Cannot find WebSpace with name westuswebspace.
info:    Error information has been recorded to /home/adam/.azure/azure.err
error:   site show command failed
```

```
$ cat /home/adam/.azure/azure.err
Tue Mar 24 2015 09:19:15 GMT-0700 (PDT):
{ [Error: Cannot find WebSpace with name westuswebspace.]
  stack: [Getter/Setter],
  code: 'NotFound',
  extendedcode: '51004',
  messagetemplate: 'Cannot find {0} with name {1}.',
  parameters: 
   { '$': { 'xmlns:a': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
     'a:string': [ 'WebSpace', 'westuswebspace' ] },
  innererrors: { '$': { 'i:nil': 'true' } },
  statusCode: 404,
  __frame: 
   { name: '__1',
     line: 452,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js',
     prev: 
      { name: 'getSites__7',
        line: 439,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js',
        prev: [Object],
        calls: 22,
        active: false,
        offset: 12,
        col: 25 },
     calls: 0,
     active: false,
     offset: 1,
     col: 35 },
  rawStack: [Getter] }
Error: Cannot find WebSpace with name westuswebspace.
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:453:36)
  at getSites__7 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:451:26)
  at lookupSiteWebSpace__19 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:858:22)
  at lookupSiteNameAndWebSpace__20 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:883:10)
  at __7 (/usr/lib/node_modules/azure-cli/lib/commands/asm/site._js:475:16)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by ipepe** [comment]
It would be nice if someone would respond to this.

**Comment by devigned** [comment]
@NaveenGoli any thoughts on this issue?

**Comment by ipepe** [comment]
I fixed it by removing whole ~/.azure folder

**Comment by ashelley** [comment]
I can't confirm that this fixes it for me.  After removing the .azure directory I am unable to login:
```
$ azure login
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: ashelley@mydomain
Password: *****************
+ Authenticating...                                                            
error:   Server returned an unknown AccountType: undefined
info:    Error information has been recorded to /home/adam/.azure/azure.err
error:   login command failed

$ cat /home/adam/.azure/azure.err 
Wed May 06 2015 08:45:38 GMT-0700 (PDT):
{ [Error: Server returned an unknown AccountType: undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'getSubscriptions',
     line: 23,
     file: '/usr/lib/node_modules/azure-cli/lib/util/profile/subscriptionUtils._js',
     prev: 
      { name: '__1',
        line: 42,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/login._js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 48,
        col: 43 },
     calls: 0,
     active: false,
     offset: 1,
     col: 32 },
  rawStack: [Getter] }
Error: Server returned an unknown AccountType: undefined
  <<< async stack >>>
  at getSubscriptions (/usr/lib/node_modules/azure-cli/lib/util/profile/subscriptionUtils._js:24:33)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login._js:90:44)
  <<< raw stack >>>
    at Logger.createError (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:196:13)
    at /usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:373:35
    at UserRealm._parseDiscoveryResponse (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/user-realm.js:234:3)
    at /usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/user-realm.js:263:12
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:116:5)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:824:12)
```

**Comment by ashelley** [comment]
Update:

I can now confirm that this does indeed fix the issue.  I was able to use the 'azure account import' method of logging in and now I am able to use 'azure site show' command. 

Thank you @ipepe

**Comment by amarzavery** [comment]
@ashelley , @ipepe - 

Deleting the .azure and .streamline folder in the User's home directory should be fine.

You can try upgrading to the latest version of cli.

```npm install -g azure-cli```

**Comment by ipepe** [comment]
I upgraded and it didn't help me. I can't reproduce error now, but removing .azure folder seemed to work. 

I think that bug is somehow connected to not having any websites, in azure account or setting some default location of websites? Because @ashelley had 
```Cannot find WebSpace with name westuswebspace.```
but I had 
```Cannot find WebSpace with name westeuropewebspace.```

**Comment by ashelley** [comment]
I can confirm I am still working after deleting the .azure directory and updating to azure-cli@0.9.2.  I didn't realize there was an update to the package before because I guess an old version of the tool dumped a binary in /usr/bin/azure which was overriding the more recent installed version so I was stuck using 0.8.16.  After deleting the old binary and logging out and logging back in again I was able to use the new version of the package.

Also, because I have deleted my .azure directory I probably will no longer be able to reproduce this problem so I expect that this issue probably should be closed now.  

Thank you for the help!

**Comment by mharen** [comment]
Burning the .azure folder also worked for me.

**Comment by bdphil86** [comment]
If you go into the .azure directory and find the spaces.{someGuid} JSON file.  Open it and just delete the space they are complaining about.  Then, re-run your command.  This worked for me without having to delete the entire. folder.

**Comment by Larney11** [comment]
This is how I solved the problem without deleting my entire azure folder. Go to azure directory (~/.azure) and delete the website object that is giving you trouble inside the files beginning with "sites." and "spaces.".
