### ISSUE TITLE
azure-cli 0.9.1 shows error "Cannot find module './account/accountclient'"

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#1729]
I installed 0.8.16 with below commands and it works. But I install 0.9.1 with "sudo npm install azure-cli@0.9.1 -g" and the client shows error "Cannot find module './account/accountclient'". Even if I uninstall 0.8.16 and install 0.9.1, the same error still exists. Could someone give me suggestions? Thanks.

Install commands:
sudo apt-get install -y nodejs-legacy
sudo apt-get install -y npm
sudo npm install azure-cli@0.8.16 -g

ERROR when executing "azure -h":
Fri May 01 2015 12:16:24 GMT+0000 (UTC):
{ [Error: Cannot find module './account/accountclient'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './account/accountclient'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/commands/account._js:12:21)
    at Module._compile (module.js:456:26)
    at Module.pModule._compile (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.streamliners._js [as ._js] (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/underscored.js:120:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by amarzavery** [comment]
@AbelHu - We are trying to repro the issue on ubuntu.
Can you please provide the following info:
- Version of Ubuntu ?
- Version of node installed on your system ?

**Comment by amarzavery** [comment]
@AbelHu - 

I was able to install azure-cli 0.9.1 via npm on Ubuntu 14.04.2 
```
├── azure-storage-legacy@0.9.13 (azure-common@0.9.10)
├── azure-gallery@2.0.0-pre.15 (azure-common@0.9.11)
├── azure-mgmt-authorization@0.9.0-pre.6 (azure-common@0.9.11)
├── azure@0.10.5 (azure-mgmt-subscription@0.9.16, azure-mgmt-hdinsight@0.9.15, azure-mgmt-storage@0.9.16, azure-mgmt@0.9.16, azure-mgmt-scheduler@0.9.1-pre.16, azure-monitoring@0.9.1-pre.16, azure-mgmt-resource@2.0.0-pre.16, azure-scheduler@0.9.1-pre.16, azure-rm-website@0.9.0-pre.10, azure-mgmt-sql@0.9.17, azure-mgmt-sb@0.9.16, azure-mgmt-vnet@0.9.17, azure-mgmt-website@0.9.16, request@2.45.0, azure-mgmt-compute@0.9.16, azure-common@0.9.11, azure-sb@0.9.16, azure-storage@0.3.3)
└── azure-mgmt-resource@2.0.0-pre.17 (azure-common@0.9.11)
amar@amar-VirtualBox:~$ azure -v
0.9.1
amar@amar-VirtualBox:~$ azure -h
info:             _    _____   _ ___ ___
info:            /_\  |_  / | | | _ \ __|
info:      _ ___/ _ \__/ /| |_| |   / _|___ _ _
info:    (___  /_/ \_\/___|\___/|_|_\___| _____)
info:       (_______ _ _)         _ ______ _)_ _ 
info:              (______________ _ )   (___ _ _)
info:    
info:    Microsoft Azure: Microsoft's Cloud Platform
info:    
info:    Tool version 0.9.1
help:    
help:    Display help for a given command
help:      help [options] [command]
help:    
help:    Log in to an Azure subscription using Active Directory. Currently, the user can login only via Microsoft organizational account
help:      login [options] [username]
help:    
help:    Log out from Azure subscription using Active Directory. Currently, the user can log out only via Microsoft organizational account
help:      logout [options] [username]
help:    
help:    Open the portal in a browser
help:      portal [options]
help:    
help:    Commands:
help:      account                            Commands to manage your account information and publish settings
help:      account affinity-group             Commands to manage your Affinity Groups
help:      account cert                       Commands to manage your account certificates
help:      account env                        Commands to manage your account environment
help:      config                             Commands to manage your local settings
help:      hdinsight                          Commands to manage your HDInsight accounts
help:      hdinsight cluster                  Commands to manage your HDInsight clusters
help:      hdinsight cluster config           Commands to manage your HDInsight configuration file
help:      hdinsight cluster config metastore Commands to manage your HDInsight metastore accounts in a configuration file
help:      hdinsight cluster config storage   Commands to manage your HDInsight storage accounts in a configuration file
help:      mobile                             Commands to manage your Mobile Services
help:      mobile api                         Commands to manage your mobile service APIs
help:      mobile appsetting                  Commands to manage your mobile application app settings
help:      mobile auth                        Commands to manage authentication settings for mobile service
help:      mobile auth aad                    Manage azure active directory settings for mobile service
help:      mobile auth aad tenant             Manage azure active directory tenants for mobile service
help:      mobile auth facebook               Manage facebook settings for mobile service
help:      mobile auth google                 Manage Google settings for mobile service
help:      mobile auth microsoftaccount       Manage microsoft account settings for mobile service
help:      mobile auth twitter                Manage twitter settings for mobile service
help:      mobile cert                        Commands to manage your Mobile Service Certificates for Domains
help:      mobile config                      Commands to manage your Mobile Service configuration
help:      mobile data                        Commands to manage your Mobile Service tables data
help:      mobile domain                      Commands to manage your Mobile Service Domains
help:      mobile domain ssl                  Commands to manage SSL for your Mobile Service Domains
help:      mobile job                         Commands to manage your Mobile Service scheduled jobs
help:      mobile key                         Commands to manage your Mobile Service keys
help:      mobile preview                     Commands to enable preview features for your Mobile Service
help:      mobile push                        Commands to manage your Mobile Service Push Settings
help:      mobile push apns                   Manage APNS settings for mobile service
help:      mobile push gcm                    Manage GCM settings for mobile service
help:      mobile push mpns                   Manage Windows Phone notification settings for mobile service
help:      mobile push nh                     Manage notification hub settings for mobile service
help:      mobile push wns                    Manage windows application credentials for mobile service
help:      mobile scale                       Commands to manage your Mobile Service scaling
help:      mobile script                      Commands to manage your Mobile Service scripts
help:      mobile table                       Commands to manage your Mobile Service tables
help:      network                            Commands to manage your Networks
help:      network dnsserver                  Commands to manage your DNS Servers
help:      network reserved-ip                Commands to manage your reserved public Virtual IP addresses
help:      network vnet                       Commands to manage your Virtual Networks
help:      network vnet static-ip             Commands to manage your Virtual Network static IP addresses
help:      sb                                 Commands to manage your Service Bus configuration
help:      sb namespace                       Commands to manage your Service Bus namespaces
help:      sb namespace location              Commands to manage your Service Bus locations
help:      service                            Commands to manage your Cloud Services
help:      service cert                       Commands to manage your Cloud Services certificates
help:      service internal-load-balancer     Commands to manage internal load balancers for your Cloud Service Deployment
help:      site                               Commands to manage your Web Sites
help:      site appsetting                    Commands to manage your Web Site application settings
help:      site config                        Commands to manage your Web Site configurations (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
help:      site connectionstring              Commands to manage your Web Site connection strings
help:      site defaultdocument               Commands to manage your Web Site default documents
help:      site deployment                    Commands to manage your Web Site deployments
help:      site deployment user               Commands to manage your Web Site deployment users
help:      site domain                        Commands to manage your Web Site domains
help:      site handler                       Commands to manage your Web Site handler mappings
help:      site job                           Commands to manage your Web Site WebJobs
help:      site job history                   Commands to manage your Web Site WebJobs History
help:      site location                      Commands to manage your Web Site locations
help:      site log                           Commands to manage your Web Site diagnostics
help:      site repository                    Commands to manage your Web Site repositories
help:      site scale                         Commands to manage your Web Site scaling
help:      sql                                Commands to manage your SQL Server accounts
help:      sql db                             Commands to manage your SQL Server databases
help:      sql firewallrule                   Commands to manage your SQL Server firewall rules
help:      sql server                         Commands to manage your SQL Server database servers
help:      storage                            Commands to manage your Storage objects
help:      storage account                    Commands to manage your Storage accounts
help:      storage account connectionstring   Commands to show your Storage connection string
help:      storage account keys               Commands to manage your Storage account keys
help:      storage blob                       Commands to manage your Storage blobs
help:      storage blob copy                  Commands to manage your blob copy operations
help:      storage blob sas                   Commands to manage shared access signature of your Storage blob
help:      storage container                  Commands to manage your Storage containers
help:      storage container policy           Commands to manage stored access policies of your Storage container
help:      storage container sas              Commands to manage shared access signatures of your Storage container
help:      storage directory                  Commands to manage your Storage file directory
help:      storage file                       Commands to manage your Storage files
help:      storage logging                    Commands to manage your Storage logging properties
help:      storage metrics                    Commands to manage your Storage metrics properties
help:      storage queue                      Commands to manage your Storage queues
help:      storage queue policy               Commands to manage stored access policies of your Storage queue
help:      storage queue sas                  Commands to manage shared access signatures of your Storage queue
help:      storage share                      Commands to manage your Storage file shares
help:      storage table                      Commands to manage your Storage tables
help:      storage table policy               Commands to manage stored access policies of your Storage table
help:      storage table sas                  Commands to manage shared access signatures of your Storage table
help:      vm                                 Commands to manage your Virtual Machines
help:      vm disk                            Commands to manage your Virtual Machine data disks
help:      vm docker                          Commands to manage your Docker Virtual Machine
help:      vm endpoint                        Commands to manage your Virtual Machine endpoints
help:      vm endpoint acl-rule               Commands to manage your Virtual Machine endpoint's ACL rules
help:      vm extension                       Commands to manage VM resource extensions
help:      vm image                           Commands to manage your Virtual Machine images
help:      vm location                        Commands to manage your Virtual Machine locations
help:      vm public-ip                       Commands to manage your Virtual Machine public IP address
help:      vm static-ip                       Commands to manage your Virtual Machine static IP address
help:    
help:    Options:
help:      -h, --help     output usage information
help:      -v, --version  output the application version
```

**Comment by AbelHu** [comment]
1.                   Ubuntu version:

uname -a
Linux abel-boshdns-crp 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


2.     node -v

v0.10.25

**Comment by AbelHu** [comment]
I can rerpo this issue.
1. Create a Ubuntu VM based on 14.04 LTS in East Asia. Set admin user with ssh certificate, without password.
2. Execute below commands:
sudo apt-get update
sudo apt-get install -y nodejs-legacy
sudo apt-get install -y npm
sudo npm install azure-cli@0.8.16 -g
sudo npm install optimist -g
sudo npm install azure-mgmt-resource -g
sudo npm install retry -g
sudo npm install async -g
sudo npm install azure-common -g
3. Execute 'azure -h" successfully.
4. Execute below commands
sudo npm uninstall azure-cli -g
sudo npm install azure-cli@0.9.1 -g
5. Failed to execute 'azure -h'.

**Comment by yugangw-msft** [comment]
2 leads from the error of "Cannot find module './account/accountclient"
a. "Accountclient" is a file we have removed several versions earlier
b. When that work happened, we also updated "account._js" to remove related "require"
So my take would be, the streamline files (pre-compiled from the "account._js") gets out of sync, and the workaround would be for you to delete the precompile folder, so the code will be regenerated on the fly
In the windows box the folder is under "C:\Users\yugangw\.streamline". I know very few on linux, but if you can't find the the folder, let me know

**Comment by amarzavery** [comment]
@AbelHu - Did your issue get resolved? Btw, we have installed a newer version of the CLI (0.9.2). You can try installing that. Hope that unblocks you.

**Comment by AbelHu** [comment]
Thanks. 0.9.2 works after I uninstall 0.8.16 and install 0.9.2.

Best Regards,
Abel HU (Mr.)
