### ISSUE TITLE
azure login issues - `Server returned error in RSTR`

### ISSUE THREAD

**Issue by blowsie** [Azure/azure-xplat-cli#1736]
Win 8.1
Node 0.10.37
NPM 1.4.28
Latest version of azure-cli

When trying to log in I get the following error, no code, no message. Any ideas?

`azure login -u myemailaddress@hotmail.com`

```
Tue May 05 2015 15:55:43 GMT+0100 (GMT Summer Time):
{ [Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE]
  stack: [Getter/Setter],
  __frame: 
   { name: 'getSubscriptions',
     line: 23,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\util\\profile\\subscriptionUtils.js',
     prev: 
      { name: '__1',
        line: 42,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 48,
        col: 43 },
     calls: 0,
     active: false,
     offset: 1,
     col: 32 },
  rawStack: [Getter] }
Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
  <<< async stack >>>
  at getSubscriptions (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\profile\subscriptionUtils.js:24:33)
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:90:44)
  <<< raw stack >>>
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:196:13)
    at WSTrustResponse.parse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\wstrust-response.js:243:23)
    at WSTrustRequest._handleRSTR (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\wstrust-request.js:150:21)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\wstrust-request.js:183:12
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:137:5)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:824:12)
```

**Comment by amarzavery** [comment]
@blowsie - Currently we only support organizational accounts via login command
```
D:\sdk\xplat1\azure-sdk-for-node>azure login -u myusername@microsoft.com
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
```

This link should help you to get an org account http://aka.ms/Dhf67j if you dont have one.

**Comment by blowsie** [comment]
Thankyou

**Comment by mrmunch** [comment]
I have the same problem but I use *******@outlook.de

**Comment by mohitsriv** [comment]
We just shipped interactive Microsoft account login yesterday.  Try running just azure login (no parameters) and follow the instructions for logging in via your browser.
