### ISSUE TITLE
resource create command fails when creating a storage account because the server returns a 202 with null body

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-xplat-cli#1737]
```
D:\sdk\xplat1\azure-sdk-for-node>azure resource create csmrg7947 mytest122 Microsoft.Storage/storageAccounts "West US" 2015-05-01-preview -p "{\"accountType\":\"Standard_LRS\"}" -v
v
info:    Executing command resource create
verbose: Getting resource mytest122
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json; charset=utf-8', user-agent: 'WindowsAzureXplatCLI/0.9.2' },
silly:       url: 'https://management.azure.com/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourcegroups/csmrg7947/providers/Microsoft.Storage//storageAccounts/mytest122?a
pi-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-failure-cause: 'gateway',
silly:           x-ms-request-id: '51cc4f8d-005b-48dc-b26b-4f8c6bcfee09',
silly:           x-ms-correlation-request-id: '51cc4f8d-005b-48dc-b26b-4f8c6bcfee09',
silly:           x-ms-routing-request-id: 'WESTUS:20150505T163116Z:51cc4f8d-005b-48dc-b26b-4f8c6bcfee09',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Tue, 05 May 2015 16:31:16 GMT',
silly:           connection: 'close',
silly:           content-length: '69'
silly:       },
silly:       body: '{"error":{"code":"ResourceNotFound","message":"Resource not found."}}'
silly:   }
verbose: Creating resource mytest122
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           Content-Length: 76,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourcegroups/csmrg7947/providers/Microsoft.Storage//storageAccounts/mytest122?a
pi-version=2015-05-01-preview',
silly:       body: '{"location":"West US","properties":{"accountType":"Standard_LRS"},"tags":{}}'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 202,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '4',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           location: 'https://management.azure.com/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/providers/Microsoft.Storage/operations/5abb9d19-81b4-4e64-abde-388368e52
9a7?monitor=true&api-version=2015-05-01-preview',
silly:           retry-after: '25',
silly:           x-ms-request-id: '5abb9d19-81b4-4e64-abde-388368e529a7',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1199',
silly:           x-ms-correlation-request-id: '8319aeab-afc0-46dc-a78d-b7209d0b0b93',
silly:           x-ms-routing-request-id: 'WESTUS:20150505T163118Z:8319aeab-afc0-46dc-a78d-b7209d0b0b93',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Tue, 05 May 2015 16:31:17 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: 'null'
silly:   }
error:   null
silly:   {
silly:       stack: 'Error: null\n  <<< async stack >>>\n  at __2 (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js:1
24:40)\n  at resource_createResource__3 (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js:122:21)\n  at __1 (C:\\User
s\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js:52:16)\n  <<< raw stack >>>\n    at C:\\Users\\amzavery\\AppData\\Roaming\\n
pm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\azure-mgmt-resource\\lib\\resourceManagementClient.js:4858:21\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\no
de_modules\\azure-cli\\lib\\util\\utils.js:308:7\n    at handleRedirect (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\util\\utils.js:285:9)\n    at C:\
\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\util\\logging.js:244:7\n    at handleRedirect (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azur
e-cli\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\
\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:49:7\n    at Request._callback (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_mo
dules\\azure-cli\\node_modules\\azure\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\Users\\amzavery\\AppData\\Roaming\\npm\
\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Users\\amzavery\\A
ppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\request\\request.js:1160:14)\n',
silly:       message: 'null',
silly:       statusCode: 202,
silly:       __frame: {
silly:           name: '__2',
silly:           line: 123,
silly:           file: 'C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js',
silly:           prev: {
silly:               name: 'resource_createResource__3',
silly:               line: 72,
silly:               file: 'C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js',
silly:               prev: {
silly:                   name: '__1',
silly:                   line: 51,
silly:                   file: 'C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\resource\\resource._js',
silly:                   prev: undefined,
silly:                   calls: 1,
silly:                   active: false,
silly:                   offset: 1,
silly:                   col: 15
silly:               },
silly:               calls: 2,
silly:               active: false,
silly:               offset: 50,
silly:               col: 20
silly:           },
silly:           calls: 0,
silly:           active: false,
silly:           offset: 1,
silly:           col: 39
silly:       },
silly:       rawStack: 'Error: null\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\azure-mgmt-resource\\lib\\resour
ceManagementClient.js:4858:21\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\util\\utils.js:308:7\n    at handleRedirect (C:\\Users\\amzavery\\Ap
pData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\util\\utils.js:285:9)\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\util\\logging.js:244:7\n
   at handleRedirect (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.j
s:36:9)\n    at C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js
:49:7\n    at Request._callback (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\azure-common\\lib\\http\\request-pipeline.j
s:109:14)\n    at Request.self.callback (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\request\\request.js:199:22)\n    at
 Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Users\\amzavery\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\azure\\node_modules\\request\\reque
st.js:1160:14)\n'
silly:   }
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
verbose: Error: null
  <<< async stack >>>
  at __2 (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\resource\resource._js:124:40)
  at resource_createResource__3 (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\resource\resource._js:122:21)
  at __1 (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\resource\resource._js:52:16)
  <<< raw stack >>>
    at C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-mgmt-resource\lib\resourceManagementClient.js:4858:21
    at C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:308:7
    at handleRedirect (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:285:9)
    at C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\lib\util\logging.js:244:7
    at handleRedirect (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\services\filters\redirectfilter.js:36:9)
    at C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:49:7
    at Request._callback (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\amzavery\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\request\request.js:1160:14)

error:   resource create command failed
```

**Comment by bingosummer** [comment]
When I use `azure resource create` to create a storage account, I hit a similar error here with the empty body.

```
C:\Users\binxi>azure resource create binxiga1101 binxiga1101storage3 Microsoft.S
torage/storageAccounts "East Asia" 2015-05-01-preview -p "{\"accountType\":\"Sta
ndard_GRS\"}"
info:    Executing command resource create
+ Getting resource binxiga1101storage3
+ Creating resource binxiga1101storage3
error:   Error
info:    Error information has been recorded to C:\Users\binxi\.azure\azure.err
error:   resource create command failed
```

However, if I use `azure storage account show XXX`, I find that the storage account has been created successfully.

Here is `azure.details.err`.
```
2015-11-02T01:33:24.935Z - info:    Executing command resource create
2015-11-02T01:33:24.958Z - silly:   requestOptions
2015-11-02T01:33:24.959Z - silly:   {
2015-11-02T01:33:24.959Z - silly:       rawResponse: false,
2015-11-02T01:33:24.959Z - silly:       queryString: {},
2015-11-02T01:33:24.959Z - silly:       method: 'GET',
2015-11-02T01:33:24.959Z - silly:       headers: { Content-Type: 'application/json; charset=utf-8', user-agent: 'WindowsAzureXplatCLI/0.9.10' },
2015-11-02T01:33:24.959Z - silly:       url: 'https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourcegroups/binxiga1101/providers/Microsoft.Storage//storageAccounts/binxiga1101storage3?api-version=2015-05-01-preview'
2015-11-02T01:33:24.959Z - silly:   }
2015-11-02T01:33:25.880Z - silly:   returnObject
2015-11-02T01:33:25.881Z - silly:   {
2015-11-02T01:33:25.881Z - silly:       statusCode: 404,
2015-11-02T01:33:25.881Z - silly:       header: {
2015-11-02T01:33:25.881Z - silly:           cache-control: 'no-cache',
2015-11-02T01:33:25.881Z - silly:           pragma: 'no-cache',
2015-11-02T01:33:25.881Z - silly:           content-type: 'application/json; charset=utf-8',
2015-11-02T01:33:25.881Z - silly:           expires: '-1',
2015-11-02T01:33:25.881Z - silly:           x-ms-failure-cause: 'gateway',
2015-11-02T01:33:25.881Z - silly:           x-ms-request-id: '21647add-e856-4555-82e4-88ee366224c2',
2015-11-02T01:33:25.881Z - silly:           x-ms-correlation-request-id: '21647add-e856-4555-82e4-88ee366224c2',
2015-11-02T01:33:25.881Z - silly:           x-ms-routing-request-id: 'JAPANEAST:20151102T013325Z:21647add-e856-4555-82e4-88ee366224c2',
2015-11-02T01:33:25.881Z - silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
2015-11-02T01:33:25.881Z - silly:           date: 'Mon, 02 Nov 2015 01:33:25 GMT',
2015-11-02T01:33:25.881Z - silly:           connection: 'close',
2015-11-02T01:33:25.881Z - silly:           content-length: '168'
2015-11-02T01:33:25.881Z - silly:       },
2015-11-02T01:33:25.881Z - silly:       body: "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Storage/storageAccounts/binxiga1101storage3' under resource group 'binxiga1101' was not found."}}"
2015-11-02T01:33:25.881Z - silly:   }
2015-11-02T01:33:25.887Z - silly:   requestOptions
2015-11-02T01:33:25.887Z - silly:   {
2015-11-02T01:33:25.887Z - silly:       rawResponse: false,
2015-11-02T01:33:25.887Z - silly:       queryString: {},
2015-11-02T01:33:25.887Z - silly:       method: 'PUT',
2015-11-02T01:33:25.887Z - silly:       headers: {
2015-11-02T01:33:25.887Z - silly:           Content-Type: 'application/json; charset=utf-8',
2015-11-02T01:33:25.887Z - silly:           Content-Length: 78,
2015-11-02T01:33:25.887Z - silly:           user-agent: 'WindowsAzureXplatCLI/0.9.10'
2015-11-02T01:33:25.887Z - silly:       },
2015-11-02T01:33:25.887Z - silly:       url: 'https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourcegroups/binxiga1101/providers/Microsoft.Storage//storageAccounts/binxiga1101storage3?api-version=2015-05-01-preview',
2015-11-02T01:33:25.887Z - silly:       body: '{"properties":{"accountType":"Standard_GRS"},"location":"East Asia","tags":{}}'
2015-11-02T01:33:25.887Z - silly:   }
2015-11-02T01:33:28.887Z - silly:   returnObject
2015-11-02T01:33:28.888Z - silly:   {
2015-11-02T01:33:28.888Z - silly:       statusCode: 202,
2015-11-02T01:33:28.888Z - silly:       header: {
2015-11-02T01:33:28.888Z - silly:           cache-control: 'no-cache',
2015-11-02T01:33:28.888Z - silly:           pragma: 'no-cache',
2015-11-02T01:33:28.888Z - silly:           content-length: '0',
2015-11-02T01:33:28.888Z - silly:           expires: '-1',
2015-11-02T01:33:28.888Z - silly:           location: 'https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/providers/Microsoft.Storage/operations/5757d73d-e32c-417f-bce9-e5f31166945d?monitor=true&api-version=2015-05-01-preview',
2015-11-02T01:33:28.888Z - silly:           retry-after: '25',
2015-11-02T01:33:28.888Z - silly:           x-ms-ratelimit-remaining-subscription-writes: '1199',
2015-11-02T01:33:28.888Z - silly:           x-ms-request-id: 'fed98a3e-530f-4972-b19f-f7f7523d2b57',
2015-11-02T01:33:28.888Z - silly:           server: 'Microsoft-HTTPAPI/2.0',
2015-11-02T01:33:28.888Z - silly:           x-ms-correlation-request-id: 'fed98a3e-530f-4972-b19f-f7f7523d2b57',
2015-11-02T01:33:28.888Z - silly:           x-ms-routing-request-id: 'JAPANEAST:20151102T013328Z:fed98a3e-530f-4972-b19f-f7f7523d2b57',
2015-11-02T01:33:28.888Z - silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
2015-11-02T01:33:28.888Z - silly:           date: 'Mon, 02 Nov 2015 01:33:28 GMT',
2015-11-02T01:33:28.888Z - silly:           connection: 'close'
2015-11-02T01:33:28.888Z - silly:       },
2015-11-02T01:33:28.888Z - silly:       body: ''
2015-11-02T01:33:28.888Z - silly:   }
2015-11-02T01:33:28.894Z - error:   Error
2015-11-02T01:33:28.920Z - info:    Error information has been recorded to C:\Users\binxi\.azure\azure.err
```

**Comment by bingosummer** [comment]
Could anyone help on this issue?

**Comment by amarzavery** [comment]
@vivsriaus @ravbhatnagar @tianoMS any update on this issue?

**Comment by ravbhatnagar** [comment]
@amarzavery @bingosummer We will investigate this for Sept release
