### ISSUE TITLE
Azure xplat corporate proxy

### ISSUE THREAD

**Issue by rarevalob** [Azure/azure-xplat-cli#1749]
HI!!

We're having troubles connecting to  Azure from our corporate-proxy. 

We can login or launch querying commands as 'Azure vm  list' 'azure account list' 'azure vm disk list vm-name' without any problem....but when we  launch 'create' commands as 'azure storage account create storage1a' , we are  getting socket errors like ths:

   error:   tunneling socket could not be established, cause=Parse Error
   info:    Error information has been recorded to /home/n032986/.azure/azure.err
   error:   storage account create command failed

azure.err:

   Error: tunneling socket could not be established, cause=Parse Error
     <<< async stack >>>
     at createAccount (/usr/lib/node_modules/azure-cli/lib/commands/storage   /storage.account._js:142:56)
     at storageAccount_createCommand__3 (/usr/lib/node_modules/azure-cli/lib   /commands/storage/storage.account._js:348:5)
     <<< raw stack >>>
       at ClientRequest.onError (/usr/lib/node_modules/azure-cli/node_modules/azure   /node_modules/request/node_modules/tunnel-agent/index.js:168:17)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnData (http.js:1593:9)
    at TCP.onread (net.js:528:27)

Any idea?

See our last proxy reported issue: 

      https://github.com/Azure/azure-xplat-cli/issues/1593

Thanks!

**Comment by rarevalob** [comment]
any idea? Thanks!

**Comment by amarzavery** [comment]
@rarevalob - Please find a link to the documentation that provides a workaround for corporate proxies over [here](https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/CorporateProxy.md).

In the mean time we shall explore further to provide a concrete solution

**Comment by rarevalob** [comment]
Thanks!
