### ISSUE TITLE
Error: The web site <sitename> cannot be found.

### ISSUE THREAD

**Issue by koistya** [Azure/azure-xplat-cli#1754]
```shell
$ azure site domain list example
```

```
Fri May 08 2015 13:00:58 GMT+0300 (Russia TZ 2 Standard Time):
{ [Error: The web site example cannot be found.]
  stack: [Getter/Setter],
  code: 'NotFound',
  extendedcode: '04009',
  messagetemplate: 'The web site {0} cannot be found.',
  parameters: 
   { '$': { 'xmlns:a': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
     'a:string': 'example' },
  innererrors: { '$': { 'i:nil': 'true' } },
  statusCode: 404,
  __frame: 
   { name: 'getSite__8',
     line: 484,
     file: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\websites\\websitesclient._js',
     prev: 
      { name: '__1',
        line: 36,
        file: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\site.domain._js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 12,
        col: 36 },
     calls: 0,
     active: false,
     offset: 17,
     col: 32 },
  rawStack: [Getter] }
Error: The web site example cannot be found.
  <<< async stack >>>
  at getSite__8 (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:501:33)
  at __1 (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.domain._js:48:37)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\request\request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure\node_modules\request\request.js:1111:12)
```

```
iojs v1.8.1
azure v0.9.2
Windows v8.1 (x64)
```

A correct subscription is selected, website exists in Azure portal under this subscription.

**Comment by koistya** [comment]
It seems like it was a temporary error.
