### ISSUE TITLE
repository delete fails with Object #<RepositoryOperations> has no method 'delete'

### ISSUE THREAD

**Issue by mikkark** [Azure/azure-xplat-cli#1794]
I'm trying to delete a repository after the "disconnect from source control" failed (I've never managed to do it succesfully). I thought this would "just work", but it doesn't:

$ azure site repository delete sitenamehere
info:    Executing command site repository delete
Delete repository? [y/n] y
+ Deleting repository files                                                    
error:   Object #<RepositoryOperations> has no method 'delete'
info:    Error information has been recorded to /Users/xxx.err
error:   site repository delete command failed

**Comment by TGVarik** [comment]
I have a similar issue:

```
❯ azure site repository delete site-name
info:    Executing command site repository delete
Delete repository? [y/n] y
+ Deleting repository files
error:   undefined is not a function
info:    Error information has been recorded to /Users/tom/.azure/azure.err
error:   site repository delete command failed
```

Here's `azure.err`:

```
Mon Sep 14 2015 16:36:37 GMT-0700 (PDT):
{ [TypeError: undefined is not a function]
  __frame:
   { name: '__2',
     line: 64,
     file: '/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js',
     prev: undefined,
     calls: 2,
     active: false,
     offset: 16,
     col: 8 },
  rawStack: [Getter] }
TypeError: undefined is not a function
    at __$doDeleteRepository (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js:314:47)
    at __tryCatch (/Users/tom/.npm-packages/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js:313:13)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js:316:13)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js:332:11)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/site.repository._js:351:16)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at __$getHostNameSuffix__14 (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:1106:16)
    at ___ (/Users/tom/.npm-packages/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:1090:19)
```
