### ISSUE TITLE
ARM: Not possible to create PTR DNS record set

### ISSUE THREAD

**Issue by roman-boltunov** [Azure/azure-xplat-cli#1795]
Repro steps:
* create dns-zone record set create for type PTR.
* command fails with unsupported type exception.

**Error: The record type PTR is not supported. Resource records can contain only one type of record specified.**

Here is the -vv output: 
```
D:\Projects\azure-xplat-cli-pr\bin>node azure network dns-zone record-set create crp-dev-test-tm testzone test-ptr-record --type ptr -vv
info:    Executing command network dns-zone record-set create
verbose: Looking up the dns zone "testzone"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json; charset=utf-8', user-agent: 'WindowsAzureXplatCLI/0.9.0' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm/pro
viders/Microsoft.Network/dnszones/testzone?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhd
WQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA
4LyIsImlhdCI6MTQyOTg3NTMwMCwibmJmIjoxNDI5ODc1MzAwLCJleHAiOjE0Mjk4NzkyMDAsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsI
m9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OTg0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29
tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJzdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1Q
GxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzI
iLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.A-g77vNI9EEIwTjRIfw09w9iuLj0F09JWhwe_kqtHPNcgUvRDDqzi4Rz5UakUP__9ftt0a3wsZ8Kt
6O2abrozCj3nCA9bmL7U9bLZRlmSh74_eFfoxI4iiWczJm-lk3-5CRLuygkkqVMqXraRKphZJUg93U4qwmnFmycvnQWesyx1SJ6sW0bfXw1QWnMRvvnP7ch2QeEKutuD6_t7WGP2xamz36FGDS6wN6
bvQi9DLCYAJ9662bgUTURvExcmrNZ3H9g_Yz6DGxYq0juttKqr4x5pwbdWlSLwn7DFIWY5_8yy8TwzqpYEUh-6CLZDJRrUyAboBccMq1EMNpM3Xpecg
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'private',
silly:           content-length: '357',
silly:           content-type: 'application/json; charset=utf-8',
silly:           etag: 'fb3f14f4-0c77-4d3a-9c70-c755c66a75b7',
silly:           x-content-type-options: 'nosniff',
silly:           x-ms-request-id: '1f67aa7d-dcce-42c8-bdb8-ef8b1f78115c',
silly:           server: 'Microsoft-IIS/7.5',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-powered-by: 'ASP.NET',
silly:           x-ms-ratelimit-remaining-subscription-resource-requests: '11991',
silly:           x-ms-correlation-request-id: '3a1ce459-2c01-4205-8430-4c403d2317cc',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T122355Z:3a1ce459-2c01-4205-8430-4c403d2317cc',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Fri, 24 Apr 2015 12:23:55 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{"id":"\\/subscriptions\\/e66a2b71-7bad-41c1-907a-108aa3565c0f\\/resourceGroups\\/crp-dev-test-tm\\/providers\\/Microsoft.Network\
\/dnszones\\/testzone","name":"testzone","type":"Microsoft.Network\\/dnszones","etag":"fb3f14f4-0c77-4d3a-9c70-c755c66a75b7","location":"global","tags
":{"tag1":"dns1","tag2":"dns2-i","tag3":"dns3"},"properties":{"numberOfRecordSets":3}}'
silly:   }
info:    --ttl parameter is not specified, using default TTL - "4"
verbose: Looking up the DNS record set "test-ptr-record"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json; charset=utf-8', user-agent: 'WindowsAzureXplatCLI/0.9.0' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm/pro
viders/Microsoft.Network/dnszones/testzone/ptr/test-ptr-record?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhd
WQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA
4LyIsImlhdCI6MTQyOTg3NTMwMCwibmJmIjoxNDI5ODc1MzAwLCJleHAiOjE0Mjk4NzkyMDAsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsI
m9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OTg0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29
tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJzdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1Q
GxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzI
iLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.A-g77vNI9EEIwTjRIfw09w9iuLj0F09JWhwe_kqtHPNcgUvRDDqzi4Rz5UakUP__9ftt0a3wsZ8Kt
6O2abrozCj3nCA9bmL7U9bLZRlmSh74_eFfoxI4iiWczJm-lk3-5CRLuygkkqVMqXraRKphZJUg93U4qwmnFmycvnQWesyx1SJ6sW0bfXw1QWnMRvvnP7ch2QeEKutuD6_t7WGP2xamz36FGDS6wN6
bvQi9DLCYAJ9662bgUTURvExcmrNZ3H9g_Yz6DGxYq0juttKqr4x5pwbdWlSLwn7DFIWY5_8yy8TwzqpYEUh-6CLZDJRrUyAboBccMq1EMNpM3Xpecg
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-failure-cause: 'gateway',
silly:           x-ms-request-id: 'ff9acad1-6c84-4ff8-9bc4-72eba4200c9c',
silly:           x-ms-correlation-request-id: 'ff9acad1-6c84-4ff8-9bc4-72eba4200c9c',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T122356Z:ff9acad1-6c84-4ff8-9bc4-72eba4200c9c',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Fri, 24 Apr 2015 12:23:55 GMT',
silly:           connection: 'close',
silly:           content-length: '69'
silly:       },
silly:       body: '{"error":{"code":"ResourceNotFound","message":"Resource not found."}}'
silly:   }
verbose: Creating DNS record set "test-ptr-record"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           Content-Length: 54,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.0'
silly:       },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm/pro
viders/Microsoft.Network/dnszones/testzone/ptr/test-ptr-record?api-version=2015-05-04-preview',
silly:       body: '{"properties":{"TTL":4},"location":"global","tags":{}}'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhd
WQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA
4LyIsImlhdCI6MTQyOTg3NTMwMCwibmJmIjoxNDI5ODc1MzAwLCJleHAiOjE0Mjk4NzkyMDAsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsI
m9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OTg0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29
tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJzdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1Q
GxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzI
iLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.A-g77vNI9EEIwTjRIfw09w9iuLj0F09JWhwe_kqtHPNcgUvRDDqzi4Rz5UakUP__9ftt0a3wsZ8Kt
6O2abrozCj3nCA9bmL7U9bLZRlmSh74_eFfoxI4iiWczJm-lk3-5CRLuygkkqVMqXraRKphZJUg93U4qwmnFmycvnQWesyx1SJ6sW0bfXw1QWnMRvvnP7ch2QeEKutuD6_t7WGP2xamz36FGDS6wN6
bvQi9DLCYAJ9662bgUTURvExcmrNZ3H9g_Yz6DGxYq0juttKqr4x5pwbdWlSLwn7DFIWY5_8yy8TwzqpYEUh-6CLZDJRrUyAboBccMq1EMNpM3Xpecg
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'private',
silly:           content-length: '135',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-content-type-options: 'nosniff',
silly:           x-ms-request-id: 'dcfd1ba3-7f48-4897-aa88-9137ebcdcc17',
silly:           server: 'Microsoft-IIS/7.5',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-powered-by: 'ASP.NET',
silly:           x-ms-ratelimit-remaining-subscription-resource-requests: '11994',
silly:           x-ms-correlation-request-id: '6fb0497e-724f-42bd-8b28-f36dacde03d6',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T122358Z:6fb0497e-724f-42bd-8b28-f36dacde03d6',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Fri, 24 Apr 2015 12:23:58 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{"code":"BadRequest","message":"The record type PTR is not supported. Resource records can contain only one type of record specifi
ed."}'
silly:   }
error:   The record type PTR is not supported. Resource records can contain only one type of record specified.
silly:   {
silly:       stack: 'Error: The record type PTR is not supported. Resource records can contain only one type of record specified.\n  <<< async stack >
>>\n  at create__1 (D:\\Projects\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js:34:43)\n  at createDnsRecordSet__61 (D:\\Projects\
\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js:424:18)\n  at __61 (D:\\Projects\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\
\network._js:1189:21)\n  <<< raw stack >>>\n    at Function.ServiceClient._normalizeError (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-commo
n\\lib\\services\\serviceclient.js:815:23)\n    at D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\\errorhandling
filter.js:44:29\n    at Request._callback (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    a
t Request.self.callback (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit
(events.js:110:17)\n    at Request.<anonymous> (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:1
4)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_mod
ules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n',
silly:       message: 'The record type PTR is not supported. Resource records can contain only one type of record specified.',
silly:       code: 'BadRequest',
silly:       statusCode: 400,
silly:       requestId: 'dcfd1ba3-7f48-4897-aa88-9137ebcdcc17',
silly:       __frame: {
silly:           name: 'create__1',
silly:           line: 17,
silly:           file: 'D:\\Projects\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js',
silly:           prev: {
silly:               name: 'createDnsRecordSet__61',
silly:               line: 420,
silly:               file: 'D:\\Projects\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__61',
silly:                   line: 1183,
silly:                   file: 'D:\\Projects\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\network._js',
silly:                   prev: undefined,
silly:                   calls: 4,
silly:                   active: false,
silly:                   offset: 6,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 17
silly:           },
silly:           calls: 2,
silly:           active: false,
silly:           offset: 17,
silly:           col: 42
silly:       },
silly:       rawStack: 'Error: The record type PTR is not supported. Resource records can contain only one type of record specified.\n    at Function.
ServiceClient._normalizeError (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at D:\\Proje
cts\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (D:\\Projects\\azu
re-xplat-cli-pr\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (D:\\Projects\\azure-xplat-cli-pr\\n
ode_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (D:\\Projects
\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingM
essage.<anonymous> (D:\\Projects\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.e
mit (events.js:129:20)\n    at _stream_readable.js:908:16\n'
silly:   }
info:    Error information has been recorded to C:\Users\roman.boltunov\.azure\azure.err
verbose: Error: The record type PTR is not supported. Resource records can contain only one type of record specified.
  <<< async stack >>>
  at create__1 (D:\Projects\azure-xplat-cli-pr\lib\commands\arm\network\dnsRecordSet._js:34:43)
  at createDnsRecordSet__61 (D:\Projects\azure-xplat-cli-pr\lib\commands\arm\network\networkClient._js:424:18)
  at __61 (D:\Projects\azure-xplat-cli-pr\lib\commands\arm\network\network._js:1189:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (D:\Projects\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network dns-zone record-set create command failed
```

**Comment by jtuliani** [comment]
PTR records are not yet supported by the Azure DNS service.  It's work-in-progress, and as a result you stumbled upon the support that is already in place in the Azure CLI.  Apologies for the confusion whilst we build out end-to-end support.

**Comment by amarzavery** [comment]
@MikhailTryakhov @jtuliani - Has this been supported now?

**Comment by jtuliani** [comment]
This is in progress/due to start as part of the change to the 2016-04-01 API version

**Comment by MikhailTryakhov** [comment]
fixed and would be published soon
