### ISSUE TITLE
ARM: Not possible to create SOA DNS record set

### ISSUE THREAD

**Issue by roman-boltunov** [Azure/azure-xplat-cli#1796]
Repro steps:
* create dns-zone record set create for type SOA.
* command fails with missing fields host & email.

Here is the -vv output:
```
node bin/azure network dns-zone record-set create crp-dev-test-tm1 crpdevtestdnszone2 crpdevtestdnszone2rs2 --type SOA -vv
info:    Executing command network dns-zone record-set create
verbose: Looking up the dns zone "crpdevtestdnszone2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.0', Content-Type: 'application/json; charset=utf-8' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'private',
silly:           etag: '27554f58-4b27-4a15-95ec-b9380b1f896c',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: '2866b6f8-579c-4cc9-a8e6-27ed71b4135c',
silly:           x-ms-ratelimit-remaining-subscription-resource-requests: '11994',
silly:           date: 'Fri, 24 Apr 2015 06:48:30 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064831Z:e524b26e-43a3-4a36-b8df-be5ccd5fc64b',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '348',
silly:           x-ms-correlation-request-id: 'e524b26e-43a3-4a36-b8df-be5ccd5fc64b',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: '{"id":"\\/subscriptions\\/e66a2b71-7bad-41c1-907a-108aa3565c0f\\/resourceGroups\\/crp-dev-test-tm1\\/providers\\/Microsoft.Network\\/dnszones\\/c
rpdevtestdnszone2","name":"crpdevtestdnszone2","type":"Microsoft.Network\\/dnszones","etag":"27554f58-4b27-4a15-95ec-b9380b1f896c","location":"global","tags":{"tag1"
:"dns1"},"properties":{"numberOfRecordSets":5}}'
silly:   }
info:    --ttl parameter is not specified, using default TTL - "4"
verbose: Looking up the DNS record set "crpdevtestdnszone2rs2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.0', Content-Type: 'application/json; charset=utf-8' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2/SOA/crpdevtestdnszone2rs2?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'private',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: 'c6991076-f79c-4306-b05f-b1a1f9496503',
silly:           date: 'Fri, 24 Apr 2015 06:48:06 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064806Z:5b5a9673-7add-461b-8652-a4facd731027',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '183',
silly:           x-ms-ratelimit-remaining-subscription-reads: '31997',
silly:           x-ms-correlation-request-id: '5b5a9673-7add-461b-8652-a4facd731027',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: "{"code":"NotFound","message":"The resource record 'crpdevtestdnszone2rs2' does not exist in resource group 'crp-dev-test-tm1' of subscription 'e6
6a2b71-7bad-41c1-907a-108aa3565c0f'."}"
silly:   }
verbose: Creating DNS record set "crpdevtestdnszone2rs2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.0',
silly:           Content-Length: 44,
silly:           Content-Type: 'application/json; charset=utf-8'
silly:       },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2/SOA/crpdevtestdnszone2rs2?api-version=2015-05-04-preview',
silly:       body: '{"properties":{"TTL":4},"location":"global"}'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'private',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1198',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: 'a4628a1c-bb42-4515-9959-673406338508',
silly:           date: 'Fri, 24 Apr 2015 06:48:32 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064833Z:4a50bfc6-8c19-4eae-852b-99a612755638',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '124',
silly:           x-ms-correlation-request-id: '4a50bfc6-8c19-4eae-852b-99a612755638',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: "{"code":"BadRequest","message":"The resource record is missing field 'host'. The resource record is missing field 'email'."}"
silly:   }
error:   The resource record is missing field 'host'. The resource record is missing field 'email'.
silly:   {
silly:       stack: "Error: The resource record is missing field 'host'. The resource record is missing field 'email'.\n  <<< async stack >>>\n  at create__1 (C:\\In
teropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js:34:43)\n  at createDnsRecordSet__61 (C
:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js:424:18)\n  at __61 (C:\\InteropP
rojects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\network._js:1194:21)\n  <<< raw stack >>>\n    at Function.Se
rviceClient._normalizeError (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\servic
eclient.js:815:23)\n    at C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\
\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-c
ommon\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\n
ode_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (C:\\InteropProjects\\XPlat-C
li\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:117
:20)\n    at IncomingMessage.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_mod
ules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n",
silly:       arguments: undefined,
silly:       type: undefined,
silly:       message: "The resource record is missing field 'host'. The resource record is missing field 'email'.",
silly:       code: 'BadRequest',
silly:       statusCode: 400,
silly:       requestId: 'a4628a1c-bb42-4515-9959-673406338508',
silly:       __frame: {
silly:           name: 'create__1',
silly:           line: 17,
silly:           file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js',
silly:           prev: {
silly:               name: 'createDnsRecordSet__61',
silly:               line: 420,
silly:               file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__61',
silly:                   line: 1188,
silly:                   file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\network._js',
silly:                   prev: undefined,
silly:                   calls: 4,
silly:                   active: false,
silly:                   offset: 6,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 17
silly:           },
silly:           calls: 2,
silly:           active: false,
silly:           offset: 17,
silly:           col: 42
silly:       },
silly:       rawStack: "Error: The resource record is missing field 'host'. The resource record is missing field 'email'.\n    at Function.ServiceClient._normalizeEr
ror (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n
at C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:
44:29\n    at Request._callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\http\\reques
t-pipeline.js:109:14)\n    at Request.self.callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-commo
n\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\A
pril23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:117:20)\n    at IncomingMes
sage.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.j
s:1111:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n"
silly:   }
info:    Error information has been recorded to C:\Users\v-bamura\.azure\azure.err
verbose: Error: The resource record is missing field 'host'. The resource record is missing field 'email'.
  <<< async stack >>>
  at create__1 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\dnsRecordSet._js:34:43)
  at createDnsRecordSet__61 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\networkClient._js:424:18)
  at __61 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\network._js:1194:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\services
\serviceclient.js:815:23)
    at C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\http\request-pipeline.js:109:
14)
    at Request.self.callback (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.
js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.js
:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\re
quest.js:1111:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

error:   network dns-zone record-set create command failed
```

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by jtuliani** [comment]
It should not be possible to create a DNS SOA record set.  SOA record sets are created and deleted automatically when the zone is created/deleted.

Thus the following commands should NOT support the SOA record type
- azure network dns record-set create
- azure network dns record-set delete
- azure network dns record-set add-record
- azure network dns record-set delete-record

It *is* possible to update the auto-created SOA record.  Hence the SOA record type should continue to be supported in
- azure network dns record-set show
- azure network dns record-set list
- azure network dns record-set set

This still leaves us with a gap.  'azure network dns record-set set' lets us change record set properties (tags, ttl) but doesn't allow us to change individual records, since that is done cia 'add-record' and 'delete-record'.  However, 'add-record' and 'delete-record' don't work for the SOA, since they can't be added and deleted.

I suggest we add explicit support for the SOA fields in 'azure network dns record-set set', with a clear comment in the help that for other record types, record changes should be made using 'add-record' and 'delete-record'.

We'd need to support all SOA fields except 'host' (which is currently read-only, but will become writable in future).

**Comment by MikhailTryakhov** [comment]
SOA record set command would is implemented and would be merged soon
