### ISSUE TITLE
Failed to authenticate if login account has two factor authentication enabled.

### ISSUE THREAD

**Issue by top2tech** [Azure/azure-xplat-cli#1802]
### Repro:
azure login with a Microsoft account (outlook.com) which has two factor authentication enabled, when asking for password, first time tried the real password, failed to authenticate, then tried app password, also failed to authenticate.

### Error:
Password: ****************
+ Authenticating...
error:   Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
info:    Error information has been recorded to /Users/<user>/.azure/azure.err
error:   login command failed

### cat /Users/<user>/.azure/azure.err
{ [Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE]
  stack: [Getter/Setter],
  __frame:
   { name: 'getSubscriptions',
     line: 23,
     file: '/usr/local/lib/node_modules/azure-cli/lib/util/profile/subscriptionUtils._js',
     prev:
      { name: '__1',
        line: 42,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/login._js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 48,
        col: 43 },
     calls: 0,
     active: false,
     offset: 1,
     col: 32 },
  rawStack: [Getter] }
Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
  <<< async stack >>>
  at getSubscriptions (/usr/local/lib/node_modules/azure-cli/lib/util/profile/subscriptionUtils._js:24:33)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login._js:90:44)
  <<< raw stack >>>
    at Logger.createError (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:196:13)
    at WSTrustResponse.parse (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-response.js:243:23)
    at WSTrustRequest._handleRSTR (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:150:21)
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:183:12
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:137:5)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:824:12)

### Suggestion:
better launch a browser and let the browser to handle the authentication handshake.

**Comment by devigned** [comment]
You must use an azure org account or a service principle to authenticate using Azure CLI. Please see the  the [Log in from the Azure CLI](https://azure.microsoft.com/en-us/documentation/articles/xplat-cli-connect/) article.
