### ISSUE TITLE
Load Balancer Templates Broken - Regression

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-xplat-cli#1822]
Since npm version 0.8.16 load balancer templates haven't been working. Various errors between them but today's error (on version v0.9.2, the version that is free from the regression caused by https://github.com/Azure/azure-sdk-for-node/issues/1431#issuecomment-109358699) is:

```
{ [Error: Cannot find module './lbShowUtil'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './lbShowUtil'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/loadBalancer._js:5:18)
    at Module._compile (module.js:460:26)
    at Module.pModule._compile (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.streamliners._js [as ._js] (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/underscored.js:120:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

It simply appears like something is missing.

This blocks really important templates for anything with multiple virtual machines that don't want to use public ips for each machine. (Like CoreOS, Deis, plus future stuff Etc.)

**Comment by yugangw-msft** [comment]
I hit this error yesterday. After i cleaned up the ".streamline" folder, this issue went away.  Let me know whether this does the trick for you as well.

**Comment by sedouard** [comment]
thanks @yugangw-msft can you specify where the `.streamline` in relation to the package root?

**Comment by yugangw-msft** [comment]
In my mac, it is under "/users/<your name>/.streamline"., where the streamline package used by CLI dynamically compiles all ._js files

**Comment by sedouard** [comment]
that appears to fix it. but question is why does this start reproducing at `0.8.16`? Rolling back to `0.8.15` allows this to work. maybe you aren't using streamline before then?

Probably good to mention this trick somewhere besides buried in a an issue somewhere.

**Comment by yugangw-msft** [comment]
It is streamline bug/limitation. The streamline package has been used since the very early period of cli for easy coding. We have known such issues, but rewriting commands is not trivial undertake. 
I will mention in the readme.

**Comment by sedouard** [comment]
Awesome thanks for looking into it!
