### ISSUE TITLE
cli.interaction.promptifNotGiven method should validate null value

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1847]
Do an azure network vnet list
Cmd run will prompt for resource group name
Just hit enter without mentioning resource group name.
 command fails with api invalid error. 

This is pretty much common error for all commands. 

Ideally the fix should be in cli.interaction.promptIfNotGiven method. This method should fail if use provide empty/ null value.

__Verbose output below:__

```
$ node bin/azure network vnet list --verbose
info:    Executing command network vnet list
Resource group name:
verbose: Listing virtual networks
error:   The api-version '2015-05-01-preview' is invalid. The supported versions are '2015-01-01,2014-04-01-preview,2014-04-0
1,2014-01-01,2013-03-01,2014-02-26,2014-04'.
info:    Error information has been recorded to c:\Users\v-bamura\.azure\azure.err
verbose: Error: The api-version '2015-05-01-preview' is invalid. The supported versions are '2015-01-01,2014-04-01-preview,20
14-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
  <<< async stack >>>
  at list__5 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\vnet._js:176:66)
  at listVNet__3 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\networkClient._js:5
8:10)
  at __3 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\network._js:91:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\az
ure-common\lib\services\serviceclient.js:815:23)
    at c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\lib\services\filters\errorhan
dlingfilter.js:44:29
    at Request._callback (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\lib\http\r
equest-pipeline.js:109:14)
    at Request.self.callback (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\node_m
odules\request\request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\node_mod
ules\request\request.js:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\
node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

error:   network vnet list command failed

```

**Comment by yugangw-msft** [comment]
I have a PR for this, but after went through the code review, it turns out be a better time to merge it in the next sprint. Doing it now will expose a code bug in storage commands' common code that it passes in the "null" to the routine and expect it be a no-op. The storage team has already fixed in their branch and plan to merge next sprint.
@babumuralidharan, let me know if you have any opinions/comments

**Comment by mayurid** [comment]
@yugangw-msft : Do we still have what we need to do here? Was the storage issue fixed.

**Comment by yugangw-msft** [comment]
@mayurid  storage code was fixed, so we can continue the fix at our end. Note, this is a rather minor issue, and we can also live with it.
