### ISSUE TITLE
Not able to use XPLAT CLI in China Azure

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-xplat-cli#1880]
Hi,

I am using a partner account (21vianet) to manage a subscription in China.
I am looking to use XPLAT for managing websites, SQL and Storage in the subscription.

Am not able to login using the china account i have. Please let me know why is this happening.
Please Note: I have a different Microsoft account and managing the resources in a North America Subscription.

Below is the error message:

Username: xxxxxxxxx@chinaford.partner.onmschina.cn
Password: ***********
+ Authenticating...
error:   Server returned an unknown AccountType: undefined
info:    Error information has been recorded to C:\Users\xxxxx\.azure\azure.err
error:   login command failed

Error from azure.err:

Thu Jun 25 2015 15:08:40 GMT-0400 (Eastern Daylight Time):
{ [Error: Server returned an unknown AccountType: undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'getSubscriptions',
     line: 23,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\util\\profile\\subscriptionUtils.js',
     prev: 
      { name: '__1',
        line: 42,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 48,
        col: 43 },
     calls: 0,
     active: false,
     offset: 1,
     col: 32 },
  rawStack: [Getter] }
Error: Server returned an unknown AccountType: undefined
  <<< async stack >>>
  at getSubscriptions (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\profile\subscriptionUtils.js:24:33)
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:90:44)
  <<< raw stack >>>
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:196:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-request.js:379:46
    at UserRealm._parseDiscoveryResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\user-realm.js:234:3)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\user-realm.js:263:12
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:137:5)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:824:12)

Thanks,
Pradebban Raja

**Comment by yugangw-msft** [comment]
Similar #1843, please check that out and follow instructions there. This is an issue from xplat side. 
you can also consider to using certificate, unless your use new ARM commands

**Comment by yugangw-msft** [comment]
Please feel free to reopen it with more data. Thanks.
