### ISSUE TITLE
azure site repository sync: utils is not defined

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-xplat-cli#1892]
Hi,
When I run this command:

    azure site repository sync <sitename>

I'm getting an error:
```
Mon Jun 29 2015 19:08:04 GMT-0700 (Pacific Daylight Time):
{ [ReferenceError: utils is not defined]
  __frame: 
   { name: 'ensureRepositoryUri__17',
     line: 810,
     file: 'C:\\Users\\albati\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\websites\\websitesclient._js',
     prev: 
      { name: '__3',
        line: 92,
        file: 'C:\\Users\\albati\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\site.repository._js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 12,
        col: 13 },
     calls: 1,
     active: true,
     offset: 3,
     col: 24 },
  rawStack: [Getter] }
ReferenceError: utils is not defined
    at createService (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:266:23)
    at Object.exports.createWebsiteManagementService (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:272:10)
    at WebsitesClient.__.extend.syncRepository (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:507:28)
    at AzureCli.site.doRepositorySync (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site._js:1159:26)
    at __$__3 (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:118:25)
    at ___ (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:125:11)
    at ___ (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at __$ensureRepositoryUri__17 (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1325:18)
    at __$ensureRepositoryUri__17 (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1316:13)
    at ___ (C:\Users\albati\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1319:11)
```

**Comment by markcowl** [comment]
@abatishchev Thanks for reporting the issue, forwarding to the appropriate team for investigation.  Can you tell us which version of the cli you are using? (executing the  'azure' command should tell us)

**Comment by abatishchev** [comment]
@markcowl, sure thing
```
info:    Microsoft Azure: Microsoft's Cloud Platform
info:    Tool version 0.9.5
```

**Comment by gavdraper** [comment]
Also getting this same issue on OS X running version 0.9.9 of the cli tools

**Comment by yugangw-msft** [comment]
@gavdraper, if you remove the '.streamline' folder under your user folder, does that help?

**Comment by fpereira1** [comment]
@yugangw-msft I don't see a `.stramline` folder under my user folder `~/`

**Comment by fpereira1** [comment]
https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/utils.js#L404

@yugangw-msft - Looking at this line above, shouldn't it written as:

    }).withFilter(new RequestLogFilter(log));

instead of:

    }).withFilter(new utils.RequestLogFilter(log));

**Comment by fpereira1** [comment]
I've submitted a PR for this issue, it looks like it was introduced in a refactoring task in https://github.com/Azure/azure-xplat-cli/commit/b1c23942cd12df3e279ffea7338fff79a401ff13#diff-0261004ab0f5706809fa8fe41a29f27aL118
