### ISSUE TITLE
Authenticating twice simultaneously results in ambiguous token error.

### ISSUE THREAD

**Issue by karlaugsten** [Azure/azure-xplat-cli#1902]
I was running tests in parallel and ran into an error when trying to log the same user on in different powershell jobs. The full stack trace is here:

```
PS C:\Project1> azure group show bum
info:    Executing command group show
- Listing resource groupsinfo:    228e1011-cb76-4c90-a5d7-b507da5f4545 - Authority: VERBOSE: Performing instance discovery: https://login.windows.net/b60c3614-9e51-4024-90d6-4e9bdab65b6a
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - Authority: VERBOSE: Performing static instance discovery
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - Authority: VERBOSE: Authority validated via static instance discovery.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - TokenRequest: INFO: Getting token from cache with refresh if necessary.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - CacheDriver: VERBOSE: finding with query:{"clientId":"","userId":""}
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - CacheDriver: VERBOSE: Looking for potential cache entries:
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - CacheDriver: VERBOSE: {"_clientId":"","userId":""}
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - CacheDriver: VERBOSE: Found 2 potential entries.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - CacheDriver: ERROR: More than one token matches the criteria.  The result is ambiguous.
Stack:
Error: More than one token matches the criteria.  The result is ambiguous.
    at Logger.createError (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\log.js:196:13)
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:227:28
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:167:5
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:172:7
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\win-token-storage.js:149:7)
    at Stream.emit (events.js:129:20)
    at drain (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:34:23)
    at Stream.stream.queue.stream.push (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:45:5)
    at Stream.end (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:15:35)

error:   Error: More than one token matches the criteria.  The result is ambiguous.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - TokenRequest: WARNING: Attempt to look for token in cache resulted in Error: Error: More than one token matches the criteria.  The result is ambiguous.
    at Logger.createError (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\log.js:196:13)
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:227:28
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:167:5
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:172:7
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\win-token-storage.js:149:7)
    at Stream.emit (events.js:129:20)
    at drain (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:34:23)
    at Stream.stream.queue.stream.push (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:45:5)
    at Stream.end (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\through\index.js:15:35)

info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - TokenRequest: VERBOSE: No appropriate cached token found.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - TokenRequest: ERROR: Entry not found in cache.
Stack:
Error: Entry not found in cache.
    at Logger.createError (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\log.js:196:13)
    at TokenRequest.<anonymous> (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\token-request.js:468:40)
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\token-request.js:138:20
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:353:7
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:227:9
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\node_modules\adal-node\lib\cache-driver.js:167:5
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:172:7
    at C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Users\karlaug\AppData\Roaming\npm\node_modules\azure-cli\lib\util\authentication\win-token-storage.js:149:7)
    at Stream.emit (events.js:129:20)

error:   Error: Entry not found in cache.
info:    228e1011-cb76-4c90-a5d7-b507da5f4545 - TokenRequest: VERBOSE: getTokenFunc returned with err
+
error:   Credentials have expired, please reauthenticate Detailed error message from ADAL is as follows: Error: Entry not found in cache.
info:    Error information has been recorded to C:\Users\karlaug\.azure\azure.err
error:   group show command failed
```

Looks like the cli retrieves and stores two different tokens then doesn't know what to do with them. It could be a possible race condition or bug.

Thanks.

**Comment by devigned** [comment]
@yugangw-msft or @amarzavery this seems odd. Any thoughts on why this is happening?

**Comment by yugangw-msft** [comment]
This is a known limitation on cli, though we can improve. For token persistence, there is no protection under parallel situation. It is possible, 2 command simultaneously triggers token refresh which ends up having 2 similar tokens in the security store, and later when cli retrieves token through adal so to send request on the wire, adal sees 2 matches and then throw.
We will need to have IPC mechanism to prevent the token storage from getting corrupted.

**Comment by markcowl** [comment]
we could consider a file locking mechanism for the token cache

**Comment by swapnilpotnis** [comment]
The issue still persists now "More than one token matches the criteria. The result is ambiguous." which is the reason why I have landed upon this thread.
@markcowl : is there anything which a user can do to resolve it??
