### ISSUE TITLE
azure login does not work with passwords containing &

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1918]
I have an ampersand (`&`) in my password and apparently xplat-cli is sending the password **unescaped** as part of the URL parameters (totally my guess) and it probably looks like:

    ?username=foo@example.com&password=myPass&word

so it doesn't work and I'm locked out after a password change.  Can you please prioritize for the next release?

```
➜  ~  azure login
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: foo@microsoft.com
Password: **********
+ Authenticating...
error:   WS-Trust RST request returned http error: 400
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   login command failed
```

**Comment by devigned** [comment]
This is probably happening in the ADAL.js code. To verify what is happening, set the AZURE_ADAL_LOGGING_ENABLED env var to 1 (or anything truthy) and gather the debug output. This should have all we need to repro.

If you post the debug output back here, make sure there is no sensitive information in the output. If you don't want to post back here, you can send to me directly.

**Comment by skarademir** [comment]
Looks like there is no escaping of the password before sending it over the wire via Oauth request

Here's the full stack:
[ cli.command('login [username]')](https://github.com/Azure/azure-xplat-cli/blob/436e5cef4794f516f8af1fd8204693d84c0f50ec/lib/commands/login._js#L34)
```
      var password = cli.interaction.promptPasswordOnceIfNotGiven('Password: ', options.password, _);

      var progress = cli.interaction.progress($('Authenticating...'));
      try {
        adalAuth.logoutUser(username, _);
        var newSubscriptions = environment.addAccount(username, password, tenant, options.servicePrincipal, _);
```
[promptPasswordOnceIfNotGiven: function (promptString, currentValue, _)](https://github.com/Azure/azure-xplat-cli/blob/99c02e66ee24c31750d3e0a1503c9da9646e8938/lib/util/interaction._js#L205)
```
var value = this.promptPasswordOnce(promptString, _);
```
[passwordOnce: function (currentStr, mask, callback)](https://github.com/Azure/azure-xplat-cli/blob/99c02e66ee24c31750d3e0a1503c9da9646e8938/lib/util/interaction._js#L275)
builds a string from user keystrokes called buf and returns it to a callback 
```
      // Return password in the buffer on enter key press
      if (character === '\015') {
        process.stdin.pause();
        process.stdin.removeAllListeners('data');
        process.stdout.write('\n');
        process.stdin.setRawMode(false);

        return callback(buf);
```
We then percolating back up to cli.command login where we then use it buf (now called password) for the  addAccount call
[environment.addAccount: function (username, password, tenant, loginAsServicePrincipal, callback) ](https://github.com/Azure/azure-xplat-cli/blob/bfe1a006e44281cf0cadfc9d5145d0170223e0fd/lib/util/profile/environment.js#L151)
```
    if (!loginAsServicePrincipal) {
      subscriptionUtils.getSubscriptions(self, username, password, tenant, processSubscriptions);
    } 
```
[environment.getSubscriptions(environment, username, password, tenant, callback)](https://github.com/Azure/azure-xplat-cli/blob/99c02e66ee24c31750d3e0a1503c9da9646e8938/lib/util/profile/subscriptionUtils.js#L25)
```
  environment.acquireToken(username, password, tenant, function (err, authContext) {
```
[environment.acquireToken : function (username, password, tenantId, callback)](https://github.com/Azure/azure-xplat-cli/blob/bfe1a006e44281cf0cadfc9d5145d0170223e0fd/lib/util/profile/environment.js#L195)
```
    adalAuth.acquireToken(this.getAuthConfig(tenantId), username, password, callback);
```
[adalAuth.acquireToken(authConfig, username, password, callback)](https://github.com/Azure/azure-xplat-cli/blob/4a9a419761af4efd22924e73eac1b5851c8f071e/lib/util/authentication/adalAuth.js#L234)
```
  context.acquireTokenWithUsernamePassword(authConfig.resourceId, username, password, authConfig.clientId
```
Now we enter azure-activedirectory-library-for-nodejs territory
[AuthenticationContext.prototype.acquireTokenWithUsernamePassword = function(resource, username, password, clientId, callback)](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/70f016a6bf1819364f076f20c99f37c5e0304d47/lib/authentication-context.js#L236)
```
  try {
    argument.validateStringParameter(resource, 'resource');
    argument.validateStringParameter(username, 'username');
    argument.validateStringParameter(password, 'password');
    argument.validateStringParameter(clientId, 'clientId');
  } catch(err) {
    callback(err);
    return;
  }

  this._acquireToken(callback, function() {
    var tokenRequest = new TokenRequest(this._callContext, this, clientId, resource);
    tokenRequest.getTokenWithUsernamePassword(username, password, callback);
  });
```

[TokenRequest.prototype.getTokenWithUsernamePassword = function(username, password, callback)](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/3e622dd7d447aea2bd86173d8431da1c88a26c7e/lib/token-request.js#L358)
```
 case AccountType.Managed:
          self._getTokenUsernamePasswordManaged(username, password, getTokenCompleteCallback);
          return;
```
[TokenRequest.prototype._getTokenUsernamePasswordManaged = function(username, password, callback)] (https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/70f016a6bf1819364f076f20c99f37c5e0304d47/lib/token-request.js#L202 )
```
  oauthParameters[OAuth2Parameters.PASSWORD] = password;
  oauthParameters[OAuth2Parameters.USERNAME] = username;

  this._oauthGetToken(oauthParameters, callback);
 ```
Goes to
[OAuth2Client.prototype.getToken = function (oauthParameters, callback)](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/70f016a6bf1819364f076f20c99f37c5e0304d47/lib/oauth2client.js#L296)
```
 var urlEncodedTokenRequestForm = querystring.stringify(oauthParameters);
```
Which calls the node.js [querystring.stringify call](https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options) which doesn't do any sort of encoding on the object by default.

I've noticed that environment.addAccount will make a call to normalize the username string with:
```
    username = adalAuth.normalizeUserName(username);
```
Perhaps this would one place to add calls to escape the password, though it is also valid to have ADAL escape the strings it is passing into the oauth call.

**Comment by ahmetalpbalkan** [comment]
@devigned hmm it doesn't look like it's sent in the URL (search for `myPassword&` below)

```
- Authenticating...info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - Authority: VERBOSE: Performing instance discovery: https://login.windows.net/common
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - Authority: VERBOSE: Performing static instance discovery
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - Authority: VERBOSE: Authority validated via static instance discovery.
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - TokenRequest: INFO: Acquiring token with username password
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - CacheDriver: VERBOSE: finding with query:{"clientId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","userId":"foo@microsoft.com"}
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - CacheDriver: VERBOSE: Looking for potential cache entries:
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - CacheDriver: VERBOSE: {"_clientId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","userId":"foo@microsoft.com"}
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - CacheDriver: VERBOSE: Found 0 potential entries.
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - TokenRequest: VERBOSE: No appropriate cached token found.
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE: Performing user realm discovery at: https://login.windows.net/common/UserRealm/foo%40microsoft.com?api-version=1.0
\info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: INFO: User Realm DiscoveryServer returned this correlationId: 6e693c9f-a5b5-4fbc-8575-cc0da11c56c5
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE: Discovery response:
{"ver":"1.0","account_type":"Federated","domain_name":"microsoft.com","federation_protocol":"WSTrust","federation_metadata_url":"https://msft.sts.microsoft.com/adfs/services/trust/mex","federation_active_auth_url":"https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed"}
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE: UserRealm response:
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE:  AccountType:             federated
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE:  FederationProtocol:      wstrust
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE:  FederationMetatdataUrl:  https://msft.sts.microsoft.com/adfs/services/trust/mex
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - UserRealm: VERBOSE:  FederationActiveAuthUrl: https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - TokenRequest: VERBOSE: Acquiring token with username password for federated user
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - TokenRequest: VERBOSE: Attempting mex at: https://msft.sts.microsoft.com/adfs/services/trust/mex
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - MEX: VERBOSE: Mex created with url: https://msft.sts.microsoft.com/adfs/services/trust/mex
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - MEX: VERBOSE: Retrieving mex at: https://msft.sts.microsoft.com/adfs/services/trust/mex
|info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - MEX: VERBOSE: found matching policy id: UserNameWSTrustBinding_IWSTrust13Async_policy
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - MEX: VERBOSE: found binding matching Action and Transport: UserNameWSTrustBinding_IWSTrust13Async
info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - WSTrustRequest: VERBOSE: Sending RST to: https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed
<s:Envelope xmlns:s='http://www.w3.org/2003/05/soap-envelope' xmlns:wsa='http://www.w3.org/2005/08/addressing' xmlns:wsu='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'>      <s:Header>        <wsa:Action s:mustUnderstand='1'>http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue</wsa:Action>        <wsa:messageID>urn:uuid:eb191925-657b-4a7a-976e-c53b3c317c0e</wsa:messageID>        <wsa:ReplyTo>          <wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>        </wsa:ReplyTo>        <wsa:To s:mustUnderstand='1'>https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed</wsa:To>        <wsse:Security s:mustUnderstand='1' xmlns:wsse='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'>    <wsu:Timestamp wsu:Id='_0'>      <wsu:Created>2015-07-14T20:11:36.993Z</wsu:Created>      <wsu:Expires>2015-07-14T20:21:36.993Z</wsu:Expires>    </wsu:Timestamp><wsse:UsernameToken wsu:Id='ADALUsernameToken'>    <wsse:Username>foo@microsoft.com</wsse:Username>    <wsse:Password>myPassword&</wsse:Password>  </wsse:UsernameToken></wsse:Security>      </s:Header>      <s:Body>        <wst:RequestSecurityToken xmlns:wst='http://docs.oasis-open.org/ws-sx/ws-trust/200512'>          <wsp:AppliesTo xmlns:wsp='http://schemas.xmlsoap.org/ws/2004/09/policy'>            <wsa:EndpointReference>              <wsa:Address>urn:federation:MicrosoftOnline</wsa:Address>            </wsa:EndpointReference>          </wsp:AppliesTo>          <wst:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer</wst:KeyType>          <wst:RequestType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue</wst:RequestType>        </wst:RequestSecurityToken>      </s:Body>    </s:Envelope>
/info:    6e693c9f-a5b5-4fbc-8575-cc0da11c56c5 - WSTrustRequest: ERROR: WS-Trust RST request returned http error: 400
Stack:
Error: WS-Trust RST request returned http error: 400
    at Logger.createError (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:196:13)
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:133:25)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:129:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:873:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by skarademir** [comment]
Federated logins are a separate rabbit hole and actually DO NOT have any character escaping:
[WSTrustRequest.prototype._populateRSTUsernamePassword = function(RSTTemplate, username, password)](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/70f016a6bf1819364f076f20c99f37c5e0304d47/lib/wstrust-request.js#L101)
```
  var RST = RSTTemplate.replace(USERNAME_PLACEHOLDER, username).replace(PASSWORD_PLACEHOLDER, password);
```

**Comment by devigned** [comment]
@skarademir thank you for the awesome debugging!

**Comment by hveiras** [comment]
+1 I had the same issue. I confirm it was for the & in the password.

**Comment by ahmetalpbalkan** [comment]
@hveiras this should be in the next release, I think it's fixed in the https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/62 upstream.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, i picked up the version containing the fix. Note the fix is only applicable on federated account like our MS org id. For regular AAD accounts, it has always worked, so not impacted by this change.

**Comment by yugangw-msft** [comment]
fixed.
