### ISSUE TITLE
azure account list : Object has no method readConfig

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#1932]
[samanoha@bigboy test]$ azure account list
info:    Executing command account list
error:   Object #<Object> has no method 'readConfig'
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   account list command failed

[samanoha@bigboy test]$ azure -v
0.9.5
[samanoha@bigboy test]$ cat /home/samanoha/.azure/azure.err
Fri Jul 17 2015 00:48:40 GMT+0300 (EEST):
{ [TypeError: Object #<Object> has no method 'readConfig']
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
TypeError: Object #<Object> has no method 'readConfig'
  <<< async stack >>>
    at __1 (/usr/lib/node_modules/azure-cli/lib/commands/account._js:23:19)
  <<< raw stack >>>
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/commands/account._js:23:19)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__1 (/usr/lib/node_modules/azure-cli/lib/commands/account._js:21:12)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/lib/cli.js:216:12)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at AzureCli.emit (events.js:98:17)
    at AzureCli.Command.parseArgs (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:405:12)
    at AzureCli.Command.parse (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:351:15)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/lib/cli.js:510:20)
    at AzureCli.emit (events.js:95:17)

**Comment by amarzavery** [comment]
@infosatheesh2020 

Can you please provide the following info:
- node version (node -v)
- operating system and version
- how did you install (via npm or mac installer)

can you execute  "azure account clear -q" and re-execute azure account list?

If that does not work then, may be the streamline files would be corrupted.

Can you remove the .streamline and .azure directories inside the user's home directory and retry?

**Comment by infosatheesh2020** [comment]
Thanks! it resolved after removed .azure and .streamline directory

FYI
Node Version: v0.10.36
OS: Fedora Release 22
Install: npm install -g azure-cli
