### ISSUE TITLE
website scale to a specific number of instance not working 

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-xplat-cli#1950]
Hey
I tried to run this command: 
azure site scale instances 5 MyWebSite
And it failed, with the following error in the log:
Thu Jul 23 2015 09:40:45 GMT+0300 (Jerusalem Daylight Time):
{ [TypeError: Cannot call method 'charAt' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: '__2',
     line: 69,
     file: 'C:\\Appium\\node_modules\\azure-cli\\lib\\commands\\asm\\site.scale._js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 15,
     col: 36 },
  rawStack: [Getter] }
TypeError: Cannot call method 'charAt' of undefined
  <<< async stack >>>
    at ___ (C:\Appium\node_modules\azure-cli\lib\commands\asm\site.scale._js:70:46)
    at ___ (C:\Appium\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at getSite__8 (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:759:20)
  at __2 (C:\Appium\node_modules\azure-cli\lib\commands\asm\site.scale._js:84:37)
  <<< raw stack >>>
    at ___ (C:\Appium\node_modules\azure-cli\lib\commands\asm\site.scale._js:70:46)
    at ___ (C:\Appium\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at __$getSite__8 (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:759:20)
    at __tryCatch (C:\Appium\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:758:11)
    at ___ (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:750:19)
    at __tryCatch (C:\Appium\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:748:15)
    at __$getSite__8 (C:\Appium\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:745:17)
    at __tryCatch (C:\Appium\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:150:4)

My environment:
Windows 8
Node v0.10.26
Npm v1.4.6
Azure cli 0.9.6

**Comment by ahmedelnably** [comment]
Thanks for reporting this issue, we are looking into that and will follow up soon

**Comment by qbikez** [comment]
this duplicates #2642

**Comment by fatso83** [comment]
A fix for this has existed in qbikez/azure-xplat-cli#1 since April.
