### ISSUE TITLE
CLI dies with "SyntaxError: Unexpected token" on JSON with BOM

### ISSUE THREAD

**Issue by kolbe** [Azure/azure-xplat-cli#1966]
I'm using Azure CLI 0.9.6 (node: 0.10.23).

I have a utf8-encoded template file that happens to start with a utf8 BOM (0xefbbbf). I think this is added automatically by many editors on Windows or perhaps by Windows itself(?). It seems like it would be good for the CLI to be able to handle template files that work fine w/ the Portal web UI.

Removing the 3-byte BOM allows the CLI to handle the template as expected.

```
$ azure group deployment create --template-file azuredeploy.json mdbec1
info:    Executing command group deployment create
info:    Supply values for the following parameters
error:   Unexpected token
info:    Error information has been recorded to /Users/kolbe/.azure/azure.err
error:   group deployment create command failed
```

```
$ cat /Users/kolbe/.azure/azure.err
Thu Jul 30 2015 13:04:55 GMT-0700 (PDT):
{ [SyntaxError: Unexpected token ]
  stack: [Getter/Setter],
  __frame:
   { name: 'getTemplateParams',
     line: 362,
     file: '/usr/local/azure/lib/commands/arm/group/groupUtils.js',
     prev:
      { name: 'createDeploymentParameters',
        line: 249,
        file: '/usr/local/azure/lib/commands/arm/group/groupUtils.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 22,
        col: 25 },
     calls: 1,
     active: false,
     offset: 3,
     col: 4 },
  rawStack: [Getter] }
SyntaxError: Unexpected token
  <<< async stack >>>
    at Object.parse (native)
    at getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:359:29)
  at getTemplateParams (/usr/local/azure/lib/commands/arm/group/groupUtils.js:365:5)
  at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:271:26)
  at exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:28)
  at __1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:53:35)
  <<< raw stack >>>
    at Object.parse (native)
    at __$getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:359:29)
    at __$getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:356:74)
    at __$getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:356:90)
    at __$getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:346:47)
    at __$getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:349:221)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at getTemplateContent (/usr/local/azure/lib/commands/arm/group/groupUtils.js:339:101)
    at __$getTemplateParams (/usr/local/azure/lib/commands/arm/group/groupUtils.js:365:18)
    at __$getTemplateParams (/usr/local/azure/lib/commands/arm/group/groupUtils.js:365:157)
```

```
$ hexdump -C azuredeploy.json | head
00000000  ef bb bf 7b 0a 20 20 20  20 22 24 73 63 68 65 6d  |...{.    "$schem|
00000010  61 22 3a 20 22 68 74 74  70 3a 2f 2f 73 63 68 65  |a": "http://sche|
00000020  6d 61 2e 6d 61 6e 61 67  65 6d 65 6e 74 2e 61 7a  |ma.management.az|
00000030  75 72 65 2e 63 6f 6d 2f  73 63 68 65 6d 61 73 2f  |ure.com/schemas/|
```

**Comment by yugangw-msft** [comment]
this is just a bug that the cmdlet implementation misses a line of invoking the util method to strip the BOM. 
fixing it...

**Comment by yugangw-msft** [comment]
@vivsriaus,let me know if you have any comments

**Comment by alexandreweiss** [comment]
@yugangw-msft 
I'm using 0.9.12 and nodejs 0.10.36 and still have the same problem with a template coming from VisualStudio 2015. Do you want me to supply more info. (alias alweiss) 
Thanks ! Alex
info:    Executing command group deployment create
verbose: Initializing template configurations and parameters
error:   Unexpected token }
info:    Error information has been recorded to /home/adm-carrefour/.azure/azure.err
verbose: SyntaxError: Unexpected token }
  <<< async stack >>>
    at Object.parse (native)
    at getTemplateContent (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:322:27)
  at __2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:257:31)
  at createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:252:19)
  at exports_createDeployment__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:69:28)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:51:35)
  <<< raw stack >>>
    at Object.parse (native)
    at __$getTemplateContent (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:322:27)
    at __$getTemplateContent (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:319:72)
    at __$getTemplateContent (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:319:88)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at getTemplateContent (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:304:101)
    at __$__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:257:22)
    at __$__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:262:122)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:252:207)
error:   group deployment create command failed
