### ISSUE TITLE
ARM: Unable to add a nic in address-pool due to the error: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by AndreyVavilov** [Azure/azure-xplat-cli#2013]
Found issue in network nic address-pool add command:

```
E:\>azure network nic address-pool add pxc pxc-node1-nic -l pxc-lb -a pxc-lb-pool
info:    Executing command network nic address-pool add
+ Looking up the network interface "pxc-node1-nic"
+ Looking up the load balancer "pxc-lb"
error:   Cannot read property 'get' of undefined
info:    Error information has been recorded to C:\Users\av\.azure\azure.err
error:   network nic address-pool add command failed


E:\>type C:\Users\av\.azure\azure.err
Tue Aug 11 2015 22:41:18 GMT+0300 (RTZ 2 (╨╖╨╕╨╝╨░)):
{ [TypeError: Cannot read property 'get' of undefined]
  __frame:
   { name: '_updateAddressPool__12',
     line: 289,
     file: 'C:\\Users\\av\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\network\\nic._js',
     prev:
      { name: 'addAddressPool__8',
        line: 273,
        file: 'C:\\Users\\av\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\network\\nic._js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 1,
        col: 9 },
     calls: 2,
     active: false,
     offset: 34,
     col: 37 },
  rawStack: [Getter] }
TypeError: Cannot read property 'get' of undefined
    at __$get__4 (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:244:74)
    at __tryCatch (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:243:17)
    at ___ (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:249:17)
    at __$get__4 (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:264:15)
    at __tryCatch (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:240:11)
    at ___ (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:270:11)
    at __$get__4 (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\network\loadBalancer._js:286:9)
    at __func (C:\Users\av\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:47:5)


```

And current state:

```
E:\>azure group list
info:    Executing command group list
+ Listing resource groups
data:    Name                         Location     Provisioning State  Tags:
data:    ---------------------------  -----------  ------------------  -----
data:    pxc                          westeurope   Succeeded           null
info:    group list command OK

E:\>azure network nic list pxc
info:    Executing command network nic list
+ Getting the network interfaces
data:    Name           Location    MAC Address        Internal DNS name  Internal FQDN  Enable IP forwarding
data:    -------------  ----------  -----------------  -----------------  -------------  --------------------
data:    pxc-node1-nic  westeurope  (hidden)                                             false
data:    pxc-node2-nic  westeurope  (hidden)                                             false
info:    network nic list command OK

E:\>azure network lb list pxc
info:    Executing command network lb list
+ Getting the load balancers
data:    Name    Location
data:    ------  ----------
data:    pxc-lb  westeurope
info:    network lb list command OK

E:\>azure network lb address-pool list pxc pxc-lb
info:    Executing command network lb address-pool list
+ Looking up the load balancer "pxc-lb"
data:    Name         Provisioning state
data:    -----------  ------------------
data:    pxc-lb-pool  Succeeded
info:    network lb address-pool list command OK
```

**Comment by romangromov** [comment]
@AndreyVavilov thanks, fix merged into `dev` branch

**Comment by romangromov** [comment]
@yugangw-msft fix was merged to latest release, hence can we close this issue?

**Comment by yugangw-msft** [comment]
certainly.
