### ISSUE TITLE
azure vm image list "northeurope" "Canonical" throws getaddrinfo ENOTFOUND management.azure.com

### ISSUE THREAD

**Issue by adrianhopebailie** [Azure/azure-xplat-cli#2015]
I am using the CLI with Azure Resource Manager
i.e. I have called `azure config mode arm`

If I call:
`azure vm image list-publishers "northeurope"`
"Canonical" is listed as a publisher.

But if I try:
`azure vm image list "northeurope" "Canonical"`
I get the error:
`error:   getaddrinfo ENOTFOUND management.azure.com`

`azure vm image list "northeurope" "GitHub"` works fine, as does `azure vm image list "northeurope" "Microsoft"`

I have tried pinging management.azure.com but get no reply.

Running Azure CLI docker container on Ubuntu 14 LTS

Full screen dump here with full publisher list trimmed slightly:

```
root@e584e195d664:/# azure vm image list-publishers -v "northeurope"
info:    Executing command vm image list-publishers
verbose: Getting virtual machine image publishers (Location: "northeurope")
data:    Publisher                                       Location   
data:    ----------------------------------------------  -----------
data:    4psa                                            northeurope
data:    4ward365                                        northeurope
data:    7isolutions                                     northeurope
data:    a10networks                                     northeurope
data:    abiquo                                          northeurope
...
data:    bssw                                            northeurope
data:    buddhalabs                                      northeurope
data:    bwappengine                                     northeurope
data:    Canonical                                       northeurope
data:    catechnologies                                  northeurope
data:    cds                                             northeurope
data:    certivox                                        northeurope
data:    checkpoint                                      northeurope
...
data:    gemalto-safenet                                 northeurope
data:    Gemalto.SafeNet.ProtectV                        northeurope
data:    GitHub                                          northeurope
data:    greensql                                        northeurope
data:    halobicloud                                     northeurope
...
data:    metavistech                                     northeurope
data:    mfiles                                          northeurope
data:    Microsoft                                       northeurope
data:    Microsoft.Azure.Applications                    northeurope
data:    Microsoft.Azure.Backup.Test                     northeurope
...
data:    your-shop-online                                northeurope
data:    zementis                                        northeurope
data:    zend                                            northeurope
info:    vm image list-publishers command OK
root@e584e195d664:/# azure vm image list "northeurope" "GitHub"
info:    Executing command vm image list
info:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "GitHub" Location:"northeurope")
data:    Publisher  Offer              Sku                OS     Version  Location     Urn                                             
data:    ---------  -----------------  -----------------  -----  -------  -----------  ------------------------------------------------
data:    GitHub     GitHub-Enterprise  GitHub-Enterprise  Linux  2.2.4    northeurope  GitHub:GitHub-Enterprise:GitHub-Enterprise:2.2.4
info:    vm image list command OK
root@e584e195d664:/# azure vm image list "northeurope" "Canonical"
info:    Executing command vm image list
info:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "Canonical" Location:"northeurope")
error:   getaddrinfo ENOTFOUND management.azure.com
info:    Error information has been recorded to /root/.azure/azure.err
error:   vm image list command failed

root@e584e195d664:/# cat /root/.azure/azure.err 
Tue Aug 11 2015 22:55:49 GMT+0000 (UTC):
{ [Error: getaddrinfo ENOTFOUND management.azure.com]
  stack: [Getter/Setter],
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'management.azure.com',
  __frame: 
   { name: 'getVMImageList__5',
     line: 102,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmImage._js',
     prev: 
      { name: 'listVMImages__27',
        line: 768,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 11,
        col: 31 },
     calls: 1,
     active: false,
     offset: 131,
     col: 34 },
  rawStack: [Getter] }
Error: getaddrinfo ENOTFOUND management.azure.com
  <<< async stack >>>
  at getVMImageList__5 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmImage._js:233:35)
  at listVMImages__27 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:779:32)
  at __27 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:603:18)
  <<< raw stack >>>
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

root@e584e195d664:/# ping management.azure.com
PING rpfd-prod-sn-01.cloudapp.net (157.55.80.115): 56 data bytes
^C--- rpfd-prod-sn-01.cloudapp.net ping statistics ---
9 packets transmitted, 0 packets received, 100% packet loss
<!---@tfsbridge:{"tfsId":4474062}-->

**Comment by huangpf** [comment]
Close duplicate. Please refer to: https://github.com/Azure/azure-xplat-cli/issues/2933
