### ISSUE TITLE
Unable to login with OrgID

### ISSUE THREAD

**Issue by andrewconnell** [Azure/azure-xplat-cli#2081]
I've been able to get to my resources by downloading a publishing profile, but to work with AzureAD I keep getting the TenantID is undefined error which I can see from `azure account list`.

However when I try to login using my OrgId (which works when I login via either web portal), I get an error about having to reauth because my credentials are expired. The details say the entry isn't fond in cache. Exact error:

```
✘ ac@Andrews-MBP  ~/dev  azure login -u me@andrewconnell.com
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Password: **********
+ Authenticating...
error:   Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.
info:    Error information has been recorded to /Users/ac/.azure/azure.err
error:   login command failed
```

> Contents of azure.err:
```
Fri Sep 04 2015 13:40:55 GMT-0400 (EDT):
{ [Error: Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.]
  __frame: 
   { name: '__1',
     line: 42,
     file: '/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/commands/login._js',
     prev: undefined,
     calls: 2,
     active: false,
     offset: 48,
     col: 43 },
  rawStack: [Getter] }
Error: Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/adalAuth.js:128:20
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:142:11
    at TokenRequest.<anonymous> (/Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:495:5)
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:139:20
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:353:7
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:227:9
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/adal-node/lib/cache-driver.js:167:5
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:172:7
    at TokenCache._.extend._loadEntries (/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:42:14)
    at TokenCache.find (/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:168:10)
```

I tried explicitly stating the TenantID as an argument but got the same error. I've tried to logout but that's throwing an error too...

```
 ✘ ac@Andrews-MBP  ~/dev  azure logout -u me@andrewconnell.com
info:    Executing command logout
error:   Cannot read property 'name' of undefined
info:    Error information has been recorded to /Users/ac/.azure/azure.err
```

> contents of azure.err:
```
Fri Sep 04 2015 13:45:42 GMT-0400 (EDT):
[TypeError: Cannot read property 'name' of undefined]
TypeError: Cannot read property 'name' of undefined
    at usernameMatches (/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/profile.js:139:54)
    at Array.filter (native)
    at Function._.filter._.select (/Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/underscore/underscore.js:172:65)
    at _.(anonymous function) [as filter] (/Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/underscore/underscore.js:1073:39)
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/profile.js:165:8
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:95:9
    at Object.async.eachSeries (/Users/ac/.npm-packages/lib/node_modules/azure-cli/node_modules/async/lib/async.js:124:20)
    at KeychainTokenStorage._.extend.removeEntries (/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/osx-token-storage.js:70:11)
    at /Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:91:26
    at TokenCache._.extend._loadEntries (/Users/ac/.npm-packages/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:42:14)
```

Is there any way to purge the cache? I know I've logged in with my OrgID in the past with no problem so not sure what's changed.

```
$ azure -v && node -v
0.9.8
v0.12.6
```

**Comment by yugangw-msft** [comment]
@andrewconnell, log-in to a web portal doesn't require an org-id. Would help if you double check whether the "me@andrewconnell.com" is a user in the default tenant of your subscriptions
At the same time, if it is an org-id, in the ongoing azure-cli release (plan to go public sometime next week) we have fixed several issues in the login command.
For now, please do 2 workaround
1. "Azure account clear".
2. In the "keychain access", delete the all entries with kind of "azure access token"
Hope this help

**Comment by andrewconnell** [comment]
Seems clearing the account fixed it as I can now login using the same OrgID
