### ISSUE TITLE
Fresh installation of latest version of Azure-CLI breaks

### ISSUE THREAD

**Issue by gkgupta** [Azure/azure-xplat-cli#2102]
I was doing setup on a new machine and installed latest azure-cli:
sudo npm install azure-cli -g

And it is giving error while executing:

```
azure storage blob download -a <STORAGE> -k <KEY> <STORAGE_CONTAINER> <BLOB_NAME>
info:    Executing command storage blob download
error:   Cannot read property 'substr' of null
info:    Error information has been recorded to /root/.azure/azure.err
error:   storage blob download command failed
```

**Comment by gkgupta** [comment]
Error details

```
Tue Sep 15 2015 05:44:01 GMT+0000 (UTC):
{ [TypeError: Cannot read property 'substr' of null] __frame: undefined, rawStack: [Getter] }
TypeError: Cannot read property 'substr' of null
    at Object.exports.stringStartsWith (/usr/lib/node_modules/azure-cli/lib/util/utilsCore.js:67:16)
    at Object.exports.isIP (/usr/lib/node_modules/azure-cli/lib/util/validation.js:38:17)
    at getStorageServiceEndpointSuffix (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:1139:18)
    at getFullConnectionString (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:1148:24)
    at adjustConnectionStringWithEnvironment (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:1196:10)
    at getStorageServiceSettings (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:1088:24)
    at StorageUtil.getBlobService (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:139:25)
    at Object.StorageUtil.getServiceClient (/usr/lib/node_modules/azure-cli/lib/util/storage.util._js:522:27)
    at getBlobServiceClient (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:67:37)
    at __$listAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:813:21)
```

**Comment by ChoOo7** [comment]
I have the same issue.
Do you have any workaround ?

**Comment by yugangw-msft** [comment]
@yaxia please investigate. #2103 is the same issue

**Comment by ChoOo7** [comment]
Tested with node 0.10.25 and 0.12.0
from a fresh 
git clone https://github.com/Azure/azure-xplat-cli.git

Still have the issue

**Comment by yaxia** [comment]
I am sorry that it's an issue in the code. Passing the connection string with the service endpoint (e.g. -c 'DefaultEndpointsProtocol=https;BlobEndpoint=https://<account_name>.blob.core.windows.net/;AccountName=<account_name>;AccountKey=<account_key>') or call "azure login" before storage commands can work around the issue.

**Comment by yugangw-msft** [comment]
fixed

**Comment by gkgupta** [comment]
This is still breaking when I do a fresh install via npm. And even when I do a fresh install of an older version like 0.9.7 or 0.9.8. My application uses this extensively and we have automated deployment setup which installs nodejs and azure-cli and invokes the same via shell scripts.
So can you please release this fix as well.

**Comment by devigned** [comment]
@gkgupta can you try with `npm install github:azure/azure-xplat-cli#a2de47095`? I don't think this fix has hit npm yet.

**Comment by gkgupta** [comment]
@devigned thanks a lot. This issue is breaking installs of previous version of azure-cli as well. Thus breaking our automate fresh installation scripts.
