### ISSUE TITLE
0.9.9: Cannot call method 'substr' of null

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#2103]
I installed 0.9.9 in Ubuntu 14.04.2 LTS. I always get an error 'Cannot call method 'substr' of null' when using 'azure storage blob' commands. 

command:
azure storage blob show --container CONTAINER-NAME -a STORAGE-ACCOUNT -k STORAGE-KEY

Error:
info:    Executing command storage blob show
error:   Cannot call method 'substr' of null
info:    Error information has been recorded to /home/MYACCOUNT/.azure/azure.err
error:   storage blob show command failed

.azure/azure.err:
Tue Sep 15 2015 07:34:48 GMT+0000 (UTC):
{ [TypeError: Cannot call method 'substr' of null]
  stack: [Getter/Setter],
  __frame:
   { name: 'showAzureBlob',
     line: 749,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 1,
     col: 15 },
  rawStack: [Getter] }
TypeError: Cannot call method 'substr' of null
  <<< async stack >>>
    at Object.exports.stringStartsWith (/usr/local/lib/node_modules/azure-cli/lib/util/utilsCore.js:67:17)
    at Object.exports.isIP (/usr/local/lib/node_modules/azure-cli/lib/util/validation.js:38:17)
    at getStorageServiceEndpointSuffix (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1139:18)
    at getFullConnectionString (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1148:24)
    at adjustConnectionStringWithEnvironment (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1196:10)
    at getStorageServiceSettings (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1088:24)
    at StorageUtil.getBlobService (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:139:25)
    at Object.StorageUtil.getServiceClient (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:522:27)
    at getBlobServiceClient (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:67:37)
    at getAzureBlobProperties (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:934:21)
  at showAzureBlob (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:750:16)
  <<< raw stack >>>
    at Object.exports.stringStartsWith (/usr/local/lib/node_modules/azure-cli/lib/util/utilsCore.js:67:17)
    at Object.exports.isIP (/usr/local/lib/node_modules/azure-cli/lib/util/validation.js:38:17)
    at getStorageServiceEndpointSuffix (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1139:18)
    at getFullConnectionString (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1148:24)
    at adjustConnectionStringWithEnvironment (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1196:10)
    at getStorageServiceSettings (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:1088:24)
    at StorageUtil.getBlobService (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:139:25)
    at Object.StorageUtil.getServiceClient (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util._js:522:27)
    at getBlobServiceClient (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:67:37)
    at __$getAzureBlobProperties (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.blob._js:934:21)

**Comment by yugangw-msft** [comment]
@yaxia , please investigate with #2102

**Comment by yaxia** [comment]
Please check the work around: https://github.com/Azure/azure-xplat-cli/issues/2102#issuecomment-140333586

**Comment by yugangw-msft** [comment]
fixed
