### ISSUE TITLE
ASM: Unable to delete certificate using 'azure service cert delete'

### ISSUE THREAD

**Issue by ronaldmendoza** [Azure/azure-xplat-cli#2136]
$ azure --version
0.9.9 (node: 0.12.7)

OS X 10.10.5

Unable to delete certificate from a specified cloud service. Running with or without '-q' results in error.

$ azure service cert delete -v -q -d [someCloudService] [someValidThumbprint]

info:    Executing command service cert delete
verbose: Getting cloud service certificates
verbose: Deleting certificates
error:   undefined is not a function
info:    Error information has been recorded to /Users/[deleted]/.azure/azure.err
verbose: TypeError: undefined is not a function
    at /usr/local/azure/lib/commands/asm/service.cert.js:160:59
    at /usr/local/azure/node_modules/async/lib/async.js:187:20
    at /usr/local/azure/node_modules/async/lib/async.js:239:13
    at _arrayEach (/usr/local/azure/node_modules/async/lib/async.js:91:13)
    at _each (/usr/local/azure/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/azure/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/usr/local/azure/node_modules/async/lib/async.js:215:22)
    at __$__3 (/usr/local/azure/lib/commands/asm/service.cert.js:159:36)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/asm/service.cert.js:156:132)
error:   service cert delete command failed

**Comment by ronaldmendoza** [comment]
Version 0.9.9

This also repro's in ASM for Linux:
silly:       ], type: 'undefined_method', message: "Object #<ServiceCertificateOperations> has no method 'delete'" }
info:    Error information has been recorded to /home/mfadmin/.azure/azure.err
verbose: TypeError: Object #<ServiceCertificateOperations> has no method 'delete'
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/service.cert._js:262:59
    at /usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:187:20
    at /usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:239:13
    at _arrayEach (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:91:13)
    at _each (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:215:22)
    at __$__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/service.cert._js:261:36)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/service.cert._js:260:21)

error:   service cert delete command failed

**Comment by mayurid** [comment]
@amarzavery : Can you take a look and follow up.

**Comment by amarzavery** [comment]
I was able to repro this and this will be fixed in the upcoming release

**Comment by DaveVoyles** [comment]
Was this ever resolved? I'm running into the same issue. 

https://www.dropbox.com/s/t1291q1uumaw33p/Screenshot%202018-01-12%2009.19.12.png?dl=0
