### ISSUE TITLE
ASM: azure vm endpoint create-multiple has issues

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2145]
Hi,

We have issues while creating multiple endpoints for VM using CLI 0.9.9

[samanoha@crystal test]$ azure vm endpoint create-multiple testvm1 41080:41080:tcp:::tcp:41080::::lbs-cms-41080:qa1-cms-ilb:

info:    Executing command vm endpoint create-multiple
+ Getting virtual machines                                                     
+ Reading network configuration                                                
+ Updating network configuration                                               
error:   InternalError : The server encountered an internal error. Please retry the request.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   vm endpoint create-multiple command failed

[samanoha@crystal test]$ cat /home/samanoha/.azure/azure.err
Mon Sep 28 2015 15:05:04 GMT+0300 (EEST):
{ [Error: InternalError : The server encountered an internal error. Please retry the request.]
  error: 
   { [Error: The server encountered an internal error. Please retry the request.]
     code: 'InternalError',
     message: 'The server encountered an internal error. Please retry the request.' } }
Error: InternalError : The server encountered an internal error. Please retry the request.
    at /usr/lib/node_modules/azure-cli/node_modules/azure-asm-compute/lib/computeManagementClient.js:26798:30
    at /usr/lib/node_modules/azure-cli/node_modules/azure-asm-compute/lib/computeManagementClient.js:285:14
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:353:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:330:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:283:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/redirectfilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:49:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)

If we ignore probe protocol and probe port, it works 

41080:41080:tcp::::::::lbs-cms-41080:qa1-cms-ilb:

**Comment by infosatheesh2020** [comment]
Sorry, this seems not CLI issue, turned out to be azure fabric issue
