### ISSUE TITLE
ARM: cannot resize VM

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2150]
Getting some internal error while resizing the VM. Please triage.

```
➜  ~  azure vm set ahmet-prem "vm" -z Standard_DS1
info:    Executing command vm set
+ Looking up the VM "vm"
+ Updating VM "vm"
error:   Required parameter 'bootDiagnostics.storageAccountName' is missing (null).
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   vm set command failed
```

verbose error:

```
verbose: Error: Required parameter 'bootDiagnostics.storageAccountName' is missing (null).
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by ahmetalpbalkan** [comment]
Error comes from 

    PUT https://management.azure.com/subscriptions/<subs-ID>/resourceGroups/ahmet-prem/providers/Microsoft.Compute/virtualMachines/vm?api-version=2015-06-15

call:

    HTTP 400 Bad Request
    "{\015\n  "error": {\015\n    "code": "InvalidParameter",\015\n    "target": "bootDiagnostics.storageAccountName",\015\n    "message": "Required parameter 'bootDiagnostics.storageAccountName' is missing (null)."\015\n  }\015\n}"

**Comment by huangpf** [comment]
I think now the ```vm set`` command will actually require the boot diagnostics parameters, which should be optional. I will try to get a fix by the next release. Thanks.

**Comment by ahmetalpbalkan** [comment]
Thanks for the update.

**Comment by sauryadas** [comment]
I verified this and it worked okay for me, resized  standard A! to Standard DS1
![image](https://cloud.githubusercontent.com/assets/15387759/11598041/58c8715e-9a74-11e5-9420-e76930858bb6.png)
@ahmetalpbalkan - Can you please confirm that this is fixed?

**Comment by ahmetalpbalkan** [comment]
@sauryadas I trust you. :-)
