### ISSUE TITLE
ARM:  unfriendly error message from `azure vm image list` in India regions

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2159]
```sh
$ azure vm image list -l 'South India' -p 'CoreOS' -v
info:    Executing command vm image list
info:    The parameters --offer and --sku if specified will be ignored
verbose: Getting virtual machine image offers (Publisher: "CoreOS" Location:"southindia")
error:   Host name resolution failed for 'Microsoft.Compute'; cannot fulfill the request.
info:    Error information has been recorded to /Users/alp/.azure/azure.err
verbose: Error: Host name resolution failed for 'Microsoft.Compute'; cannot fulfill the request.
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

verbose:

```
silly:   returnObject
silly:   {
silly:       statusCode: 502,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-failure-cause: 'service',
silly:           x-ms-request-id: 'b3c14f19-a1ec-42d9-962a-d54d06746693',
silly:           x-ms-correlation-request-id: 'b3c14f19-a1ec-42d9-962a-d54d06746693',
silly:           x-ms-routing-request-id: 'WESTUS:20150929T214619Z:b3c14f19-a1ec-42d9-962a-d54d06746693',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Tue, 29 Sep 2015 21:46:18 GMT',
silly:           connection: 'close',
silly:           content-length: '132'
silly:       },
silly:       body: "{"error":{"code":"InvalidGatewayHost","message":"Host name resolution failed for 'Microsoft.Compute'; cannot fulfill the request."}}"
silly:   }
```

**Comment by huangpf** [comment]
@ahmetalpbalkan 
Instead of throwing the exception from the service side, may I know what's the right error message in your opinion?

**Comment by ahmetalpbalkan** [comment]
@huangpf there's nothing friendlier we can show here I believe, I just wanted to report this call is failing.

**Comment by huangpf** [comment]
I can reproduce this on my end as well, but I think this is related to the resources that are available in the specific location. For example, ```South India``` is not listed in the ```Microsoft.Compute/locations/publishers``` list.

```
azure location list
```
```
Microsoft.Compute/locations/publishers
East US,East US 2,West US,Central US,South Central US,North Europe,West Europe,East Asia,Southeast Asia,Japan East,Japan West,North Central US,Australia East,Australia Southeast,Brazil South
```

**Comment by ahmetalpbalkan** [comment]
Ah may be CRP or PIR is not there yet?

**Comment by huangpf** [comment]
@ahmetalpbalkan I think so. Could you please help close this issue? Thanks.
