### ISSUE TITLE
[DEBIAN] Can't upload disk on Azure

### ISSUE THREAD

**Issue by moulip** [Azure/azure-xplat-cli#2168]
Hi,

I am no longer able to upload disks using azure-cli :+1I get this error on the command-line :+1: 
info:    Executing command vm disk upload
info:    VHD size : 70 GB
info:    Uploading 3604480.5 KB
error:   Object conectix�����������waWi2k��������0�X;E�A�E���s��>� has no method 'on'
info:    Error information has been recorded to /home/julien/.azure/azure.err

Here's the output of azure.err :+1: 
Fri Oct 02 2015 16:00:26 GMT+0200 (CEST):
[TypeError: Object conectix^@^@^@^B^@^A^@^@��������^]���wa^@^@^@^F^@^AWi2k^@^@^@^Q�^@^@^@^@^@^@^Q�^@^@^@��^P�^@^@^@^B���0�X;E�A�E���s��>�^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ has no method 'on']
TypeError: Object conectix^@^@^@^B^@^A^@^@��������^]���wa^@^@^@^F^@^AWi2k^@^@^@^Q�^@^@^@^@^@^@^Q�^@^@^@��^P�^@^@^@^B���0�X;E�A�E���s��>�^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ has no method 'on'
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:431:35
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:557:5
    at SharedKey.signRequest (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/signing/sharedkey.js:84:3)
    at BlobService.StorageServiceClient._buildRequestOptions (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:539:27)
    at operation (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:262:10)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:470:9
    at BlobService.filter (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:826:7)
    at BlobService.StorageServiceClient._performRequest (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:453:8)
    at BlobService.StorageServiceClient.performRequestOutputStream (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:193:8)
    at BlobService._createPages (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:4650:10)

I am using Azure-cli 0.9.9 on Debian Jessie with NodeJS ver. 0.10.29~dfsg-2 from Jessie official repo and npm 1.4.21+ds-2.

I have tried with other versions from SID for instance same results. I have also tried on Cent OS same results.
Can you please help me ?

**Comment by moulip** [comment]
I have tried with nodejs 0.12 and I get another error. Undefined is not a function

azure.err:
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:431:35
    at /usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:557:5
    at SharedKey.signRequest (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/signing/sharedkey.js:84:3)
    at BlobService.StorageServiceClient._buildRequestOptions (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:539:27)
    at operation (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:262:10)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:470:9
    at BlobService.filter (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:826:7)
    at BlobService.StorageServiceClient._performRequest (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:453:8)
    at BlobService.StorageServiceClient.performRequestOutputStream (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:193:8)
    at BlobService._createPages (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:4650:10)

**Comment by yugangw-msft** [comment]
@yaxia any ideas for the original error?
@moulip, did you get azure-cli "npm install"? If yes, could you please delete the "/home/julien/.streamline" and try again?

**Comment by moulip** [comment]
Yes I have installed azure-cli with npm install azure-cli -g.
Everything went fine. I have deleted .streamline, I get the same error.
undefined is not a function. Still with nodejs 0.12

**Comment by yugangw-msft** [comment]
@yaxia, could you please take a look the second issue as well?

**Comment by kgibson-ud** [comment]
Hi, I am running into this error as well, but I only experience it when uploading dynamic disks. Fixed VHDs work correctly for me. I know my VHDs are OK because they upload correctly if I use Azure Powershell.

I'm running Node v.0.12.7 on Windows 7 Professional 64-bit. azure-cli is v0.9.9, and I installed it with npm install.

I have also tried installing it using the standalone installer on another completely different Windows 7 machine, and still hit this issue.

I looked at the source code briefly. It seems that the problem happens when writing the vhd footer to convert it to fixed format. The stream object getting passed into storageserviceclient is expected to be able to handle events, but it can't.

**Comment by moulip** [comment]
Hi,

I think this is the issue ! I am using dynamic disks too. But it's still a bug since it is working under Powershell with the same vhd.

**Comment by colemickens** [comment]
Any updates?

**Comment by anuchandy** [comment]
@moulip @colemickens   you could use the utility below to upload VHDs while our storage team fixes this issue
https://github.com/Microsoft/azure-vhd-utils-for-go

**Comment by colemickens** [comment]
@anuchandy That's exactly what I plan to do for now. Thanks for letting me know about that tool! I'll report back on how successful I am.
