### ISSUE TITLE
storage blob upload gets MD5 Mismatch w/ node 4.0.0.

### ISSUE THREAD

**Issue by BillAtPros** [Azure/azure-xplat-cli#2175]
Azure-Storage has fixed this error in 0.6.0. Need to update dependency for xplat-cli

**Comment by yugangw-msft** [comment]
we will get azure-cli work with node 4.* after the nodejs/node#2996 get resolved, which is impacting all commands with keyboard interaction such as prompt for keyword, or missed parameter value.

**Comment by mayurid** [comment]
@BillAtPros : Are you still seeing this? We believe this is fixed but would like it if you can confirm

**Comment by MrBRUE** [comment]
I do have this issue, when I try something like this:
azure storage blob upload 'rubyonflower.jpg' 'somecontainer' 'super.jpg' -c 'DefaultEndpointsProtocol=https;BlobEndpoint=https://laberlaber.blob.core.windows.net/;AccountName=laberlaber;AccountKey=<key>' I get, with Azure CLI version 0.9.9:
error:   The MD5 value specified in the request did not match with the MD5 value calculated by the server.

The error log says:
 at Object.StorageServiceClient._processResponse (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:611:50)
    at Request.processResponseCallback [as _callback] (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:281:37)
    at Request.self.callback (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/azure-cli/node_modules/azure-storage/node_modules/request/request.js:354:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/azure-cli/node_modules/azure-storage/node_modules/request/request.js:1207:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/azure-cli/node_modules/azure-storage/node_modules/request/request.js:1153:12)

What's the matter here?!

**Comment by MrBRUE** [comment]
@mayurid The issue still pertains, do you have any pointers for me what to do?

**Comment by amarzavery** [comment]
@MrBRUE - Can you please install the latest version of azure-cli (0.10.0) and make sure you have 4.x version of node.js installed on your system? Do let us know if the issue still persists after that.

**Comment by MrBRUE** [comment]
Finally it works @amarzavery ! Thanks, the CLI upgrade helped.
