### ISSUE TITLE
azure group template download fails with Object #<Object> has no method 'trim'

### ISSUE THREAD

**Issue by infidel** [Azure/azure-xplat-cli#2196]
On Ubuntu 14.04:

```
$ azure group template download Microsoft.WindowsServer2008R2SP1.0.2.111-preview -v
info:    Executing command group template download
error:   Object #<Object> has no method 'trim'
info:    Error information has been recorded to /home/luked/.azure/azure.err
verbose: TypeError: Object #<Object> has no method 'trim'
  <<< async stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:925:13
    at next (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:827:24)
    at AzureCli.Command.prompt (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:834:5)
    at AzureCli.Command.confirm (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:924:8)
    at Interactor.__.extend.confirm (/usr/local/lib/node_modules/azure-cli/lib/util/interaction._js:153:14)
    at Object.normalizeDownloadFileName (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:215:5)
    at __3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.template._js:112:25)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:925:13
    at next (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:827:24)
    at AzureCli.Command.prompt (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:834:5)
    at AzureCli.Command.confirm (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:924:8)
    at Interactor.__.extend.confirm (/usr/local/lib/node_modules/azure-cli/lib/util/interaction._js:153:14)
    at Object.normalizeDownloadFileName (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:215:5)
    at __$__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.template._js:112:25)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.template._js:106:12)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/cli.js:223:12)

```

I just upgraded from 0.9.9 due to #2169.

**Comment by yugangw-msft** [comment]
@infidel,  you will need to specify the download folder, it is required per service api change 
```sh
azure group template download Microsoft.WindowsServer2008R2SP1.0.2.111-preview /home/luked/temp
```

**Comment by infidel** [comment]
OK, I just tried that but I received the same error about "trim". With "group template show" I can see the URL and I can download it manually as a work-around.

**Comment by yugangw-msft** [comment]
@infidel  could you please remove the "/home/luked/.streamline" and try again?
thanks!

**Comment by infidel** [comment]
Thanks, that works now.

**Comment by yugangw-msft** [comment]
@infidel 
I have filed the issue on the streamline package. This has happened on several users
https://github.com/Sage/streamlinejs/issues/290

**Comment by yugangw-msft** [comment]
We have fixed the issue by no longer publishing streamline files to npm. Please try out the latest azure-cli@0.9.11
