### ISSUE TITLE
error:   Credentials have expired, please reauthenticate.

### ISSUE THREAD

**Issue by drunkwolfs** [Azure/azure-xplat-cli#2203]
I was working and after a while has appeared an error:
"Credentials have expired, please reauthenticate
Detailed error message from ADAL is as follows: Error: Entry not found in cache."

Then I re-made authentication, but it did not help:
```
PS C:\> azure login
info:    Executing command login
/info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code C5****3TR to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters.
/info:    Added subscription BizSpark
info:    Setting subscription "BizSpark" as default
+
info:    login command OK
PS C:\> azure vm create ******* -o vmdepot-56718-9-16 -l "North Europe" user ****** --ssh
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up community image
+ Looking up cloud service
error:   Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.
info:    Error information has been recorded to C:\Users\***\.azure\azure.err
error:   vm create command failed
```

I used google.com, and then do:

```
PS C:\> $env:AZURE_ADAL_LOGGING_ENABLED = 1
PS C:\> azure vm create ******* -o vmdepot-56718-9-16 -l "North Europe" user ****** --ssh -z 'Standard_D2'
info:    Executing command vm create
+ Looking up community image
/ Looking up cloud serviceinfo:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-01a365****** - Authority: VERBO
SE: Performing instance discovery: https://login.microsoftonline.com/f661b434-0028-4e80-a307-ec4233******
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - Authority: VERBOSE: Performing static inst
ance discovery
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - Authority: VERBOSE: Authority validated vi
a static instance discovery.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - TokenRequest: INFO: Getting token from cac
he with refresh if necessary.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - CacheDriver: VERBOSE: finding with query:{
"clientId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","userId":"drunkwolfs1@gmail.com"}
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - CacheDriver: VERBOSE: Looking for potentia
l cache entries:
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - CacheDriver: VERBOSE: {"_clientId":"04b077
95-8ddb-461a-bbee-02f9e1bf7b46","userId":"drunkwolfs1@gmail.com"}
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - CacheDriver: VERBOSE: Found 9 potential en
tries.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-******3e661d - CacheDriver: ERROR: More than one token ma
tches the criteria.  The result is ambiguous.
Stack:
Error: More than one token matches the criteria.  The result is ambiguous.
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:223:28
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:163:5
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:178:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:
149:7)
    at Stream.emit (events.js:129:20)
    at drain (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:34:23)
    at Stream.stream.queue.stream.push (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:45
:5)
    at Stream.end (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:15:35)
error:   Error: More than one token matches the criteria.  The result is ambiguous.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-01a365****** - TokenRequest: WARNING: Attempt to look for
 token in cache resulted in Error: Error: More than one token matches the criteria.  The result is ambiguous.
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:223:28
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:163:5
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:178:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:
149:7)
    at Stream.emit (events.js:129:20)
    at drain (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:34:23)
    at Stream.stream.queue.stream.push (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:45
:5)
    at Stream.end (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\through\index.js:15:35)
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-01a365****** - TokenRequest: VERBOSE: No appropriate cach
ed token found.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-01a365****** - TokenRequest: ERROR: Entry not found in ca
che.
Stack:
Error: Entry not found in cache.
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at TokenRequest.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-reques
t.js:515:40)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-request.js:147:20
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:354:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:223:9
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:163:5
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:178:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:
149:7)
    at Stream.emit (events.js:129:20)
error:   Error: Entry not found in cache.
info:    Sat, 17 Oct 2015 19:39:13 GMT:b9765d34-485a-4c9a-8f92-01a365****** - TokenRequest: VERBOSE: getTokenFunc return
ed with err
+
error:   Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.
info:    Error information has been recorded to C:\Users\******\.azure\azure.err
error:   vm create command failed
```

"azure login" does not work:

```
PS C:\> azure login
info:    Executing command login
- Authenticating...info:    Sat, 17 Oct 2015 19:45:55 GMT:efd59f84-fd9a-40fb-9745-62d1367366a4 - Authority: VERBOSE: Per
forming instance discovery: https://login.microsoftonline.com/common
info:    Sat, 17 Oct 2015 19:45:55 GMT:efd59f84-fd9a-40fb-9745-62d1367366a4 - Authority: VERBOSE: Performing static inst
ance discovery
info:    Sat, 17 Oct 2015 19:45:55 GMT:efd59f84-fd9a-40fb-9745-62d1367366a4 - Authority: VERBOSE: Authority validated vi
a static instance discovery.
info:    Sat, 17 Oct 2015 19:45:55 GMT:efd59f84-fd9a-40fb-9745-62d1367366a4 - DeviceCodeRequest: INFO: Getting user code
 info.
/info:    Sat, 17 Oct 2015 19:45:56 GMT:efd59f84-fd9a-40fb-9745-62d1367366a4 - OAuth2Client: INFO: Get Device Code Serve
r returned this correlationId: efd59f84-fd9a-40fb-9745-62d1367366a4
info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code CDJMUVYLL to authentic
ate. If you're signing in as an Azure AD application, use the --username and --password parameters.
info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - Authority: VERBOSE: Performing instance di
scovery: https://login.microsoftonline.com/common
info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - Authority: VERBOSE: Performing static inst
ance discovery
info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - Authority: VERBOSE: Authority validated vi
a static instance discovery.
info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - TokenRequest: INFO: Getting a token via de
vice code
\info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - OAuth2Client: INFO: Get TokenServer retur
ned this correlationId: 3a501c83-835d-4156-a89a-d9eb6fb8cec7
info:    Sat, 17 Oct 2015 19:45:56 GMT:3a501c83-835d-4156-a89a-d9eb6fb8cec7 - OAuth2Client: ERROR: Get Token request ret
urned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending en
d-user authorization.\r\nTrace ID: 07327a78-38cb-4a99-832d-960a8edf730c\r\nCorrelation ID: 3a501c83-835d-4156-a89a-d9eb6
fb8cec7\r\nTimestamp: 2015-10-17 20:45:57Z","error_codes":[70016],"timestamp":"2015-10-17 20:45:57Z","trace_id":"07327a7
8-38cb-4a99-832d-960a8edf730c","correlation_id":"3a501c83-835d-4156-a89a-d9eb6fb8cec7"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_descripti
on":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 07327a78-38cb-4a99-832d-960a8edf730c\r\nCorrelation ID: 3
a501c83-835d-4156-a89a-d9eb6fb8cec7\r\nTimestamp: 2015-10-17 20:45:57Z","error_codes":[70016],"timestamp":"2015-10-17 20
:45:57Z","trace_id":"07327a78-38cb-4a99-832d-960a8edf730c","correlation_id":"3a501c83-835d-4156-a89a-d9eb6fb8cec7"}
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:133:25)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1187
:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
error:   Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_
description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 07327a78-38cb-4a99-832d-960a8edf730c\r\nCorrelat
ion ID: 3a501c83-835d-4156-a89a-d9eb6fb8cec7\r\nTimestamp: 2015-10-17 20:45:57Z","error_codes":[70016],"timestamp":"2015
-10-17 20:45:57Z","trace_id":"07327a78-38cb-4a99-832d-960a8edf730c","correlation_id":"3a501c83-835d-4156-a89a-d9eb6fb8ce
c7"}
```

PLEASE HELP ME

**Comment by yugangw-msft** [comment]
@drunkwolfs,  please run "azure account clear /q" and then run "azure login". The windows storage persistence code might have bug.

**Comment by drunkwolfs** [comment]
how to get <your user id> list?
Thanks for the help.
I have already has configured a virtual machine with the help of Azure web-panel.

**Comment by yugangw-msft** [comment]
@drunkwolfs , assume you are asking about how to get account list? that is "azure account list"

**Comment by yugangw-msft** [comment]
@drunkwolfs, i am closing it as there is nothing actionable and no more responses

**Comment by nydick** [comment]
I've seen this problem too.   It didn't get better until I did:
    azure logout me@mydomain.onmicrosoft.com
    azure account clear -q
    azure login me@mydomain.onmicrosoft.com
    azure account set 'Name of My Account'
    azure config mode arm

**Comment by jcastiblanco** [comment]
@nydick @yugangw-msft  I have the same problem from yesterday.  I was working with Azure CLI v2.8  After a few minutes working without problem, i received a message, that I need to relogin.   Since then, It could be imposible to me login though azurecli.  
this is the error message:
error: We don't have a valid access token. Please run "azure login" again. info: Error information has been recorded to C:\Users\julia.azure\azure.err error: login command failed

the errordetail  file this information:
2015-12-09T14:25:39.477Z - info: Executing command login 2015-12-09T14:25:40.278Z - info: To sign in, use a web browser to open the page aka.ms/devicelogin. Enter the code FYEBRSSSW to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters. 2015-12-09T14:25:40.278Z - verbose: code response from AAD is :{"userCode":"FYEBRSSSW","deviceCode":"FAAABAAEAiL9Kn2Z27UubvWFPbm0gLSP06OmChH0nnUbKKbL9_GLsujCsreUiKWZtv3DBNS6o5dK7vblnGRAk_b_3oO64FJ9f6Dd306_5P_ZlMUwIPCD-a02NydqTyYXXXXXXX","verificationUrl":"aka.ms/devicelogin","expiresIn":900,"interval":5,"message":"To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code FYEBRSSSW to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters."} 2015-12-09T14:36:25.449Z - error: We don't have a valid access token. Please run "azure login" again. 2015-12-09T14:36:25.451Z - silly: { 2015-12-09T14:36:25.451Z - silly: stack: "Error: We don't have a valid access token. Please run "azure login" again.\n at _polishError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\adalAuthForUser.js:64:10)\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\adalAuthForUser.js:48:25\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:96:9\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:52:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:272:32\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:44:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:169:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:697:13\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:52:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:272:32", 2015-12-09T14:36:25.452Z - silly: message: "We don't have a valid access token. Please run "azure login" again.", 2015-12-09T14:36:25.452Z - silly: __frame: { 2015-12-09T14:36:25.452Z - silly: name: '__1', 2015-12-09T14:36:25.452Z - silly: line: 47, 2015-12-09T14:36:25.452Z - silly: file: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js', 2015-12-09T14:36:25.452Z - silly: prev: undefined, 2015-12-09T14:36:25.452Z - silly: calls: 0, 2015-12-09T14:36:25.452Z - silly: active: false, 2015-12-09T14:36:25.452Z - silly: offset: 53, 2015-12-09T14:36:25.452Z - silly: col: 27 2015-12-09T14:36:25.452Z - silly: }, 2015-12-09T14:36:25.452Z - silly: rawStack: " token. Please run "azure login" again.\n at _polishError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\adalAuthForUser.js:64:10)\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\adalAuthForUser.js:48:25\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:96:9\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:52:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:272:32\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:44:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:169:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:697:13\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:52:16\n at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\async\lib\async.js:272:32" 2015-12-09T14:36:25.452Z - silly: } 2015-12-09T14:36:25.458Z - info: Error information has been recorded to C:\Users\julia.azure\azure.err

**Comment by andreasgrimm** [comment]
with `azure-cli` verion `0.10.8` for me only this worked:

```shell
azure login -u "<my email address>"
```

**Comment by amarzavery** [comment]
@andreasgrimm -  try cleaning the token cache. 
azure account clear -q
And then login again.
For interactive login just execute: azure login.
Use -u only for organizational user accounts that do not have 2FA enabled.
