### ISSUE TITLE
The provided account key undefined is not a valid base64 string.

### ISSUE THREAD

**Issue by petemill** [Azure/azure-xplat-cli#2286]
When providing a valid storage connectionstring, or storage account name and key pair via environment variables, azure-cli fails reporting the key as not valid. Though, it seems the validation function is always passed in `undefined` rather than the key.

Reproducable steps:

```
> npm install -g azure-cli

> azure login
# Successful login

> azure storage account list
# Successfully outputs storage accounts

> azure storage connectionstring show mystorage
# Successfully shows connection string

> export AZURE_STORAGE_CONNECTION_STRING=myconnectionstring==
> azure storage metrics show
info:    Executing command storage metrics show
error:   The provided account key undefined is not a valid base64 string.
info:    Error information has been recorded to /home/myuser/.azure/azure.err
error:   storage metrics show command failed
```

I have tried multiple versions of node and even used the azure-cli docker image to discount environment differences. Also set the AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY environment variables instead of connection string. Exact same result.

Detailed error from azure.err:
```
{ [Error: The provided account key undefined is not a valid base64 string.] __frame: undefined, rawStack: [Getter] }
Error: The provided account key undefined is not a valid base64 string.
    at exports.isBase64Encoded (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:146:11)
    at Array.<anonymous> (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/servicesettings.js:137:25)
    at Object.exports.matchedSpecification (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/servicesettings.js:250:54)
    at Function.StorageServiceSettings.createFromSettings (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageservicesettings.js:196:34)
    at Function.StorageServiceSettings.createFromConnectionString (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageservicesettings.js:114:35)
    at StorageServiceClient.getStorageSettings (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:753:53)
    at getStorageServiceSettings (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/lib/util/storage.util.js:1238:10)
    at StorageUtil.getBlobService (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/lib/util/storage.util.js:256:25)
    at Object.StorageUtil.getServiceClient (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/lib/util/storage.util.js:692:23)
    at getServiceClient (/home/finesseuser/.nvm/versions/node/v0.12.4/lib/node_modules/azure-cli/lib/commands/storage/storage.service.js:472:61)
```

**Comment by amarzavery** [comment]
@yaxia - Can you please help validate this issue?

**Comment by tantommy** [comment]
I've also just run into the same issue following the same steps.

**Comment by petemill** [comment]
Thanks @tantommy

**Comment by yaxia** [comment]
@amarzavery It is resolved, Please close. Thanks.
