### ISSUE TITLE
[AzureChinaCloud] Fail to login

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2357]
```
C:\Users\binxi>azure login -e AzureChinaCloud
info:    Executing command login
+ Authenticating...
error:   wireResponse is missing expires_in
info:    Error information has been recorded to C:\Users\binxi\.azure\azure.err
error:   login command failed
```

.azure\azure.err:
```
Fri Dec 04 2015 16:44:23 GMT+0800 (China Standard Time):
{ [Error: wireResponse is missing expires_in]
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 47,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 53,
     col: 27 },
  rawStack: [Getter] }
Error: wireResponse is missing expires_in
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:100:28)
  <<< raw stack >>>
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at OAuth2Client._validateDeviceCodeResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:319:23)
    at OAuth2Client._handleGetDeviceCodeResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:392:33)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:521:16
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:137:5)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1187:12)
```

**Comment by ahmetalpbalkan** [comment]
+1. it appears like the new device login flow has broken China login.

**Comment by yugangw-msft** [comment]
I have contacted AAD team to clarify whether the chinacloud has the device flow supports. 2 months ago I asked and told it was not deplyed yet, though planned,

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft in any case we should not break? :)

**Comment by yugangw-msft** [comment]
The device flow never works. I will post back when it is full deployed and close this issue. For now always provider "-u username" to the login command. Of course if your account is 2fa enabled, you are out of luck

**Comment by bingosummer** [comment]
Closing it since the device login flow works now.
And please make sure you use node (4.x).
https://github.com/Azure/azure-xplat-cli/issues/2725
