### ISSUE TITLE
Validation Error Message For Invalid Resource Name

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-xplat-cli#2381]
I ran azure group template validate (CLI version 0.9.11), and I get the error message below saying that I've named a resource incorrectly, but it does not specify which resource is named incorrectly. The error should indicate which resource is incorrectly named, ideally with the specific reason why it is named in correctly (e.g. 'there is a $ in the name, which is not supported; the resource name can contain only...')

Tue Dec 15 2015 03:28:40 GMT+0000 (UTC):
{ [Error: The resource name can contain only letters, numbers, and hyphens. The first and last character in the field must be a letter or a number.]
  stack: [Getter/Setter],
  code: 'InvalidResourceName',
  statusCode: 400,
  requestId: 'c87d284b-4c83-412a-b4d5-eb4d522eabcc',
  __frame:
   { name: '__1',
     line: 104,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
     prev:
      { name: 'exports_validateTemplate__2',
        line: 97,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 6,
        col: 33 },
     calls: 0,
     active: false,
     offset: 1,
     col: 32 },
  rawStack: [Getter] }
Error: The resource name can contain only letters, numbers, and hyphens. The first and last character in the field must be a letter or a number.
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:105:33)
  at exports_validateTemplate__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:103:34)
  at __4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.template.js:165:18)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

**Comment by yugangw-msft** [comment]
@vivsriaus , please comment

**Comment by remkoboschker** [comment]
Hi, 
I just closed #2435 dealing with a hyphen in a resource group name. I guess the same regex is causing your issue as it does not match for underscores in your `name: 'exports_validateTemplate__2',`
