### ISSUE TITLE
Moving Storages and VMs between ResourceGroups is not possible and the error message is not clear/helpful

### ISSUE THREAD

**Issue by yosuah** [Azure/azure-xplat-cli#2428]
Hello,

I was trying to use the move functionality to move Storage accounts between resource groups, but this failed. This very recent document suggests that moving is currently not possible for essential things like Storage and VMs: https://azure.microsoft.com/en-us/documentation/articles/resource-manager-supported-services/

Currently if you try to move a resource like this, the error message will simply state that "No HTTP resource was found that matches the request URI", which is not very helpful for a beginner - it is not clear whether the user made a mistake, or if this is something that could be corrected. A simple sentence like "Moving this resource is currently not supported" would make it easier for the users.

Thanks,
Adam

```
azure resource move -i "/subscriptions/[subscription_id]/resourceGroups/[old_rg]/providers/Microsoft.Storage/storageAccounts/[storage_id]" -d "[new_rg]"
info:    Executing command resource move
Move selected resources in [old_rg] to [new_rg]? [y/n] y
/error:   {"error":{"code":"HttpResourceNotFound","message":"No HTTP resource was found that matches the request URI 'https://globalxls.storage.azure.com:443/subscriptions/[subscription_id]/resourceGroups/[old_rg]/moveResources?api-version=2015-05-01-preview'."}}
+
error:   Resources '/subscriptions/[subscription_id]/resourceGroups/[old_rg]/providers/Microsoft.Storage/storageAccounts/[storage_id]' could not be moved. The tracking Id is 'cc01d247-1d27-45ba-a2ce-75172d376a96'
info:    Error information has been recorded to /Users/xx/.azure/azure.err
error:   resource move command failed
```

```
cat /Users/xx/.azure/azure.err
Wed Jan 13 2016 12:11:16 GMT+0100 (CET):
{ [Error: Resources '/subscriptions/[subscription_id]/resourceGroups/[old_rg]/providers/Microsoft.Storage/storageAccounts/[storage_id]' could not be moved. The tracking Id is 'cc01d247-1d27-45ba-a2ce-75172d376a96']
  stack: [Getter/Setter],
  code: 'ResourceMoveFailed',
  target: null,
  details: 
   [ { Code: null,
       Target: 'Microsoft.Storage/storageAccounts',
       Message: '{"error":{"code":"HttpResourceNotFound","message":"No HTTP resource was found that matches the request URI \'https://globalxls.storage.azure.com:443/subscriptions/[subscription_id]/resourceGroups/[old_rg]/moveResources?api-version=2015-05-01-preview\'."}}',
       Details: null } ],
  statusCode: 409,
  requestId: '83233c23-4162-4dcf-97eb-f53c20fcb6b9',
  __frame: 
   { name: '__7',
     line: 316,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 27,
     col: 25 },
  rawStack: [Getter] }
Error: Resources '/subscriptions/[subscription_id]/resourceGroups/synetiqjupyterx/providers/Microsoft.Storage/storageAccounts/[storage_id]' could not be moved. The tracking Id is 'cc01d247-1d27-45ba-a2ce-75172d376a96'
  <<< async stack >>>
  at __7 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:343:26)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
```

**Comment by yugangw-msft** [comment]
@vivsriaus, please comment

**Comment by ravbhatnagar** [comment]
This is fixed now. Moving VMs and Storage is possible. PLease let us know if you run into issues. Closing this.
