### ISSUE TITLE
Login through .publishsettings breaks CLI commands

### ISSUE THREAD

**Issue by damolina-ms** [Azure/azure-xplat-cli#2530]
Probably same root cause as #2529 

Run: 
1. azure account download 
2.Save file (example: x.publishsettings)
3.Run: azure account import <.publishsetting file> 
4.Verify account works (example: azure account show)
5. Run: azure group create <name> <location>

**Bug**
Command fails with : _Authentication failed. The 'Authorization' header is missing._

Stack Info
    at Function.ServiceClient._normalizeError (...\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at ...\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (...\npm\node_modules\azure-cli\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (...\npm\node_modules\azure-cli\node_modules\azure-common\node_modules\request\request.js:199:22)

**Comment by yugangw-msft** [comment]
@damolina-ms, "group create" is only valid under arm mode which requires AAD token, and this can't be supplied by "importing publish settings" which only works under asm, aka rdfe.
I will take a look to see whether i can make the error better.

**Comment by yugangw-msft** [comment]
fix was in
