### ISSUE TITLE
ASM: Application gateway creation does not accept multiple subnets

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2537]
"azure network application-gateway create" option help specifies to use multiple subnets:
-t, --subnet-names <subnet-names>      comma separated list of subnet names exists in the virtual network identified by --vnet-name

But when we try to use multiple subnets in command, it throws error

azure network application-gateway create --name testgw --vnet-name TestNet --subnet-names "Subnet-1,Subnet-2" --gateway-size "Small" 
info:    Executing command network application-gateway create
+ Looking up an Application Gateway "testgw"                                   
warn:    --instance-count parameter is not specified, using default - 1
+ Creating an Application Gateway "testgw" for virtual network "TestNet"    
error:   Only one subnet can be provided in the subnet list
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network application-gateway create command failed

Error:

cat /home/samanoha/.azure/azure.err
2016-02-15T09:40:54.393Z:
{ [Error: Only one subnet can be provided in the subnet list]
  stack: [Getter/Setter],
  code: 'BadRequest',
  statusCode: 400,
  requestId: '74ef19f232b8718597f62634cc6afa4b',
  __frame: 
   { name: 'create__1',
     line: 33,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/appGateway._js',
     prev: 
      { name: '__62',
        line: 1008,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
        prev: undefined,
        calls: 4,
        active: false,
        offset: 7,
        col: 17 },
     calls: 1,
     active: false,
     offset: 13,
     col: 55 },
  rawStack: [Getter] }
Error: Only one subnet can be provided in the subnet list
  <<< async stack >>>
  at create__1 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/appGateway._js:46:56)
  at __62 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:1015:18)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

**Comment by romangromov** [comment]
@infosatheesh2020 thanks for flagging, this is Azure side issue, not CLI itself. I will start e-mail thread about this and let you know

**Comment by infosatheesh2020** [comment]
@romangromov thanks!

**Comment by romangromov** [comment]
@infosatheesh2020 here is answer from Azure team:
```
You can have only one subnet by design.
- Amit Srivastava 
```

I will update option description accordingly, sorry for inconvenience

**Comment by infosatheesh2020** [comment]
@romangromov Thanks for clarification!
