### ISSUE TITLE
vm disk list (arm) err in 0.9.15

### ISSUE THREAD

**Issue by Trepliev** [Azure/azure-xplat-cli#2542]
~ $ azure vm disk list cm-smtp-3 cm-smtp-3
info:    Executing command vm disk list
error:   msRest.addSerializationMixin is not a function
info:    Error information has been recorded to /Users/trepliev/.azure/azure.err
error:   vm disk list command failed

azure.err:

{ [TypeError: msRest.addSerializationMixin is not a function]
  stack: [Getter/Setter],
  __frame:
   { name: '__25',
     line: 518,
     file: '/usr/local/azure/lib/commands/arm/vm/vm.js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 5,
     col: 17 },
  rawStack: [Getter] }
TypeError: msRest.addSerializationMixin is not a function
  <<< async stack >>>
    at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
    at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
    at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
    at VMClient.__.extend._getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
    at listDataDisks__23 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:926:31)
  at __25 (/usr/local/azure/lib/commands/arm/vm/vm.js:523:18)
  <<< raw stack >>>
    at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
    at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
    at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
    at VMClient.__.extend._getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
    at __$listDataDisks__23 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:926:31)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at VMClient.listDataDisks__23 [as listDataDisks] (/usr/local/azure/lib/commands/arm/vm/vmClient.js:924:239)
    at ___ (/usr/local/azure/lib/commands/arm/vm/vm.js:523:27)
    at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:99:14

**Comment by amarzavery** [comment]
Looks like you did brew install. The latest version of cli has not been updated for brew install.
Can you please uninstall (npm uninstall azure-cli -g)
Clear the cache (npm cache clear -g)
And install again (npm install azure-cli -g)
Note: if you previously installed via Mac installer then execute (sudo azure-uninstall)

Thanks,
Amar Zavery

On Feb 16, 2016, at 1:56 AM, "Trepliev" <notifications@github.com<mailto:notifications@github.com>> wrote:


~ $ azure vm disk list cm-smtp-3 cm-smtp-3
info: Executing command vm disk list
error: msRest.addSerializationMixin is not a function
info: Error information has been recorded to /Users/trepliev/.azure/azure.err
error: vm disk list command failed

azure.err:

{ [TypeError: msRest.addSerializationMixin is not a function]
stack: [Getter/Setter],
frame:
{ name: '__25',
line: 518,
file: '/usr/local/azure/lib/commands/arm/vm/vm.js',
prev: undefined,
calls: 3,
active: false,
offset: 5,
col: 17 },
rawStack: [Getter] }
TypeError: msRest.addSerializationMixin is not a function
<<< async stack >>>
at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
at VMClient..extend.getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
at listDataDisks__23 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:926:31)
at __25 (/usr/local/azure/lib/commands/arm/vm/vm.js:523:18)
<<< raw stack >>>
at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
at VMClient._.extend.getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
at _$listDataDisks__23 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:926:31)
at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
at VMClient.listDataDisks__23 as listDataDisks</usr/local/azure/lib/commands/arm/vm/vmClient.js:924:239>
at ___ (/usr/local/azure/lib/commands/arm/vm/vm.js:523:27)
at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
at /usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:99:14

-

**Comment by Trepliev** [comment]
Hello Amar! Thank you for response. I use always dmg installation file. After azure-uninstall and new install it works just fine. Thank you!

Jan
