### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined when running azure site repository sync

### ISSUE THREAD

**Issue by pjfsilva** [Azure/azure-xplat-cli#2555]
Just installed azure cli on my win7 64bit machine, did 'azure login' and now I'm trying to run:

`azure site repository sync <my app name>`

that results in an azure.err file like this:

```
2016-02-18T18:17:28.945Z:
{ [TypeError: Cannot read property 'key' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'ensureRepositoryUri__17',
     line: 810,
     file: 'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\websites\\websitesclient._js',
     prev: 
      { name: '__3',
        line: 92,
        file: 'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\site.repository._js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 12,
        col: 13 },
     calls: 1,
     active: true,
     offset: 3,
     col: 24 },
  rawStack: [Getter] }
TypeError: Cannot read property 'key' of undefined
  <<< async stack >>>
    at createService (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:404:49)
    at Object.exports.createWebsiteManagementService (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:417:10)
    at WebsitesClient.__.extend.syncRepository (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:507:28)
    at AzureCli.site.doRepositorySync (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site._js:1159:26)
    at __3 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:118:25)
  at ensureRepositoryUri__17 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:813:25)
  at __3 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:104:14)
  <<< raw stack >>>
    at createService (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:404:49)
    at Object.exports.createWebsiteManagementService (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:417:10)
    at WebsitesClient.__.extend.syncRepository (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:507:28)
    at AzureCli.site.doRepositorySync (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site._js:1159:26)
    at __$__3 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:118:25)
    at ___ (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:125:11)
    at ___ (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at __$ensureRepositoryUri__17 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1325:18)
    at __$ensureRepositoryUri__17 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1316:13)
    at ___ (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\websites\websitesclient._js:1319:11)


```

node v4.3.1
azure cli 0.9.15

Any idea how to debug this further or what the problem can be?

**Comment by yugangw-msft** [comment]
what version azure-cli you are using? you can run "azure -v"

**Comment by pjfsilva** [comment]
Sorry, updated to include that. 0.9.15

**Comment by yugangw-msft** [comment]
Did you login using certificate? It appears "site repository" client expects you log in using a certificate. For you reference the code is [here] (https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/utils.js#L420)

**Comment by pjfsilva** [comment]
That solves it. Now I get a problem using 'repository branch', but that's another problem, thanks.
