### ISSUE TITLE
Error running 'azure site repository branch': The request is invalid

### ISSUE THREAD

**Issue by pjfsilva** [Azure/azure-xplat-cli#2556]
I'm trying to run this command:
`azure site repository branch development <my app name>`

My website is already configured with github and using continuous deployment from the master branch. Now I want to change it's branch. When I run that command I get the following error:

```
2016-02-18T22:55:11.563Z:
{ [Error: The request is invalid.]
  stack: [Getter/Setter],
  message: 'The request is invalid.',
  messagedetail: 'The parameters dictionary contains an invalid entry for parameter \'newSettings\' for method \'System.Net.Http.HttpResponseMessage Set(Newtonsoft.Json.Linq.JObject)\' in \'Kudu.Services.Settings.SettingsController\'. The dictionary contains a value of type \'Newtonsoft.Json.Linq.JValue\', but the parameter requires a value of type \'Newtonsoft.Json.Linq.JObject\'.',
  statusCode: 400,
  requestId: '0822e0b5-5f4c-4242-8ec3-814d7178e427',
  __frame: 
   { name: 'doSettingsSet',
     line: 170,
     file: 'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\site.repository._js',
     prev: 
      { name: '__1',
        line: 38,
        file: 'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\site.repository._js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 14,
        col: 8 },
     calls: 1,
     active: false,
     offset: 7,
     col: 30 },
  rawStack: [Getter] }
Error: The request is invalid.
  <<< async stack >>>
  at doSettingsSet (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:177:31)
  at __1 (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\site.repository._js:52:9)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\node_modules\request\request.js:1111:12)
``` 

azure cli 0.9.15
node v4.3.1

home\site\deployments\settings.xml file has the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<settings>
    <deployment>
        <add key="branch" value="master" />
    </deployment>
</settings>
```

**Comment by amarzavery** [comment]
@ahmedelnably - This seems to be a server side issue. Can you please help in resolving this issue ?

**Comment by ahmedelnably** [comment]
We are looking into this, will loop back once I have any information

**Comment by davideicardi** [comment]
I have the same problem, any news?
