### ISSUE TITLE
VMAgentStatusCommunicationError

### ISSUE THREAD

**Issue by TimoKramer** [Azure/azure-xplat-cli#2628]
CLI Version: **0.9.15**
OS Type:  Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Description:
azure group deployment create -vv -f ~/azuredeploy.json -g $group returns

```
error:   Deployment provisioning state was not successful
error:   The resource operation completed with terminal provisioning state 'Failed'.
error:   Cannot call method 'forEach' of undefined
error:   group deployment create command failed
```

Steps to reproduce:
1) Run `group deployment -f azuredeploy.json -g $group`

Error stack trace:

```
2016-03-11T12:05:35.889Z:
{ [TypeError: Cannot call method 'forEach' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'exports_getFailedDeploymentOperations__3',
     line: 360,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js',
     prev: 
      { name: '__1',
        line: 68,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 10,
        col: 46 },
     calls: 1,
     active: true,
     offset: 4,
     col: 25 },
  rawStack: [Getter] }
TypeError: Cannot call method 'forEach' of undefined
  <<< async stack >>>
    at /usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:100:54
    at Array.forEach (native)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:98:84
    at Array.forEach (native)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:94:46)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:490:16)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at getFailedNestedOperations (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:504:14)
  at exports_getFailedDeploymentOperations__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:364:26)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:78:47)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:67:25)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:100:54
    at Array.forEach (native)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:98:84
    at Array.forEach (native)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment._js:94:46)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:490:16)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at __$getFailedNestedOperations (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:504:14)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13
```

azure group log show $group --json | jq '.[] | select(.status.value == "Failed")' returns

```
...
  "status": {
    "value": "Failed",
    "localizedValue": "Failed"
  },
...
  "properties": {
    "statusCode": "Conflict",
    "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMAgentStatusCommunicationError\",\"message\":\"VM 'dbtestg1' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent, and can establish outbound connections to Azure storage.\"}]}}"
  },
...
```
The attached file is my azuredeploy.json renamed to .pdf
[azuredeploy.pdf](https://github.com/Azure/azure-xplat-cli/files/169034/azuredeploy.pdf)
Thanks for help

**Comment by amarzavery** [comment]
So there are two issues over here
1. Resource Manager bug 
   - Cannot call method 'forEach' of undefined --> is a cli issue. We should check whether the array exists before doing the forEach
2. Compute issue
   - "VMAgentStatusCommunicationError\",\"message\":\"VM 'dbtestg1' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent, and can establish outbound connections to Azure storage

@ravbhatnagar @vivsriaus @huangpf @sauryadas - Can you please respond for your respective issues?

**Comment by huangpf** [comment]
Yes, I can see similar errors from other related commands. Will keep you posted.

**Comment by huangpf** [comment]
Confirm that it's a service side error, and it shall be fixed now. @TimoKramer Can you retry and see if it's fine now? Thanks.

**Comment by TimoKramer** [comment]
My Subscription is out of money. I will do this on Friday.

**Comment by vivsriaus** [comment]
With respect to the ResourceManager bug - the issue was fixed already. cc @ravbhatnagar

**Comment by sauryadas** [comment]
@amarzavery closing this. The creator of the bug @TimoKramer can reopen if this is not fixed yet.

**Comment by the1bit** [comment]
Hi,

Please provide me the solution's details because I have totally same issue and you did not provide the solution.

Thanks in advance.
