### ISSUE TITLE
[ARM] azure group delete: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2656]
CLI Version: 0.9.18
OS Type: Mac
Installation via:  npm

Mode: ARM

Description:
`azure group delete` fails with error `Cannot read property 'toLowerCase' of null`
![image](https://cloud.githubusercontent.com/assets/159209/13886243/4ae9e2c6-ecf3-11e5-9258-5069299a6eb9.png)

Error stack trace:

```
  ~ azure group delete -q ahmet-wp2 -vv
info:    Executing command group delete
error:   Cannot read property 'toLowerCase' of null
silly:   {
silly:       __frame: {
silly:           name: '__4',
silly:           line: 133,
silly:           file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
silly:           prev: undefined,
silly:           calls: 0,
silly:           active: true,
silly:           offset: -132,
silly:           col: 17
silly:       },
silly:       message: "Cannot read property 'toLowerCase' of null",
silly:       rawStack: "TypeError: Cannot read property 'toLowerCase' of null\n    at Object.exports.urlIsHTTPS (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/utils.js:14:29)\n    at ResourceManagementClient.ServiceClient._setDefaultProxy (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:105:13)\n    at ResourceManagementClient.ServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:60:8)\n    at ResourceManagementClient.AzureServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)\n    at new ResourceManagementClient (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/resourceManagementClient.js:64:38)\n    at Object.exports.createAutoRestClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:114:16)\n    at Object.exports.createResourceClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:310:15)\n    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:139:26)\n    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:383)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:399)\n",
silly:       stack: "TypeError: Cannot read property 'toLowerCase' of null\n  <<< async stack >>>\n    at Object.exports.urlIsHTTPS (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/utils.js:14:29)\n    at ResourceManagementClient.ServiceClient._setDefaultProxy (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:105:13)\n    at ResourceManagementClient.ServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:60:8)\n    at ResourceManagementClient.AzureServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)\n    at new ResourceManagementClient (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/resourceManagementClient.js:64:38)\n    at Object.exports.createAutoRestClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:114:16)\n    at Object.exports.createResourceClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:310:15)\n    at __4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:139:26)\n  <<< raw stack >>>\n    at Object.exports.urlIsHTTPS (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/utils.js:14:29)\n    at ResourceManagementClient.ServiceClient._setDefaultProxy (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:105:13)\n    at ResourceManagementClient.ServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:60:8)\n    at ResourceManagementClient.AzureServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)\n    at new ResourceManagementClient (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/resourceManagementClient.js:64:38)\n    at Object.exports.createAutoRestClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:114:16)\n    at Object.exports.createResourceClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:310:15)\n    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:139:26)\n    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:383)\n    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:399)\n"
silly:   }
info:    Error information has been recorded to /Users/alp/.azure/azure.err
verbose: TypeError: Cannot read property 'toLowerCase' of null
  <<< async stack >>>
    at Object.exports.urlIsHTTPS (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/utils.js:14:29)
    at ResourceManagementClient.ServiceClient._setDefaultProxy (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:105:13)
    at ResourceManagementClient.ServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:60:8)
    at ResourceManagementClient.AzureServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)
    at new ResourceManagementClient (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/resourceManagementClient.js:64:38)
    at Object.exports.createAutoRestClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:114:16)
    at Object.exports.createResourceClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:310:15)
    at __4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:139:26)
  <<< raw stack >>>
    at Object.exports.urlIsHTTPS (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/utils.js:14:29)
    at ResourceManagementClient.ServiceClient._setDefaultProxy (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:105:13)
    at ResourceManagementClient.ServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/serviceClient.js:60:8)
    at ResourceManagementClient.AzureServiceClient (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)
    at new ResourceManagementClient (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/resourceManagementClient.js:64:38)
    at Object.exports.createAutoRestClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:114:16)
    at Object.exports.createResourceClient (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:310:15)
    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:139:26)
    at __$__4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:383)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:134:399)

error:   group delete command failed
```

**Comment by amarzavery** [comment]
@ahmetalpbalkan - Thanks for reporting this issue. We shall fix this in the upcoming release.

**Comment by amarzavery** [comment]
@ahmetalpbalkan - It seems the result of nodes' url.parse(proxyUrl) had protocol undefined. Hence, this piece of code failed `urlToCheck.protocol.toLowerCase() === Constants.HTTPS;`. Ideally there should have been a check to ensure that protocol is defined and is of type 'string' before calling the toLowerCase() method.

However, the code enters this path only if you have one of the following envt. variables defined for proxy.
- HTTP_PROXY
- HTTPs_PROXY
- http_proxy
- https_proxy

Can you make sure that if one of the envt. variables is set then it has a correct url as its value?

**Comment by ahmetalpbalkan** [comment]
Ah that was probably it. Thanks.
