### ISSUE TITLE
ASM Azure network vpn-gateway shared-key set not working

### ISSUE THREAD

**Issue by ediazrod** [Azure/azure-xplat-cli#2690]
CLI Version: **0.9.15**
OS Type: Linux (Debian)
Installation via:  npm 

Mode: ARM 

Description:
`azure network vpn-gateway shared-key set VPNRemoteApp` Not change the Shared-key and not running

Steps to reproduce:
1) azure login
2)  azure network vpn-gateway shared-key set VPNRemoteApp
info:    Executing command network vpn-gateway shared-key set
Shared key value: asdf
+ Setting up shared key for vnet "VPNRemoteApp"
+ Looking up network VPN Gateway in virtual network "VPNRemoteApp"
error:   Default local network site is not set for virtual network "VPNRemoteApp"
info:    Error information has been recorded to /home/ediaz/.azure/azure.err
error:   network vpn-gateway shared-key set command failed

Error stack trace:

```
2016-03-28T17:02:47.125Z:
{ [Error: Default local network site is not set for virtual network "VPNRemoteApp"]
  stack: [Getter/Setter],
  __frame:
   { name: 'setSharedKey__10',
     line: 222,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js',
     prev:
      { name: '__48',
        line: 775,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 6,
        col: 17 },
     calls: 1,
     active: false,
     offset: 3,
     col: 9 },
  rawStack: [Getter] }
Error: Default local network site is not set for virtual network "VPNRemoteApp"
  <<< async stack >>>
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:841:26)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:486:17)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:482:13)
    at get__9 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:479:15)
  at setSharedKey__10 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:225:10)
  at __48 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:781:18)
  <<< raw stack >>>
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:841:26)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:486:17)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:482:13)
    at __$get__9 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:479:15)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:477:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:481:13)
    at __$get__9 (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/network/vpnGateway._js:464:21)
```

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this?

**Comment by MikhailTryakhov** [comment]
@romangromov works with vpn gateways commands block. We'll provide you details tomorrow
Thank you!

**Comment by romangromov** [comment]
@ediazrod you have to attach local-network to existing virtual network, then create vpn gateway and manupulate shared-key, see attached below:

```
azure network vnet create VnetForGateway -l "West US" -e 10.1.0.0 -i 16 -p 10.1.0.0 -r 19
azure network vnet subnet create -t VnetForGateway -n GatewaySubnet -a "10.1.32.0/29"
azure network local-network create -n LocalNet -a "10.2.0.0/16" -w 200.200.200.200
azure network vnet local-network add -n VnetForGateway -l LocalNet
azure network vpn-gateway create -n VnetForGateway -t DynamicRouting
azure network vpn-gateway shared-key set -n VnetForGateway -t LocalNet -k abcd
```

**Comment by ediazrod** [comment]
Yes is true :-) thanks a lot!!

**Comment by romangromov** [comment]
@ediazrod glad to help
