### ISSUE TITLE
[ARM] `azure vm image list` frequently time out on Ubuntu

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-xplat-cli#2691]
CLI Version: **0.9.18**
OS Type: Ubuntu
Installation via:  github repo

Mode: **ARM**

Description:
The command call or terst for `azure vm image list` frequently time out on Ubuntu, whereas the same call on Windows will finish mostly in time.

Steps to reproduce:
```
1. Create an Azure Ubuntu VM in Standard_A2 size
2. git clonse the CLI project to local
3. npm install & azure login
4. azure vm image list WestUS Canonical --json
```

Error stack trace:

```
Mon Mar 28 2016 05:47:40 GMT+0000 (UTC):
{ [Error: connect ETIMEDOUT 65.52.117.246:443]
  stack: [Getter/Setter],
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xxx.xxx.xxx.xxx',
  port: 443,
  __frame:
   { name: '_getVMImageListForPublisher__8',
     line: 193,
     file: '/x/lib/commands/arm/vm/vmImage._js',
     prev:
      { name: 'getVMImageList__5',
        line: 90,
        file: '/x/lib/commands/arm/vm/vmImage._js',
        prev:
         { name: 'listVMImages__32',
           line: 1250,
           file: '/x/lib/commands/arm/vm/vmClient._js',
           prev:
            { name: '__39',
              line: 832,
              file: '/x/lib/commands/arm/vm/vm._js',
              prev: undefined,
              calls: 3,
              active: false,
              offset: 12,
              col: 17 },
           calls: 1,
           active: false,
           offset: 11,
           col: 31 },
        calls: 1,
        active: false,
        offset: 14,
        col: 18 },
     calls: 1,
     active: false,
     offset: 43,
     col: 10 },
  rawStack: [Getter] }
'Error: connect ETIMEDOUT 65.52.117.246:443\n  <<< async stack >>>\n  at _getVMImageListForPublisher__8 (/x/lib/commands/arm/vm/vmImage._js:236:11)\n  at getVMImageList__5 (/x/lib/commands/arm/vm/vmImage._js:104:19)\n  at listVMImages__32 (/x/lib/commands/arm/vm/vmClient._js:1261:32)\n  at __39 (/x/lib/commands/arm/vm/vm._js:844:18)\n  <<< raw stack >>>\n    at Object.exports._errnoException (util.js:890:11)\n    at exports._exceptionWithHostPort (util.js:913:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)\n'
'node cli.js vm image list WestUS Canonical --json'
```

**Comment by huangpf** [comment]
@amarzavery 
Is it feasible to configure and increase the time-out limit?

**Comment by amarzavery** [comment]
@huangpf - This seems to be a vm setup/network issue. I ran the same command on centos VM of Standard_DS1 size and everything worked fine for me.

**Comment by huangpf** [comment]
@amarzavery 
Any general instruction on how to configure it? I created the Ubuntu VM from Azure, and didn't do any specific config, so I guess any users doing that will probably encounter the similar problem... 

Also, Standard_DS1 is a premium VM size, I don't think it's a general case. Have you tried a non-DS size VM?

**Comment by amarzavery** [comment]
@huangpf - I took the one that was available with the lowest config for my subscription. There is no special setup required. 

Are you seeing this only for this command or other commands as well?

What happens when you try azure group list OR azure location list ?

**Comment by huangpf** [comment]
Those commands will be fine. The errors usually happen for the current VM image list, because it involves quite some sub-calls, and the request/response payloads are very large. 

There is a previously reported issue about this as well: #2245

**Comment by amarzavery** [comment]
Not able to reproduce. It works well for me.

```
 testadmin@testbun2:~$ time azure vm image list westus Canonical UbuntuServer
. . . 
data:    Canonical  UbuntuServer  15.10-DAILY        Linux  15.10.201603290  westus    Canonical:UbuntuServer:15.10-DAILY:15.10.201603290
data:    Canonical  UbuntuServer  15.10-DAILY        Linux  15.10.201604050  westus    Canonical:UbuntuServer:15.10-DAILY:15.10.201604050
data:    Canonical  UbuntuServer  16.04-beta         Linux  16.04.201602231  westus    Canonical:UbuntuServer:16.04-beta:16.04.201602231
data:    Canonical  UbuntuServer  16.04-beta         Linux  16.04.201603220  westus    Canonical:UbuntuServer:16.04-beta:16.04.201603220
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604070  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604070
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604071  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604071
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604080  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604080
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604090  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604090
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604110  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604110
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604120  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604120
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604151  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604151
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604160  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604160
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604170  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604170
data:    Canonical  UbuntuServer  16.04.0-DAILY-LTS  Linux  16.04.201604180  westus    Canonical:UbuntuServer:16.04.0-DAILY-LTS:16.04.201604180
info:    vm image list command OK

real    0m4.809s
user    0m3.468s
sys     0m0.172s
```
