### ISSUE TITLE
Azure CLI default working directory does not permit user to save JSON template with 'azure capture vm'

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-xplat-cli#2702]
CLI Version: 0.9.16
OS Type: Windows 10
Installation via: Windows installer

Mode: ARM

Description:
When running 'azure vm capture' and specifying the name of the JSON template file, the default option is to save this JSON file to the present working directory, which is typically C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.8> when launching Azure CLI from Start menu. For a standard user, this will fail due to permissions unless you launch an elevated Azure CLI command prompt. Other similar commands that provide file output may have similar issue.

If you just launch a regular command prompt window, you'll typically be at C:\Users\<username> so the JSON template can successfully be saved. 

From a Linux machine, you just execute 'azure vm capture' from your shell of choice, so you're typically already in a working directory that you have permissions to.

I guess this more the default behavior of a new user, launching the Azure CLI from the Start menu, not being in a working directory to save things. azure vm capture --help only indicates the user should enter a file name, however you can enter a full filepath to an acceptable directory and it will save correctly.

Steps to reproduce:
1) Start | Microsoft Azure Command Prompt
2) azure vm capture testrg testvm vhdprefix -t capturedvm.json

If this is ran from an elevated Azure CLI prompt, it works fine.
If this is ran from Start | Command Prompt, it works fine as your default pwd is your home folder.

Error stack trace:
c:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.8>azure vm capture testcapture testcapturevm myprefix -t capturedvm.json -o
info:    Executing command vm capture
+ Looking up the VM "testcapturevm"
+ Capturing the virtual machine "testcapturevm"
error:   EPERM: operation not permitted, open 'c:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.8\capturedvm.json'
info:    Error information has been recorded to C:\Users\iainfou\.azure\azure.err
error:   vm capture command failed

2016-03-30T23:00:10.623Z:
{ [Error: EPERM: operation not permitted, open 'c:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.8\capturedvm.json']
  stack: [Getter/Setter],
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'c:\\Program Files\\Microsoft SDKs\\Azure\\.NET SDK\\v2.8\\capturedvm.json',
  __frame: 
   { name: 'captureVM__10',
     line: 417,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\vm\\vmClient.js',
     prev: 
      { name: '__11',
        line: 282,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\vm\\vm.js',
        prev: undefined,
        calls: 4,
        active: false,
        offset: 6,
        col: 15 },
     calls: 2,
     active: true,
     offset: 16,
     col: 32 },
  rawStack: [Getter] }
Error: EPERM: operation not permitted, open 'c:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.8\capturedvm.json'
  <<< async stack >>>
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vmClient.js:436:18)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:129)
    at __tryCatch (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:65)
    at captureVM__11 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:31)
  at captureVM__10 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vmClient.js:433:33)
  at __11 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vm.js:288:16)
  <<< raw stack >>>
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vmClient.js:436:18)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:129)
    at __tryCatch (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:65)
    at __$captureVM__11 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:151:31)
    at __tryCatch (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:150:4)

**Comment by amarzavery** [comment]
@iainfoulds - Thanks for reporting this.
It depends on the command prompt you are using. Looks like you are using azure 2.8 sdk prompt as your default prompt. We are not bundled under the azure sdk label. 
As you pointed that upon using the default command prompt that opens your home profile as the default location, the command executed correctly. This is what we expect as the general behavior.

Hence, this seems like a non issue.

**Comment by iainfoulds** [comment]
Agreed. It's more even if a user also then installed the Azure CLI standalone installer, a new user hitting the Start menu and searching for 'Azure' gets that SDK command prompt which defaults them to a directory they can't then save to. So it's an end user experience issue more so than Azure CLI. Didn't realize that necessarily falls outside the scope of this this team. Just wanted to raise awareness. I'll close out this issue. Thanks.
