### ISSUE TITLE
azure vm endpoint acl-rule create: unable to create rules on load-balanced-set endpoint

### ISSUE THREAD

**Issue by tbartlett0** [Azure/azure-xplat-cli#2717]
CLI Version: **0.9.17**
OS Type: Linux (Ubuntu 14.04 LTS)
Installation via:  npm

Mode: **ASM**

*Description*:
`azure vm endpoint acl-rule create` command returns an error when trying to add rules to an endpoint in a load-balanced set.

Steps to reproduce: first error:
1) Create at least two VMs with public endpoints in a shared load-balanced set
2) Then run `azure vm endpoint acl-rule create VMName EndpointName 0 permit 10.0.0.0/8`

```
2016-04-07T01:13:18.465Z:
{ [Error: Existing endpoints in LB set 'DNS-balance' do not contain ACL.]
  code: 'BadRequest',
  statusCode: 400,
  requestId: '911511ed3d5b91d880e727e093f21e1d' }
Error: Existing endpoints in LB set 'DNS-balance' do not contain ACL.
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

Steps to reproduce: second error:
1) Create at least two VMs with public endpoints in a shared load-balanced set
2) Create an ACL rule on the load-balanced endpoints using the Azure portal
3) Run `azure vm endpoint acl-rule create VMName EndpointName 1 permit 10.0.0.0/8`

```
Error stack trace:2016-04-07T00:45:13.341Z:
{ [Error: ACL rules do not match for endpoint in 'loadbalancedset'. Mismatch in rule count. Specified '2'. Existing '1'.]
  code: 'BadRequest',
  statusCode: 400,
  requestId: 'b06b480cd321992ba6e4254c4688f1e2' }
Error: ACL rules do not match for endpoint in 'loadbalancedset'. Mismatch in rule count. Specified '2'. Existing '1'.
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

*Comments:*

This appears to be the same / similar to the problem encountered in [Issue 1552](https://github.com/Azure/azure-xplat-cli/issues/1522), but that issue was closed when the 'acl-rule index 0' bug was fixed.

The wiki page for [Manage load balanced set](https://github.com/Azure/azure-xplat-cli/wiki/Manage-load-balanced-set) seems to imply that the ACLs should be managed with a `azure service lbsettings acl create` command which is not yet implemented. Does this mean they cannot be managed with `endpoint acl-rule` commands? If so it would help if the error message said so! (I began with the assumption that they should be configured my modifying one of the affected endpoints since this is the way I did it in the portal.)

If load-balanced endpoint ACLs require the `lbsettings` command to manage, then please consider this a feature request for implementing it.

**Comment by amarzavery** [comment]
@huangpf - Can you take a look at this issue?

**Comment by huangpf** [comment]
Networking team owns these features.

**Comment by amarzavery** [comment]
@romangromov @MikhailTryakhov - Please take a look.

**Comment by romangromov** [comment]
Hi @amarzavery,

In ASM, `LoadBalancerOperations` as well as `ACL's` are the part of `azure-asm-compute` 
package [computeManagementClient.js](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/computeManagement/lib/computeManagementClient.js) .

Also `azure vm <..> and azure service <..>` commands stack (both modes) are out of responsibility for our team

**Comment by MikhailTryakhov** [comment]
@amarzavery @huangpf  please let us know person who owns compute commands block - they can do it much better and faster in this area.
Please let us know if we can help something else.

**Comment by huangpf** [comment]
A while ago, there was a conversation that networking related features in ASM belongs to networking team. Unlike ARM, the package name may not align with the ownership in ASM. We can start an internal email thread to further discuss that.

**Comment by huangpf** [comment]
@amarzavery It's confirmed in the back-end triage that this belongs to Networking.

**Comment by MikhailTryakhov** [comment]
fixed
