### ISSUE TITLE
Unable to specify degreeOfParallelism when creating data lake job

### ISSUE THREAD

**Issue by edevil** [Azure/azure-xplat-cli#2747]
CLI Version: **0.9.19**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure datalake analytics job create -d 2` command errors out.

Steps to reproduce:
```
$ azure datalake analytics job create -d 2 brpxlaketest "teste41" la_ran_mm-extract.usql
info:    Executing command datalake analytics job create
error:   Error "parameters.degreeOfParallelism with value 2 must be of type number." occurred in serializing the payload - "{ jobId: '32b38ef6-7cbf-48e0-b1ae-2455ddbc42ab',
  name: 'teste41',
  type: 'USql',
  degreeOfParallelism: '2',
  priority: 1000,
...
```

Error stack trace:

2016-04-13T09:44:22.239Z:
{ [Error: Error "parameters.degreeOfParallelism with value 2 must be of type number." occurred in serializing the payload - "{ jobId: '32b38ef6-7cbf-48e0-b1ae-2455ddbc42ab',
  name: 'teste41',
  type: 'USql',
  degreeOfParallelism: '2',
  priority: 1000,
  properties:
   { type: 'USql',
     script: ...
  stack: [Getter/Setter],
  __frame:
   { name: '__1',
     line: 58,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 72,
     col: 33 },
  rawStack: [Getter] }
Error: Error "parameters.degreeOfParallelism with value 2 must be of type number." occurred in serializing the payload - "{ jobId: '32b38ef6-7cbf-48e0-b1ae-2455ddbc42ab',
  name: 'teste41',
  type: 'USql',
  degreeOfParallelism: '2',
  priority: 1000,
  properties:
   { type: 'USql',
     script: ...
  <<< async stack >>>
    at Job.create (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-datalake-analytics/lib/job/operations/job.js:964:30)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:130:33)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:130:34)
  <<< raw stack >>>
    at Job.create (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-datalake-analytics/lib/job/operations/job.js:964:30)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:130:33)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:130:165)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:84:110)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:79:124)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

**Comment by amarzavery** [comment]
@begoldsm - Can you take a look at this issue?

**Comment by begoldsm** [comment]
I think I see the issue. Previously when using Hydra to generate we didn't enforce hard types, so everything was treated as a string (and everything is treated as a string when passed in on the command line). I will fix this and it will be available for the next release. Good catch!

**Comment by amarzavery** [comment]
@begoldsm - We have the release branch open right now. I will be generating installers tomorrow for a hotfix release. The installers will be publicly available on 04/19. Just letting you know, incase you want to target for this release.
