### ISSUE TITLE
ARM: Application gateway with custom backend port

### ISSUE THREAD

**Issue by sofam** [Azure/azure-xplat-cli#2768]
CLI Version: 0.9.19
OS Type: Mac
Installation via:  npm 
Mode: ARM

Description:
`azure network application-gateway create -n AGNAME -g MYGROUP -e TESTING -m GatewaySubnet -k AGPIP -o 9080 -r 77.22.22.22 -y ~/wobbletest.pfx -x myVeryStrongPassword -l northeurope ` command exists with `error:   Error "parameters.properties.backendHttpSettingsCollection.properties.port with value 9080 must be of type number." occurred in serializing the payload - `

Steps to reproduce:
1) Run the above command with a custom port defined with -o

Error stack trace:

`  <<< async stack >>>
    at ApplicationGateways.beginCreateOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:669:30)
    at ApplicationGateways.createOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:467:8)
    at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:138:75)
  at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:138:76)
  at __119 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:2506:18)
  <<< raw stack >>>
    at ApplicationGateways.beginCreateOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:669:30)
    at ApplicationGateways.createOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:467:8)
    at __$create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:138:75)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:135:193)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:138:246)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:140:165)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway.js:759:20)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
`

**Comment by romangromov** [comment]
As FYI: @MikhailTryakhov

**Comment by MikhailTryakhov** [comment]
Hi @sofam  thank you for this fix!
