### ISSUE TITLE
VpnClientAddressPool is not created

### ISSUE THREAD

**Issue by pablolibo** [Azure/azure-xplat-cli#2789]
CLI Version: **0.9.19**
OS Type:  Ubuntu 14.04 with docker
Installation via:  last dockerfile

Mode: **ARM **

Description:
I have been creating a new "gateway" but I have some error when I tray create it:

Steps to reproduce:
```
1) azure network vnet create --resource-group PlatDigTest01
2) azure network vnet subnet create --resource-group PlatDigTest01 \
      --vnet-name PlatDigTest01 --name GatewaySubnet \
      --address-prefix 10.0.0.0/16
3) azure network vnet subnet create --resource-group PlatDigTest01 \
      --vnet-name PlatDigTest01 --name 10.0.255.0/27 \
      --address-prefix 10.0.255.0/27
4) azure network public-ip create --resource-group PlatDigTest01 \
      --name GatewayIP --location brazilsouth --allocation-method Dynamic 
5) azure network vpn-gateway create --resource-group PlatDigTest01 \
      --name PlatDigTest01 --location brazilsouth \
      --sku-name Basic --public-ip-name GatewayIP --vnet-name PlatDigTest01

```

**The Output error is:**
Cannot read property 'vpnClientAddressPool' of undefined\nerror:   network vpn-gateway create command failed", "stdout": "info:    Executing command network vpn-gateway create\nwarn:    Using default subnet name: GatewaySubnet\ninfo:  

Error stack trace:

```
cat /root/.azure/azure.err
2016-04-21T14:34:13.246Z:
{ [TypeError: Cannot read property 'vpnClientAddressPool' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: '__102',
     line: 2141,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/network/network.js',
     prev: undefined,
     calls: 4,
     active: false,
     offset: 7,
     col: 18 },
  rawStack: [Getter] }
TypeError: Cannot read property 'vpnClientAddressPool' of undefined
  <<< async stack >>>
    at /usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:738:21
    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:248:7)
    at VirtualNetworkGateway.__.extend._showGateway (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:712:22)
    at create__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:97:24)
  at __102 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:2148:19)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:738:21
    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:248:7)
    at VirtualNetworkGateway.__.extend._showGateway (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:712:22)
    at __$create__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:97:24)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:94:185)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:94:118)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:94:73)
    at __$create__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetworkGateway.js:94:39)
```

That's very strange because the gateway is created and it works, but the error always happens.
Thanks a lot!

**Comment by romangromov** [comment]
@pablolibo thanks for flagging, let me take a look and come back, stay tuned

**Comment by romangromov** [comment]
@pablolibo can't reproduce this on latest Xplat-CLI of `0.9.20`,working fine for me:

```
>azure network vpn-gateway create --resource-group test-roman-group --name MyGateway --location eastus --sku-name Basic --public-ip-name IPForGateway --vnet-name VnetForGateway
info:    Executing command network vpn-gateway create
warn:    Using default subnet name: GatewaySubnet
+ Looking up the public ip "IPForGateway"
+ Looking up the subnet "GatewaySubnet"
+ Looking up virtual network gateway "MyGateway"
+ Creating virtual network gateway "MyGateway"
CREATE: {"id":"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway","name":"MyGateway","type":"Microsoft.Network/virtualNetwor
kGateways","location":"eastus","ipConfigurations":[{"id":"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway/ipConfigurations
/ip-config","privateIPAllocationMethod":"Dynamic","subnet":{"id":"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworks/VnetForGateway/subnets/Ga
tewaySubnet"},"publicIPAddress":{"id":"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/publicIPAddresses/IPForGateway"},"provisioningState":"Succeeded","na
me":"ip-config","etag":"W/\"d156bc3a-b6c1-485d-a753-042e7f8b24d5\""}],"gatewayType":"Vpn","vpnType":"RouteBased","enableBgp":false,"sku":{"name":"Basic","tier":"Basic","capacity":2},"bgpSettings":{"asn":65515,"bgpPeerin
gAddress":"10.0.255.254","peerWeight":0},"resourceGuid":"c53cf4c6-6abd-4715-97c3-3aae2d2e08fd","provisioningState":"Succeeded","etag":"W/\"d156bc3a-b6c1-485d-a753-042e7f8b24d5\""}
data:    Id                              : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway
data:    Name                            : MyGateway
data:    Type                            : Microsoft.Network/virtualNetworkGateways
data:    Location                        : eastus
data:    Provisioning state              : Succeeded
data:    Gateway type                    : Vpn
data:    VPN type                        : RouteBased
data:    Enable BGP                      : false
data:    SKU:
data:      Name                          : Basic
data:      Tier                          : Basic
data:      Capacity                      : 2
data:    IP configurations:
data:      Id                            : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway/ipConfigurations/ip-config
data:      Name                          : ip-config
data:      Provisioning state            : Succeeded
data:      Private IP allocation method  : Dynamic
data:      Public IP address id          : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/publicIPAddresses/IPForGateway
data:      Subnet id                     : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworks/VnetForGateway/subnets/GatewaySubnet
data:
info:    network vpn-gateway create command OK

```

Can you please update cli and let me know?
Also please confirm you are trying to create a gateway of type `Vpn`, but not `ExpressRoute`

**Comment by pablolibo** [comment]
Hi @romangromov , I have tested the last version (0.9.20) and the issue doesn't happend again

Thanks a lot and sorry for my delay

**Comment by romangromov** [comment]
@pablolibo not a problem at all, thanks for confirmation! 

Please **close** the issue, re-open if you come across this again.
