### ISSUE TITLE
Unable to create keyvault

### ISSUE THREAD

**Issue by ncodes** [Azure/azure-xplat-cli#2800]
CLI Version: **0.9.20**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
I cannot create a keyvault with this command:  `azure keyvault create --vault-name newdawnvault --resource-group newdawn --location "east asia"`

Steps to reproduce:
1) Run `azure group create newdawn "east asia"`
2) Then run `azure keyvault create --vault-name newdawnvault --resource-group newdawn --location "east asia".`

Error stack trace:

**
{ [Error: Unable to find user with upn email@outlook.com]
  stack: [Getter/Setter],
  __frame:
   { name: 'getAccountFromSubscription',
     line: 889,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js',
     prev:
      { name: 'getObjectId',
        line: 839,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 9,
        col: 16 },
     calls: 1,
     active: false,
     offset: 12,
     col: 15 },
  rawStack: [Getter] }
Error: Unable to find user with upn email@outlook.com
  <<< async stack >>>
  at getAccountFromSubscription (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js:901:16)
  at getObjectId (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js:848:17)
  at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js:175:22)
  <<< raw stack >>>
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.js:881:20)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
**

**Comment by amarzavery** [comment]
Duplicate #2709 

@msfcolombo - Please take a look at this issue on priority. Another customer also faced a similar issue.
