### ISSUE TITLE
azure storage blob: root container ($root) causes error

### ISSUE THREAD

**Issue by arafato** [Azure/azure-xplat-cli#2816]
CLI Version: **0.9.19**
OS Type: Linux (Ubuntu 15.10)
Installation via:  npm

Mode: **ASM**

Description:
`azure storage blob upload foo.txt $root foo.txt`

Results in
```
info:    Executing command storage blob upload
+ Checking blob index.html in container index.html                             
error:   Container name format is incorrect.
info:    Error information has been recorded to /home/arafato/.azure/azure.err
error:   storage blob upload command failed
```

It seems that the character $ causes trouble...

Error stack trace:

```
2016-04-26T09:37:49.324Z:
{ [Error: Container name format is incorrect.]
  stack: [Getter/Setter],
  __frame:
   { name: 'StorageUtil_performStorageOperation__1',
     line: 350,
     file: '/usr/lib/node_modules/azure-cli/lib/util/storage.util.js',
     prev:
      { name: 'uploadAzureBlob',
        line: 829,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js',
        prev: undefined,
        calls: 3,
        active: false,
        offset: 47,
        col: 25 },
     calls: 1,
     active: false,
     offset: 19,
     col: 4 },
  rawStack: [Getter] }
Error: Container name format is incorrect.
  <<< async stack >>>
    at fail (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:38:13)
    at ArgumentValidator.exports.containerNameIsValid (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:204:12)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:1274:7
    at Object.validateArgs (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:498:3)
    at Object.BlobService.getBlobProperties (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:1271:12)
    at Function.Object.defineProperty.value (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/builtins.js:367:19)
    at __1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:371:41)
  at StorageUtil_performStorageOperation__1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:369:5)
  at uploadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:876:26)
  <<< raw stack >>>
    at fail (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:38:13)
    at ArgumentValidator.exports.containerNameIsValid (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:204:12)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:1274:7
    at Object.validateArgs (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:498:3)
    at Object.BlobService.getBlobProperties (/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:1271:12)
    at Function.Object.defineProperty.value (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/builtins.js:367:19)
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:371:41)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 [as fn] (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:369:135)
    at _doOne (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/builtins.js:57:17)

```

**Comment by ahmetalpbalkan** [comment]
@arafato it is very likely your shell is treating `$root` as a variable and trying to expand it as such. Please try quoting that argument with single quotes, or you can prepend an `echo` to your `azure` command and see what gets executed.

**Comment by arafato** [comment]
Thanks @ahmetalpbalkan ! Single quotes did it, I was using double quotes...
