### ISSUE TITLE
Error message from command line gives location in the single line version of the JSON template

### ISSUE THREAD

**Issue by russellseymour** [Azure/azure-xplat-cli#2873]
CLI Version: 0.10.0
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
When using `azure group deployment create ...` with an error in the template file the application gives the location of the error in the minified single line version of the JSON template, e.g.:

```
Unable to process template language expressions for resource '/subscriptions/1e0b427a-d58b-494e-ae4f-ee558463ebbf/resourceGroups/cpcp/providers/Microsoft.Compute/virtualMachines/jenkins-01' at line '1' and column '2895'. 'Template language expression property 'osdisk' doesn't exist, available properties are 'datadisk, odsisk, nic'. Please see http://aka.ms/arm-template-expressions for usage details.'
```

The error message should give the location in the non-minified version of the JSON so it is more human readable.  For example. line 25 column 46 instead of line 1 column 2895.

Steps to reproduce:
1) Create a template and set a variable name incorrectly, e.g. `odsisk` and then try to use the variable name `osdisk`.
2) Use the `azure group deployment create ...` command to create the deployment in Azure.

```
Error stack trace:
2016-05-12T13:49:07.444Z:
{ [Error: Deployment validate failed.]
  stack: [Getter/Setter],
  __frame:
   { name: 'exports_createDeployment__1',
     line: 70,
     file: '/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
     prev:
      { name: '__1',
        line: 52,
        file: '/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 21,
        col: 34 },
     calls: 2,
     active: false,
     offset: 17,
     col: 31 },
  rawStack: [Getter] }
Error: Deployment validate failed.
  <<< async stack >>>
  at exports_createDeployment__1 (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:87:32)
  at __1 (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:73:35)
  <<< raw stack >>>
    at ___ (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:97:24)
    at ___ (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1213:12
    at retryCallback (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/util/utils.js:543:7
    at handleRedirect (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/util/utils.js:520:9)
    at /usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/lib/util/logging.js:412:7
    at Request._callback (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/Cellar/node/5.7.0/libexec/npm/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
```

**Comment by eduardkoller** [comment]
@vivsriaus @ravbhatnagar - can you please take a look?

**Comment by vivsriaus** [comment]
@russellseymour  @ravbhatnagar Can you please share the template file and the command you ran? FWIW, I tried reproducing this using a faulty template and I get the expected error (with the correct line number):

$ node bin/azure group deployment create -g vtest --template-uri https://raw.githubusercontent.com/vivsriaus/armtemplates/master/invalidJsonTemplate.json
info:    Executing command group deployment create
info:    Supply values for the following parameters
error:   Parse error on line 29:
...outputs": {                  }} blah
--------------------^
Expecting 'EOF', '}', ',', ']', got 'undefined'
info:    Error information has been recorded to c:\Users\visriniv\.azure\azure.err
error:   group deployment create command failed

**Comment by amarzavery** [comment]
@vivsriaus  - I remember you adding the json linter in a PR. I am not sure if that PR was a part of 0.10.0. Did you run the code from the 0.10.0 version or from your local repo clone?

**Comment by vivsriaus** [comment]
@amarzavery I ran this from my local repo clone. May be the user has to run npm install again?

**Comment by ravbhatnagar** [comment]
Looks like this has been fixed. @russellseymour Feel free to comment if you still see this issue and I will reopen
