### ISSUE TITLE
Storage blob upload error

### ISSUE THREAD

**Issue by techgeek03** [Azure/azure-xplat-cli#2875]
CLI Version: **0.10.0**
OS Type: Linux (Ubuntu)
Installation via:  npm
node version: 6.1.0
npm version: 3.8.6

Mode: **ARM**

Description:
azure storage blob upload 'test.txt' container blob 
throws error "If encoding is specified then the first argument must be a string" on Ubuntu with node 6.1.0 and npm 3.8.6

Steps to reproduce:
1) Run `azure storage blob upload 'test.txt' container blob`

Error stack trace:

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Object.StorageUtil.getSpeedPrinter (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:748:21)
    at __$uploadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:902:41)
    at __$uploadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:891:384)
    at __$uploadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:891:400)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:883:190)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:883:123)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:883:78)

**Comment by techgeek03** [comment]
Editing /usr/lib/node_modules/azure-cli/lib/util/storage.util.js line 748 by deleting the "utf8" parameter solved the problem.

**Comment by amarzavery** [comment]
@yaxia - can you please take a look?

**Comment by yaxia** [comment]
It's fixed in the commit:  https://github.com/Azure/azure-xplat-cli/commit/896de300bfa9859e0618cdb8527d0c3e18c86ae0
