### ISSUE TITLE
ARM: application-gateway create -b/--http-listener-protocol throws an exception

### ISSUE THREAD

**Issue by jozefsukovsky** [Azure/azure-xplat-cli#2876]
CLI Version: **0.10.0**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm

Mode: **ARM**

Description:
`azure network application-gateway create` command throws an exception when using -b/--http-listener-protocol

Steps to reproduce:
1) Run `azure network application-gateway create -b [http|https].`

Error stack trace:

2016-05-12T18:45:16.394Z:
[TypeError: Cannot call method 'toLowerCase' of undefined]
TypeError: Cannot call method 'toLowerCase' of undefined
    at __$__124 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js:2727:144)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js:2740:15)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:99:14
    at Object.__g.trampoline.flush (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:58:61)
    at AzureCli.__124 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js:2717:12)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/cli.js:229:12)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at AzureCli.emit (events.js:98:17)

-------------

this condition: options.httpListenerProtocol.toLowerCase() === constants.appGateway.settings.protocol[1].toLowerCase())

references constants.appGateway.settings.protocol which I believe should be constants.appGateway.httpListener.protocol instead.

**Comment by amarzavery** [comment]
@romangromov @MikhailTryakhov - please take a look?

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in next release (end of May)
