### ISSUE TITLE
ARM: application-gateway create does not validate -x/--cert-password correctly

### ISSUE THREAD

**Issue by jozefsukovsky** [Azure/azure-xplat-cli#2877]
CLI Version: **0.10.0**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure network application-gateway create` ignores -x/--cert-password and throws an error **verbose: Error: --password parameter must not be empty** even there is no --password parameter present. (at least using `azure network application-gateway create -h`. 

Steps to reproduce:
1) Run `azure network application-gateway create` with -y and -x

Error stack trace:

2016-05-12T19:00:14.922Z:
{ [Error: --password parameter must not be empty]
  stack: [Getter/Setter],
  __frame: 
   { name: 'create__1',
     line: 39,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js',
     prev: 
      { name: '__124',
        line: 2609,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js',
        prev: undefined,
        calls: 9,
        active: false,
        offset: 19,
        col: 17 },
     calls: 2,
     active: true,
     offset: 10,
     col: 35 },
  rawStack: [Getter] }
Error: --password parameter must not be empty
  <<< async stack >>>
    at AppGateways.__.extend._setDefaultAttributes (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:1840:15)
    at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:56:29)
  at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:49:36)
  at __124 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js:2628:18)
  <<< raw stack >>>
    at AppGateways.__.extend._setDefaultAttributes (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:1840:15)
    at __$create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:56:29)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:51:15)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/subnet._js:273:17)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/subnet._js:269:13)
    at __$get__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/subnet._js:266:15)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/subnet._js:264:13)

**Comment by amarzavery** [comment]
@romangromov @MikhailTryakhov - please take a look?

**Comment by MikhailTryakhov** [comment]
Hi @jozefsukovsky 
thank you for a great job!
This issue duplicates issue [#2877](https://github.com/Azure/azure-xplat-cli/issues/2877). It's fixed in PR[#2861](https://github.com/Azure/azure-xplat-cli/pull/2861) and would be published in next release.

**Comment by MikhailTryakhov** [comment]
sorry @jozefsukovsky. You're right - this is another issue.
Would be fixed soon

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in next release (end of May)
