### ISSUE TITLE
ARM: application-gateway create -z/--capacity invalidates number

### ISSUE THREAD

**Issue by jozefsukovsky** [Azure/azure-xplat-cli#2878]
CLI Version: **0.10.0**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure network application-gateway create -z/--capacity [2,10]` throws Error "parameters.properties.sku.capacity with value 2 must be of type number." occurred in serializing the payload

Steps to reproduce:
1) Run `azure network application-gateway create -z 2`

Error stack trace:

2016-05-12T19:19:57.143Z:
{ [Error: Error "parameters.properties.sku.capacity with value 2 must be of type number." occurred in serializing the payload - "{ name: 'agw',
  location: 'West Europe',
  sku: { capacity: '2', name: 'Standard_Medium', tier: 'Standard' },
  
.....shortened.......

  <<< async stack >>>
    at ApplicationGateways.beginCreateOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:669:30)
    at ApplicationGateways.createOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:467:8)
    at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:153:75)
  at create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:138:76)
  at __124 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network._js:2628:18)
  <<< raw stack >>>
    at ApplicationGateways.beginCreateOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:669:30)
    at ApplicationGateways.createOrUpdate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/applicationGateways.js:467:8)
    at __$create__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:153:75)
    at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:152:17)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:158:17)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:174:15)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/appGateway._js:1639:20)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)

**Comment by amarzavery** [comment]
@MikhailTryakhov @romangromov - This should be a simple fix. Commander treats all the values given from command line as a string. You will have to use `parseInt(value)` before passing it to the sdk.

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in next release (end of May)
