### ISSUE TITLE
Does Azure CLI support proxy?

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#2882]
CLI Version: **0.10.0**
OS Type: Win
Installation via:  win-or-mac installer

Mode: ARM

Description:
In many corporate environments, proxies are in heavy use. The Azure CLI seems not to support proxies. Can you help to confirm it? If not, when can Azure CLI support proxies?

**Comment by amarzavery** [comment]
set HTTP_PROXY=""
OR 
set HTTPS_PROXY=""
and that should work.
This is looked at in the node sdk runtime that CLI depends on.
https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest/lib/serviceClient.js#L91

**Comment by AbelHu** [comment]
Thanks, @amarzavery. In Linux, the command is as below.
export HTTP_PROXY=""
or 
export HTTPS_PROXY=""

**Comment by AbelHu** [comment]
'set HTTP_PROXY="" ' does not work on Windows.

Version: 0.10.0

Command and result:
```
$azure login
info:    Executing command login
+ Authenticating...
error:   tunneling socket could not be established, cause=connect ECONNREFUSED 1
27.0.0.1:80
info:    Error information has been recorded to C:\Users\xxx\.azure\azure.err

error:   login command failed
```

.azure\azure.details.err
```
2016-05-19T07:30:16.083Z - info:    Executing command login
2016-05-19T07:30:17.147Z - error:   tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
2016-05-19T07:30:17.147Z - silly:   {
2016-05-19T07:30:17.147Z - silly:       __frame: {
2016-05-19T07:30:17.147Z - silly:           name: '__1',
2016-05-19T07:30:17.147Z - silly:           line: 49,
2016-05-19T07:30:17.147Z - silly:           file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
2016-05-19T07:30:17.147Z - silly:           prev: undefined,
2016-05-19T07:30:17.147Z - silly:           calls: 0,
2016-05-19T07:30:17.147Z - silly:           active: false,
2016-05-19T07:30:17.147Z - silly:           offset: 64,
2016-05-19T07:30:17.147Z - silly:           col: 27
2016-05-19T07:30:17.147Z - silly:       },
2016-05-19T07:30:17.147Z - silly:       message: 'tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80',
2016-05-19T07:30:17.147Z - silly:       rawStack: 'Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\n    at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\request\\node_modules\\tunnel-agent\\index.js:176:17)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at Socket.socketErrorListener (_http_client.js:259:9)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at emitErrorNT (net.js:1257:8)\n    at doNTCallback2 (node.js:441:9)\n    at process._tickCallback (node.js:355:17)',
2016-05-19T07:30:17.147Z - silly:       stack: 'Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\n  <<< async stack >>>\n  at __1 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js:113:28)\n  <<< raw stack >>>\n    at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\request\\node_modules\\tunnel-agent\\index.js:176:17)\n    at ClientRequest.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)\n    at Socket.socketErrorListener (_http_client.js:259:9)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at emitErrorNT (net.js:1257:8)\n    at doNTCallback2 (node.js:441:9)\n    at process._tickCallback (node.js:355:17)',
2016-05-19T07:30:17.147Z - silly:       code: 'ECONNRESET'
2016-05-19T07:30:17.147Z - silly:   }
2016-05-19T07:30:17.163Z - info:    Error information has been recorded to C:\Users\abelch\.azure\azure.err
```

.azure.err
```
2016-05-19T07:30:17.147Z:
{ [Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80]
  stack: [Getter/Setter],
  code: 'ECONNRESET',
  __frame: 
   { name: '__1',
     line: 49,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 64,
     col: 27 },
  rawStack: [Getter] }
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:113:28)
  <<< raw stack >>>
    at ClientRequest.onError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1257:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by yugangw-msft** [comment]
This is not right. For windows, the batch file to work with fiddler are in the repository
https://github.com/Azure/azure-xplat-cli/blob/dev/tools/windows/scripts/enableFiddler.cmd
https://github.com/Azure/azure-xplat-cli/blob/dev/tools/windows/scripts/disableFiddler.cmd

**Comment by amarzavery** [comment]
@AbelHu - From the snapshot you provided above `$ azure login`. It looks like you are using git bash on windows.

For bash you need to use `export HTTP_PROXY=""`.

FYI, Please do not use powershell prompt from windows. It is not supported for azure-xplat-cli. The commands may or may not work as expected.

**Comment by AbelHu** [comment]
I use ‘Command Prompt’ in Windows. The same proxy works in Linux but does not work in Windows.

**Comment by AbelHu** [comment]
@amarzavery @yugangw-msft Ping...

**Comment by amarzavery** [comment]
AS we said this works for us. Yugang even showed you a script that sets/unsets the HTTP_PROXY.

I would say try HTTPS_PROXY as well.

I have tested and this works well on my windows box as well.

**Comment by AbelHu** [comment]
@amarzavery On Windows, it seems like that the proxy address is always 127.0.0.1:80 whatever you set in HTTP_PROXY. You can see the error message in above comments.

**Comment by AbelHu** [comment]
Ping...

**Comment by AbelHu** [comment]
@amarzavery Please see the result in the below screenshot. The command to set HTTP proxy works in PowerShell but does not work in command line.

![image](https://cloud.githubusercontent.com/assets/6416187/17843007/983af8b0-685b-11e6-874c-6f8ba06e435f.png)

**Comment by amarzavery** [comment]
That is the problem. 
- Firstly, using `set` syntax is not the correct way to set environment variables in powershell. That statement has no effect. [This](http://windowsitpro.com/powershell/powershell-one-liner-creating-and-modifying-environment-variable) is how one can set environment variables in powershell.  We do not officially support the powershell prompt. Most of the times things should work. However, if they dont, then they just dont.
- Secondly when you set the environment variable in cmd prompt why are you setting the value in single quotes. There shouldnt be any quotes.

To make your life easy set the following environment variables as described below (just copy paste the text as-is.
```
set NODE_TLS_REJECT_UNAUTHORIZED=0
set HTTPS_PROXY=http://10.0.0.7
```
If you look at the above comments closely, then on May 19, Yugang also provided you the links that show how to set and unset environment variables in a comment. 

Hope this resolves your issue.

**Comment by AbelHu** [comment]
Same issues. Please see them in below screenshot.
![image](https://cloud.githubusercontent.com/assets/6416187/17844177/175aec7e-6869-11e6-8f03-0ba1c7d9e92e.png)

**Comment by amarzavery** [comment]
Btw, why do you want to set a proxy?
what version of node.js are you using?
Did you try with a port number? How about `set HHTPS_PROXY=http://10.0.0.7:8080`

**Comment by AbelHu** [comment]
@amarzavery After I changed my proxy port to 808, it works now. Thank you so much.

NOT WORK:
set HTTPS_PROXY='10.0.0.7:808'
set HTTPS_PROXY="10.0.0.7:808"
set HTTPS_PROXY=https://10.0.0.7:808

WORK:
set HTTPS_PROXY=http://10.0.0.7:808

**Comment by rkralston** [comment]
If this is picked up by Node, could you just set the Node configuration for proxy?

**Comment by cyberfox1** [comment]
It does not work on Linux either, even with http_proxy, https_proxy etc set. Lame.
