### ISSUE TITLE
"group template list" failed

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2906]
CLI Version: **0.9.18**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **Azure China Cloud**

Description:
`azure group template list` command doesn't output the template.

Steps to reproduce:
1) login in AzureChinaCloud
2) Then run `azure group template list`

Error stack trace:

```
2016-05-27T04:21:25.043Z:
{ [Error: getaddrinfo ENOTFOUND gallery.chinacloudapi.cn gallery.chinacloudapi.cn:443]
  stack: [Getter/Setter],
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'gallery.chinacloudapi.cn',
  host: 'gallery.chinacloudapi.cn',
  port: 443,
  __frame:
   { name: '__1',
     line: 55,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.template.js',
     prev:
      { name: '__1',
        line: 42,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.template.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 12,
        col: 35 },
     calls: 0,
     active: false,
     offset: 1,
     col: 30 },
  rawStack: [Getter] }
Error: getaddrinfo ENOTFOUND gallery.chinacloudapi.cn gallery.chinacloudapi.cn:443
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.template.js:56:31)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.template.js:54:36)
  <<< raw stack >>>
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

**Comment by bingosummer** [comment]
Any update on this issue?

**Comment by haocs** [comment]
@bingosummer - "gallery.chinacloudapi.cn" seems not longer available. Let me check with service team.

**Comment by bingosummer** [comment]
@haocs , thanks for your confirmation.
Do you have a plan to fix it?

**Comment by eduardkoller** [comment]
@ravbhatnagar @vivsriaus - can you please take a look?

**Comment by bingosummer** [comment]
@ravbhatnagar @vivsriaus 

Any update on this?

**Comment by ravbhatnagar** [comment]
@bingosummer Apologize for the delay here. We will investigate this.

**Comment by ravbhatnagar** [comment]
Following up with the marketplace team which owns this.
