### ISSUE TITLE
Server Error when starting/stopping/restarting App Services

### ISSUE THREAD

**Issue by madorb** [Azure/azure-xplat-cli#2923]
CLI Version: **0.10.1**
OS Type: Mac AND  Linux (Amazon Linux)
Installation via: npm AND brew

Mode: **ASM**

Environment: **AzureCloud**

Description:
`azure site (start|stop|restart)` results in server error

Steps to reproduce:
1) Run `azure site *`
2) See error

Additional Details:
This started happening today on multiple servers both our automated CI (amazon linux) machine and my local machine (mac). It appear that using `arm` mode *does* work as i was able to do `azure webapp restart <resource group> <sitename>` but `asm` mode does not seem to function. 

Error stack trace:

```
2016-06-03T17:56:55.077Z:
{ [Error: The server encountered an internal error. Please retry the request.]
  stack: [Getter/Setter],
  code: 'InternalError',
  statusCode: 500,
  requestId: '455cb1ff4a09ab8ea9de5df890dd7210',
  __frame: 
   { name: 'updateSite__10',
     line: 552,
     file: '/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js',
     prev: 
      { name: '__12',
        line: 831,
        file: '/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/lib/commands/asm/site._js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 13,
        col: 15 },
     calls: 0,
     active: false,
     offset: 7,
     col: 30 },
  rawStack: [Getter] }
Error: The server encountered an internal error. Please retry the request.
  <<< async stack >>>
  at updateSite__10 (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient._js:559:31)
  at __12 (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/lib/commands/asm/site._js:844:16)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/boxen/homebrew/Cellar/azure-cli/0.10.1/libexec/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)

```

**Comment by madorb** [comment]
Not sure if this is a fabric issue or a cli issue - but thought i'd at least open the ticket in case others are seeing it (in either case)

**Comment by madorb** [comment]
This was definitely an infrasturcture issue. Was getting back 500 errors with body: 
```<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>InternalError</Code><Message>The server encountered an internal error. Please retry the request.</Message></Error>``` from every start/stop/restart request to 

`https://management.core.windows.net/xxxx/services/WebSpaces/ResourceGroupname-WestUSwebspace/sites/ggp-dm-mall-batch-dev
