### ISSUE TITLE
Error message 'ConsoleScreenshotBlobUri' should not be set.

### ISSUE THREAD

**Issue by CraigWiand** [Azure/azure-xplat-cli#2926]
CLI Version: 0.10.0
OS Type: Win + Linux (CentOS.)
Installation via:  npm 

Mode: ARM + ASM

Environment: AzureCloud

Description:
_'ConsoleScreenshotBlobUri' should not be set._

Steps to reproduce:
1) Locate a Linux VM that has the `DebugSettings>ConsoleScreenshotBlobUri` attribute set
2)  Call **azure vm extension set** command against the VM

Error stack trace:
```
2016-05-20T13:15:26.814Z:
{ [Error: Parameter 'ConsoleScreenshotBlobUri' should not be set.]
  code: 'BadRequest',
  statusCode: 400,
  requestId: '158cd3ddc726a1e49ef621794d36ffdc' }
Error: Parameter 'ConsoleScreenshotBlobUri' should not be set.
    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
```

Please contact CraigW internally for more detailed troubleshooting information

**Comment by eduardkoller** [comment]
@huangpf - can you please take a look? /c @sauryadas.

**Comment by squillace** [comment]
Anyone have a chance to look?

**Comment by huangpf** [comment]
I think it's ```ASM``` only, not ```ASM + ARM```. Could you please help confirm?

**Comment by squillace** [comment]
One person asserted that it was in ARM, but the only clear cases I know of are in ASM. Ping cynthn internally for another repro.

**Comment by cynthn** [comment]
I'm seeing this on ASM with Ubuntu 14, 16 and SUSE (so far) on CLI version 0.10.1

C:\Users\cynthn>azure vm extension set SUSEClassic VMAccessForLinux Microsoft.OSTCExtensions 1.* --private-config-path PrivateConf.json -v
info:    Executing command vm extension set
verbose: Getting virtual machines
verbose: Updating vm extension
error:   Parameter 'ConsoleScreenshotBlobUri' should not be set.
info:    Error information has been recorded to C:\Users\cynthn\.azure\azure.err
verbose: Error: Parameter 'ConsoleScreenshotBlobUri' should not be set.
    at Function.ServiceClient._normalizeError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1111:12)
error:   vm extension set command failed

**Comment by CraigWiand** [comment]
+1 @Squillace - there have been reports of ARM but I have only seen examples of ASM.  Support received a high severity issue with the same error today so this will be escalated through internal channels also.  It is worth noting that it appears to be reproducible with other updates to the VM when the `ConsoleScreenshotBlobUri` attribute is set, and not specific to just setting extensions.
