### ISSUE TITLE
Intermittent request timeouts against Azure China API

### ISSUE THREAD

**Issue by thomas1206** [Azure/azure-xplat-cli#2929]
CI operations intermittently encounter server timeouts when invoking the Azure CLI
 
```
{ [Error: The request timed out. Diagnostic information: timestamp '20160601T150001Z', subscription id '305c6e1b-01f7-4dec-a5f6-01ca4ec57f3e', tracking id 'ae3f6828-bd9a-48dd-aad5-2a80593e1f46', request correlation id 'ae3f6828-bd9a-48dd-aad5-2a80593e1f46'.]
  stack: [Getter/Setter],
  code: 'ServerTimeout',
  statusCode: 503,
  requestId: 'ae3f6828-bd9a-48dd-aad5-2a80593e1f46',
  __frame:
   { name: '__1',
     line: 57,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
     prev:
      { name: '__1',
        line: 46,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 10,
        col: 24 },
     calls: 0,
     active: false,
     offset: 2,
     col: 44 },
  rawStack: [Getter] }
Error: The request timed out. Diagnostic information: timestamp '20160601T150001Z', subscription id '305c6e1b-01f7-4dec-a5f6-01ca4ec57f3e', tracking id 'ae3f6828-bd9a-48dd-aad5-2a80593e1f46', request correlation id 'ae3f6828-bd9a-48dd-aad5-2a80593e1f46'.
 <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:59:45)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:56:25)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
``````

**Comment by eduardkoller** [comment]
Where are you running this from - where is the client geographically located?

**Comment by ahmetalpbalkan** [comment]
It would be better to open an incident internally, saying HTTP 503 at this date with this `x-ms-request-id`.

This is not an xplat-cli issue.
