### ISSUE TITLE
azure account import errors with "Invalid IV length"

### ISSUE THREAD

**Issue by molant** [Azure/azure-xplat-cli#2939]
CLI Version: **0.10.1**
OS Type: Win
Installation via:  npm
node version: 6.2.1

Mode: **ARM / ASM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
`azure account import credentials.publishsettings` command throws the following:
> info:    Executing command account import
error:   Invalid IV length
info:    Error information has been recorded to C:\Users\molant\.azure\azure.err
error:   account import command failed

Steps to reproduce:
1) Run `azure account import credentials.publishsettings`

Error stack trace:
```
2016-06-15T20:10:38.264Z:
{ Error: Invalid IV length
  <<< async stack >>>
  <<< raw stack >>>
    at Error (native)
    at new Decipheriv (crypto.js:232:16)
    at Object.Decipheriv (crypto.js:229:12)
    at Array.__dirname.PfxAlgorithmDecoder.self.on.elements.createCipher (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:274:23)
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:333:28)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
Error: Invalid IV length
  <<< async stack >>>
  <<< raw stack >>>
    at Error (native)
    at new Decipheriv (crypto.js:232:16)
    at Object.Decipheriv (crypto.js:229:12)
    at Array.__dirname.PfxAlgorithmDecoder.self.on.elements.createCipher (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:274:23)
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:333:28)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
```

I was using the version 0.9.x and node 5.x but I've recently updated to node 6.x so I upgraded the package and now I'm having this issue :/

**Comment by molant** [comment]
This also happens with node 6.0.0
Replacing `key` and `iv` in `lib\util\certificates\pkcs.js#274` with strings of 24 and 8 characters get me a bit further but still throw an error:
> info:    Executing command account import
error:   error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
info:    Error information has been recorded to C:\Users\molant\.azure\azure.err
error:   account import command failed

```
2016-06-15T21:29:30.018Z:
{ Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
  <<< async stack >>>
  <<< raw stack >>>
    at Error (native)
    at Decipheriv.Cipher.final (crypto.js:150:26)
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:335:24)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
    at PfxSafeBagDecoder.emit (events.js:188:7)
    at PfxSafeBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:52:10)
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
  <<< async stack >>>
  <<< raw stack >>>
    at Error (native)
    at Decipheriv.Cipher.final (crypto.js:150:26)
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:335:24)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
    at PfxSafeBagDecoder.emit (events.js:188:7)
    at PfxSafeBagDecoder.Decoder.parse (C:\Users\molant\AppData\Roaming\npm\node_modules\azure-cli\lib\util\certificates\der.js:52:10)
```

**Comment by gforghetti** [comment]
I'm getting the same error on OSX.

azure account import credentials.publishsettings
info:    Executing command account import
error:   Invalid IV length
info:    Error information has been recorded to /Users/gforghetti/.azure/azure.err
error:   account import command failed

node --version
v6.2.2

**Comment by Apoorv121** [comment]
Getting the same error on Ubuntu 

Installation via: npm
node version: 6.2.1

**Comment by Apoorv121** [comment]
Anyone has any updates on this?

**Comment by zilman** [comment]
+1

Pretty big show stopper right here.

**Comment by eduardkoller** [comment]
Investigating. /c @haocs

**Comment by JulienBlancher** [comment]
+1 same error on OSX, node 6.2.2

**Comment by haocs** [comment]
The fix for this issue is merged in our dev branch and will be included in our upcoming release(07/07). Please give it a shot and reopen this issue if necessary. 

To run cli from source code(dev branch by default):
```js
git clone git@github.com:Azure/azure-xplat-cli.git
cd azure-xplat-cli
npm install
// to run cli
node bin/azure <your_command>
```
