### ISSUE TITLE
Fail to create a storage account without specifying the location when logging in using a service principal

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2966]
CLI Version: **0.10.1**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**/**AzureChinaCloud** No specific env

Description:
`azure storage account create` command fail to create the storage account if the location is not specified and a service principal is used to login.

Steps to reproduce:
1) Login Azure CLI using a service principal
2) Run `azure storage account create <storage-account-name>` without specifying the location.

```
$ azure storage account create sdfx062802sasdfdsfd213
info:    Executing command storage account create
+ Checking availability of the storage account name
+ Getting SKU
help:    SKU Name:
  1) LRS
  2) ZRS
  3) GRS
  4) RAGRS
  5) PLRS
  : 1
|error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
-info:    Error information has been recorded to /home/azureuser/.azure/azure.err
error:   storage account create command failed
```

If I login Azure CLI not using a service principal (via https://aka.ms/devicelogin), the command works.

Error stack trace:

```
{ [Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.]
  stack: [Getter/Setter],
  code: 'ForbiddenError',
  statusCode: 403,
  __frame:
   { name: 'chooseIfNotGiven__4',
     line: 229,
     file: '/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js',
     prev:
      { name: 'validateAccountConfiguration',
        line: 102,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 32,
        col: 50 },
     calls: 0,
     active: false,
     offset: 3,
     col: 19 },
  rawStack: [Getter] }
Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
  <<< async stack >>>
  at chooseIfNotGiven__4 (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:232:20)
  at validateAccountConfiguration (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:134:51)
  at storageAccount_createCommand__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:555:5)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**Comment by bingosummer** [comment]
cc: @halimacc

**Comment by amarzavery** [comment]
@bingosummer - Can you login as Service Principal and execute the storage account create command with **-vv**. I think there might be a azure.details.err file in .azure folder in your home profile. Can you paste the content of that file.

**Comment by bingosummer** [comment]
@amarzavery 

```
2016-07-07T05:56:25.357Z - info:    Executing command storage account create
2016-07-07T05:56:25.559Z - verbose: Checking availability of the storage account name
2016-07-07T05:56:25.590Z - silly:   requestOptions
2016-07-07T05:56:25.595Z - silly:   {
2016-07-07T05:56:25.596Z - silly:       rawResponse: false,
2016-07-07T05:56:25.596Z - silly:       queryString: {},
2016-07-07T05:56:25.596Z - silly:       method: 'POST',
2016-07-07T05:56:25.596Z - silly:       headers: {
2016-07-07T05:56:25.596Z - silly:           x-ms-client-request-id: '80c1f818-b1de-4b0c-948d-e9763714b845',
2016-07-07T05:56:25.597Z - silly:           accept-language: 'en-US',
2016-07-07T05:56:25.597Z - silly:           user-agent: 'WindowsAzureXplatCLI/0.10.1',
2016-07-07T05:56:25.597Z - silly:           Content-Type: 'application/json; charset=utf-8'
2016-07-07T05:56:25.597Z - silly:       },
2016-07-07T05:56:25.597Z - silly:       url: 'https://management.chinacloudapi.cn/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx824e43b7-4be9-435e-8c2a-26493d7597aa/providers/Microsoft.Storage/checkNameAvailability?api-version=2016-01-01',
2016-07-07T05:56:25.597Z - silly:       body: '{"name":"binxi070701nolocation","type":"Microsoft.Storage/storageAccounts"}'
2016-07-07T05:56:25.597Z - silly:   }
2016-07-07T05:56:26.405Z - silly:   returnObject
2016-07-07T05:56:26.405Z - silly:   {
2016-07-07T05:56:26.406Z - silly:       statusCode: 200,
2016-07-07T05:56:26.406Z - silly:       header: {
2016-07-07T05:56:26.406Z - silly:           cache-control: 'no-cache',
2016-07-07T05:56:26.406Z - silly:           pragma: 'no-cache',
2016-07-07T05:56:26.406Z - silly:           content-length: '23',
2016-07-07T05:56:26.406Z - silly:           content-type: 'application/json',
2016-07-07T05:56:26.406Z - silly:           expires: '-1',
2016-07-07T05:56:26.406Z - silly:           x-ms-request-id: 'abb93b3d-29a2-4286-b40c-7966dc4d3520',
2016-07-07T05:56:26.407Z - silly:           server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
2016-07-07T05:56:26.407Z - silly:           x-ms-ratelimit-remaining-subscription-reads: '14998',
2016-07-07T05:56:26.407Z - silly:           x-ms-correlation-request-id: 'abb93b3d-29a2-4286-b40c-7966dc4d3520',
2016-07-07T05:56:26.407Z - silly:           x-ms-routing-request-id: 'CHINAEAST:20160707T055507Z:abb93b3d-29a2-4286-b40c-7966dc4d3520',
2016-07-07T05:56:26.407Z - silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
2016-07-07T05:56:26.409Z - silly:           date: 'Thu, 07 Jul 2016 05:55:07 GMT',
2016-07-07T05:56:26.409Z - silly:           connection: 'close'
2016-07-07T05:56:26.409Z - silly:       },
2016-07-07T05:56:26.409Z - silly:       body: '{"nameAvailable":true}\n'
2016-07-07T05:56:26.409Z - silly:   }
2016-07-07T05:56:26.415Z - verbose: Getting SKU
2016-07-07T05:56:26.416Z - help:    SKU Name:
2016-07-07T05:56:31.189Z - verbose: Getting locations
2016-07-07T05:56:31.191Z - silly:   requestOptions
2016-07-07T05:56:31.191Z - silly:   {
2016-07-07T05:56:31.192Z - silly:       rawResponse: false,
2016-07-07T05:56:31.192Z - silly:       queryString: {},
2016-07-07T05:56:31.192Z - silly:       method: 'GET',
2016-07-07T05:56:31.192Z - silly:       headers: { x-ms-version: '2014-10-01' },
2016-07-07T05:56:31.192Z - silly:       url: 'https://management.core.chinacloudapi.cn/xxxxxxxxxxxxxxxxxxxxxxxxxxx/locations'
2016-07-07T05:56:31.192Z - silly:   }
2016-07-07T05:56:31.958Z - silly:   returnObject
2016-07-07T05:56:31.958Z - silly:   {
2016-07-07T05:56:31.958Z - silly:       statusCode: 403,
2016-07-07T05:56:31.958Z - silly:       header: {
2016-07-07T05:56:31.958Z - silly:           content-length: '288',
2016-07-07T05:56:31.958Z - silly:           content-type: 'application/xml; charset=utf-8',
2016-07-07T05:56:31.959Z - silly:           server: 'Microsoft-HTTPAPI/2.0',
2016-07-07T05:56:31.959Z - silly:           date: 'Thu, 07 Jul 2016 05:55:13 GMT',
2016-07-07T05:56:31.959Z - silly:           connection: 'close'
2016-07-07T05:56:31.959Z - silly:       },
2016-07-07T05:56:31.959Z - silly:       body: '<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>'
2016-07-07T05:56:31.959Z - silly:   }
2016-07-07T05:56:31.962Z - error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
2016-07-07T05:56:31.967Z - silly:   {
2016-07-07T05:56:31.967Z - silly:       rawStack: 'Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.\n    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)\n    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29\n    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)\n    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)\n    at emitOne (events.js:82:20)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)',
2016-07-07T05:56:31.967Z - silly:       __frame: {
2016-07-07T05:56:31.967Z - silly:           name: 'chooseIfNotGiven__4',
2016-07-07T05:56:31.967Z - silly:           line: 229,
2016-07-07T05:56:31.967Z - silly:           file: '/usr/lib/node_modules/azure-cli/lib/util/interaction.js',
2016-07-07T05:56:31.968Z - silly:           prev: {
2016-07-07T05:56:31.968Z - silly:               name: 'validateAccountConfiguration',
2016-07-07T05:56:31.968Z - silly:               line: 102,
2016-07-07T05:56:31.968Z - silly:               file: '/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js',
2016-07-07T05:56:31.969Z - silly:               prev: {
2016-07-07T05:56:31.970Z - silly:                   name: 'storageAccount_createCommand__3',
2016-07-07T05:56:31.970Z - silly:                   line: 536,
2016-07-07T05:56:31.971Z - silly:                   file: '/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js',
2016-07-07T05:56:31.971Z - silly:                   prev: undefined,
2016-07-07T05:56:31.971Z - silly:                   calls: 2,
2016-07-07T05:56:31.971Z - silly:                   active: false,
2016-07-07T05:56:31.971Z - silly:                   offset: 19,
2016-07-07T05:56:31.971Z - silly:                   col: 4
2016-07-07T05:56:31.971Z - silly:               },
2016-07-07T05:56:31.971Z - silly:               calls: 2,
2016-07-07T05:56:31.972Z - silly:               active: false,
2016-07-07T05:56:31.972Z - silly:               offset: 32,
2016-07-07T05:56:31.972Z - silly:               col: 50
2016-07-07T05:56:31.972Z - silly:           },
2016-07-07T05:56:31.972Z - silly:           calls: 0,
2016-07-07T05:56:31.972Z - silly:           active: false,
2016-07-07T05:56:31.972Z - silly:           offset: 3,
2016-07-07T05:56:31.972Z - silly:           col: 19
2016-07-07T05:56:31.972Z - silly:       },
2016-07-07T05:56:31.972Z - silly:       stack: 'Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.\n  <<< async stack >>>\n  at chooseIfNotGiven__4 (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:232:20)\n  at validateAccountConfiguration (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:134:51)\n  at storageAccount_createCommand__3 (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:555:5)\n  <<< raw stack >>>\n    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)\n    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29\n    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)\n    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)\n    at emitOne (events.js:82:20)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)',
2016-07-07T05:56:31.973Z - silly:       code: 'ForbiddenError',
2016-07-07T05:56:31.973Z - silly:       message: 'The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.',
2016-07-07T05:56:31.973Z - silly:       statusCode: 403
2016-07-07T05:56:31.973Z - silly:   }
2016-07-07T05:56:32.718Z - info:    Error information has been recorded to /home/azureuser/.azure/azure.err
```

BTW, the role of the service principal is `Contributor`. Do I need any specific role to get the location?

**Comment by eduardkoller** [comment]
Thank you for the details. Looks like the command failed to retrieve the locations list. Investigating
