### ISSUE TITLE
Fail to import publish settings with error:   Invalid IV length

### ISSUE THREAD

**Issue by gavdraper** [Azure/azure-xplat-cli#2967]
CLI Version: 10.11.15
OS Type: Mac
Installation via:  npm

Description:
Have just done a clean instal via npm. Then downloaded the publish settings via the download option in "azure account download". 

If I then run

> azure account import Main-6-28-2016-credentials-2.publishsettings

I get 

> Error :  Invalid IV length

The stack trace below mentions no such file but it definitely does exist.

Error stack trace:

`2016-06-28T20:17:30.215Z:
{ Error: ENOENT: no such file or directory, open 'Main-6-28-2016-credentials-2.publishsettingvim'
  <<< async stack >>>
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at readFileContents (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:28:23)
    at Object.importPublishSettings [as import] (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:91:13)
    at Profile._.extend.importPublishSettings (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/profile.js:207:34)
    at __5 (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/commands/account.js:172:25)
  <<< raw stack >>>
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at readFileContents (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:28:23)
    at Object.importPublishSettings [as import] (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:91:13)
    at Profile._.extend.importPublishSettings (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/util/profile/profile.js:207:34)
    at __$__5 (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/lib/commands/account.js:172:25)
    at __func (/Users/gavdraper/.npm-packages/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)`

**Comment by haocs** [comment]
duplicated https://github.com/Azure/azure-xplat-cli/issues/2939
