### ISSUE TITLE
Uploading a VM disk image with vm image create, results in error

### ISSUE THREAD

**Issue by neeohw** [Azure/azure-xplat-cli#2972]
CLI Version: 0.10.1
OS Type: Mac / Linux (Ubuntu)
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
`azure vm image create` crashes when uploading.

Steps to reproduce:
1) Run `azure vm image create <ImageName> -u <blob-url> --os Linux <path-to-vhd>`

Error stack trace:

2016-06-29T12:09:06.159Z:
[TypeError: body.outputStream.on is not a function]
TypeError: body.outputStream.on is not a function
    at /opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:444:35
    at /opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:573:5
    at SharedKey.signRequest (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/signing/sharedkey.js:199:3)
    at BlobService.StorageServiceClient._buildRequestOptions (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:555:27)
    at operation (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:275:10)
    at /opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:483:9
    at BlobService.filter (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:855:7)
    at BlobService.StorageServiceClient._performRequest (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:466:8)
    at BlobService.StorageServiceClient.performRequestOutputStream (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:206:8)
    at BlobService._createPages (/opt/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/services/blob/blobservice.js:4749:10)
Maartens-MacBook-Pro-2:graylog-vhd mvergouwe$

**Comment by huangpf** [comment]
This is a known issue, and it's ASM.

**Comment by neeohw** [comment]
Great! Now where is this known issue?

**Comment by anuchandy** [comment]
@neeohw please use https://github.com/Microsoft/azure-vhd-utils to upload your vhd to azure.

**Comment by avs099** [comment]
duplicate of #2230 - you can't use dynamic VHDs for now, only fixed
