### ISSUE TITLE
error - Cannot find WebSpace with name westuswebspace

### ISSUE THREAD

**Issue by GeoffreyEmery** [Azure/azure-xplat-cli#2987]
CLI Version: 0.10
OS Type: Win 
Installation via:  npm 

Mode: **ARM / ASM**

Environment: AzureCloud 

Description:
info:    Executing command site create
+ Getting sites
error:   Cannot find WebSpace with name westuswebspace.
info:    Error information has been recorded to C:\Users\{user}\.azure\azure.err
error:   site create command failed
Steps to reproduce:
1) azure site create {sitename}
2) first time you login it runs ok... 
3) now delete that site and run command again. `

Error stack trace:
`2016-07-05T04:20:41.767Z:
{ [Error: Cannot find WebSpace with name westuswebspace.]
  stack: [Getter/Setter],
  code: 'NotFound',
  extendedcode: '51004',
  messagetemplate: 'Cannot find {0} with name {1}.',
  parameters: 
   { '$': { 'xmlns:a': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
     'a:string': [ 'WebSpace', 'westuswebspace' ] },
  innererrors: { '$': { 'i:nil': 'true' } },
  statusCode: 404,
  __frame: 
   { name: '__1',
     line: 458,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\websites\\websitesclient.js',
     prev: 
      { name: 'getSites__7',
        line: 446,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\websites\\websitesclient.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 11,
        col: 25 },
     calls: 0,
     active: false,
     offset: 1,
     col: 35 },
  rawStack: [Getter] }
Error: Cannot find WebSpace with name westuswebspace.
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\websites\websitesclient.js:459:36)
  at getSites__7 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\websites\websitesclient.js:457:26)
  at determineIfSiteAndSlotExists (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\site.js:282:30)
  at __4 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\site.js:229:11)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1111:12)
`
**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by GeoffreyEmery** [comment]
Linking to another issue last year looks like same problem
https://github.com/Azure/azure-xplat-cli/issues/1646

**Comment by GeoffreyEmery** [comment]
the burning the azure file as listed in previous bug here: https://github.com/Azure/azure-xplat-cli/issues/1646 did not work for me

**Comment by GeoffreyEmery** [comment]
if i logout of my command prompt and close all the command windows and shut down all the browser then restart everything it works again

**Comment by eduardkoller** [comment]
Investigating
