### ISSUE TITLE
CLI does not support transparent proxies (or configured CAfile)

### ISSUE THREAD

**Issue by zollman** [Azure/azure-xplat-cli#2990]
CLI Version: 0.10.1 (node: 0.12.2)
OS Type: Mac 
Installation via:  npm

Mode: ASM (but really anything will do)

Environment: Azure Cloud

Description:
azure cli does not work through transparent SSL-terminating proxies. These proxies are commonly used in highly-regulated industries (PCI, financial services, education, health care) to protect a network perimeter. 

Because an SSL-terminating proxy, by definition, presents certificates that aren't in a public, trusted root, users of these proxies will provision the proxy's SSL certificate to the system trust store. 

However, NodeJS does not respect the system trust stores -- see https://github.com/nodejs/node/issues/4175 . Any individual project can configure a cafile (e.g. https://github.com/bnoordhuis/node-gyp/commit/8c4b0ffa503aa385f4186e028542dcedca2efeee or npm itself https://docs.npmjs.com/misc/config#cafile).

Ideally you'd add a cacert configuration option, change the azure CLI to respect system truststores (since you're using system storage for credentials), or -- even better -- submit an upstream patch to close https://github.com/nodejs/node/issues/4175 ).

Steps to reproduce:
1. Set up a transparent SSL proxy, perhaps http://docs.mitmproxy.org/en/latest/transparent/osx.html
2. Run any azure command (e.g. azure login)

Error stack trace:

- Authenticating...Tue, 05 Jul 2016 18:05:33 GMT:af9a4388-bfa5-417d-979f-303303521d86 - Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.com/common
Tue, 05 Jul 2016 18:05:33 GMT:af9a4388-bfa5-417d-979f-303303521d86 - Authority: VERBOSE: Performing static instance discovery
Tue, 05 Jul 2016 18:05:33 GMT:af9a4388-bfa5-417d-979f-303303521d86 - Authority: VERBOSE: Authority validated via static instance discovery.
Tue, 05 Jul 2016 18:05:33 GMT:af9a4388-bfa5-417d-979f-303303521d86 - DeviceCodeRequest: INFO: Getting user code info.
-Tue, 05 Jul 2016 18:05:37 GMT:af9a4388-bfa5-417d-979f-303303521d86 - OAuth2Client: ERROR: Get Device Code  request failed with
Stack:
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
{ [Error: self signed certificate in certificate chain] code: 'SELF_SIGNED_CERT_IN_CHAIN' }
+
error:   self signed certificate in certificate chain
info:    Error information has been recorded to /Users/home/.azure/azure.err
error:   login command failed

**Comment by eduardkoller** [comment]
Investigating adding an -ca option

**Comment by andrefernandes** [comment]
This turned out to be a roadblock for me as well. I usually solve the issue with my proxy on npm with:

`npm config set cafile /etc/certs/bacen/bacen_raiz.pem -g`

...but Azure CLI ignores it.

**Comment by amarzavery** [comment]
@zollman @andrefernandes - with new version of node.js [v4.8.0](https://nodejs.org/dist/latest-v4.x/), (documentation over [here](https://nodejs.org/docs/latest-v4.x/api/all.html#cli_node_extra_ca_certs_file)) you can set the following environment variable: `set NODE_EXTRA_CA_CERTS=<path-to-pem-file>` and run the commands. This should work fine.

**Comment by Anshapar** [comment]
I tried with self-signed certificate and got the following error:

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))


I tried to follow the steps mentioned in the comments @amarzavery but the error still persists.

**Comment by amarzavery** [comment]
What is the version of node.js on your system. (node -v) ?

Moreover I would suggest to use CLI 2.0,the recommended CLI for ARM commands. GitHub.com/Azure/azure-cli

**Comment by Anshapar** [comment]
@amarzavery node.js version is 4.8.0. And I am using CLI 2.0 and I am using the same commands as mentioned in the referral link in the github page, but still the error persists. Is there any other workaround to add self signed certificate for azure cli and what should be the ideal version of node.js and npm?

**Comment by amarzavery** [comment]
Couple of things:
1. It would be best to use the latest LTS version of node.js, which at present is 8.9.1 (https://nodejs.org/en/). If you are using a linux flavor then please follow the instructions over [here](https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager) for installing node.js

2. The problem that you are seeing is a node.js problem. CLI 2.0 is written in python. So it should definitely not have this problem. If you see similar problems with CLI 2.0 then you should file an issue over there (https://github.com/azure/azure-cli). FYI, CLI 2.0 commands start with `az` and not `azure`, just FYI incase you mistook CLI 1.0 as the new CLI.

**Comment by Anshapar** [comment]
@amarzavery I tried to install node.js with the commands mentioned in the link you mentioned but when I am trying to run the command node -v to check the version, I am getting following error:

bash: /usr/local/bin/node: No such file or directory
Also I am running the commands with az and not with azure.

**Comment by Anshapar** [comment]
@amarzavery I have reinstalled azure cli with node.js version 8.9.1 and tried setting up the environment variable but the value is not setting up. I tried to print the value of the variable after setting it and it is coming as empty. Can you help with this one as it is urgent for me?

I tried to run the command "az login" and got the following error:

"az login
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))"

**Comment by amarzavery** [comment]
@Anshapar - You are clearly not getting it. 
The CLI 2.0 is written in `python`. It has got nothing to do with `node.js`. Please file an issue over here - https://github.com/azure/azure-cli.

Does that make sense?

**Comment by yugangw-msft** [comment]
@Anshapar, like @amarzavery mentioned, please do not use this repository to report CLI 2.0 issue. Also, please check out [installation guide](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) to ensure you have right dependencies configured, which is very different from 1.0
