### ISSUE TITLE
AzureStack Login Error

### ISSUE THREAD

**Issue by tasquith** [Azure/azure-xplat-cli#2994]
CLI Version: **0.10.1**
OS Type: Linux (CentOS 7)
Installation via:  npm

Mode: ARM

Environment: Azure Stack

Description:
I can't seem to connect to AzureStack, despite my user being the owner of a subscription. Is this a known error?

Steps to reproduce:
1) Add AzureStack environment
2) azure login -e AzureStack -u "xxxxxx"

Error stack trace:

```
[centos@ImdClientCentos packer-azure]$ vi /home/centos/.azure/azure.err
2016-07-07T09:54:33.970Z:
{ [Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE]
  stack: [Getter/Setter],
  warnToUserInteractive: true,
  __frame:
   { name: '__1',
     line: 49,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 64,
     col: 27 },
  rawStack: [Getter] }
Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login.js:113:28)
  <<< raw stack >>>
    at Logger.createError (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:201:13)
    at WSTrustResponse.parse (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-response.js:278:23)
    at WSTrustRequest._handleRSTR (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:187:21)
    at /usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:228:12
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:137:5)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
```
If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).
```
azure login -e AzureStack -u "tom.asquith@live.co.uk"
info:    Executing command login
Password: **********
- Authenticating...Thu, 07 Jul 2016 09:51:07 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - Authority: VERBOSE: Performing instance discovery: https://login.windows.net/common
Thu, 07 Jul 2016 09:51:07 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - Authority: VERBOSE: Performing static instance discovery
Thu, 07 Jul 2016 09:51:07 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - Authority: VERBOSE: Authority validated via static instance discovery.
Thu, 07 Jul 2016 09:51:07 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - TokenRequest: INFO: Acquiring token with username password
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - CacheDriver: VERBOSE: finding with query:{"clientId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","userId":"tom.asquith@live.co.uk"}
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - CacheDriver: VERBOSE: Looking for potential cache entries:
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - CacheDriver: VERBOSE: {"_clientId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","userId":"tom.asquith@live.co.uk"}
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - CacheDriver: VERBOSE: Found 0 potential entries.
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - TokenRequest: VERBOSE: No appropriate cached token found.
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE: Performing user realm discovery at: https://login.windows.net/common/UserRealm/tom.asquith%40live.co.uk?api-version=1.0
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: INFO: User Realm DiscoveryServer returned this correlationId: f6cc3997-e819-4d97-95bf-68d68e67ece0
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE: Discovery response:
{"ver":"1.0","account_type":"Federated","domain_name":"live.com","federation_protocol":"WSTrust","federation_metadata_url":"","federation_active_auth_url":"https://login.live.com/rst2.srf","cloud_instance_name":"microsoftonline.com"}
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE: UserRealm response:
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE:  AccountType:             federated
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE:  FederationProtocol:      wstrust
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE:  FederationMetatdataUrl:
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - UserRealm: VERBOSE:  FederationActiveAuthUrl: https://login.live.com/rst2.srf
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - TokenRequest: VERBOSE: Acquiring token with username password for federated user
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - TokenRequest: WARNING: Unable to retrieve federationMetadataUrl from AAD.  Attempting fallback to AAD supplied endpoint.
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - TokenRequest: VERBOSE: Wstrust endpoint version is: wstrust2005
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - WSTrustRequest: VERBOSE: Created RST:
<s:Envelope xmlns:s='http://www.w3.org/2003/05/soap-envelope' xmlns:wsa='http://www.w3.org/2005/08/addressing' xmlns:wsu='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'>      <s:Header>        <wsa:Action s:mustUnderstand='1'>http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue</wsa:Action>        <wsa:messageID>urn:uuid:921c3706-5835-415d-bfbc-52ce960ef5c0</wsa:messageID>        <wsa:ReplyTo>          <wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address>        </wsa:ReplyTo>        <wsa:To s:mustUnderstand='1'>https://login.live.com/rst2.srf</wsa:To>        <wsse:Security s:mustUnderstand='1' xmlns:wsse='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'>    <wsu:Timestamp wsu:Id='_0'>      <wsu:Created>2016-07-07T09:51:08.157Z</wsu:Created>      <wsu:Expires>2016-07-07T10:01:08.157Z</wsu:Expires>    </wsu:Timestamp>    <wsse:UsernameToken wsu:Id='ADALUsernameToken'>      <wsse:Username>{UsernamePlaceHolder}</wsse:Username>      <wsse:Password>{PasswordPlaceHolder}</wsse:Password>    </wsse:UsernameToken>    </wsse:Security>      </s:Header>      <s:Body>        <wst:RequestSecurityToken xmlns:wst='http://schemas.xmlsoap.org/ws/2005/02/trust'>          <wsp:AppliesTo xmlns:wsp='http://schemas.xmlsoap.org/ws/2004/09/policy'>            <wsa:EndpointReference>              <wsa:Address>urn:federation:MicrosoftOnline</wsa:Address>            </wsa:EndpointReference>          </wsp:AppliesTo>          <wst:KeyType>http://schemas.xmlsoap.org/ws/2005/05/identity/NoProofKey</wst:KeyType>          <wst:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</wst:RequestType>        </wst:RequestSecurityToken>      </s:Body>    </s:Envelope>
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - WSTrustRequest: VERBOSE: Sending RST to: https://login.live.com/rst2.srf
/Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - WSTrustResponse: VERBOSE: RSTR Response: <?xml version="1.0" encoding="utf-8" ?><S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><S:Body><S:Fault><S:Code><S:Value>S:Sender</S:Value><S:Subcode><S:Value>wst:InvalidRequest</S:Value></S:Subcode></S:Code><S:Reason><S:Text xml:lang="en-US">Invalid Request</S:Text></S:Reason><S:Detail><psf:error><psf:value>0x8004882b</psf:value><psf:internalerror><psf:code>0x80045c19</psf:code><psf:text>STS partner do not have a certificate provisioned.&#x000D;&#x000A;</psf:text></psf:internalerror></psf:error></S:Detail></S:Fault></S:Body></S:Envelope>
Thu, 07 Jul 2016 09:51:08 GMT:f6cc3997-e819-4d97-95bf-68d68e67ece0 - WSTrustResponse: ERROR: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
Stack:
Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
    at Logger.createError (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:201:13)
    at WSTrustResponse.parse (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-response.js:278:23)
    at WSTrustRequest._handleRSTR (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:187:21)
    at /usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/wstrust-request.js:228:12
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:137:5)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
[Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE]
```

**Comment by tasquith** [comment]
issue was authenticating with a microsoft account rather than an organisational account. Closing.
