### ISSUE TITLE
Parameters file parsing error (`Unexpected token c`) when attempting to update existing vmss

### ISSUE THREAD

**Issue by jpoon** [Azure/azure-xplat-cli#3092]
CLI Version: 0.10.3
OS Type: Mac 
Installation via:  npm 

Mode: ARM

Environment: AzureCloud

Description:
Moved from https://github.com/Azure/azure-cli/issues/566. 
_Tldr;_ Deployed a Kubernetes cluster using the [official guide](http://kubernetes.io/docs/getting-started-guides/azure/) and am trying to externally expose the VMSS in the cluster via a load balancer I manually added through the portal. Now attempting to add the NICs to the LB's  backend address pool as advised by https://github.com/colemickens/azkube/issues/11. 

Steps to reproduce:

1. Generate parameter file from existing VMSS: 
`azure vmss show --json -g <my_resource_group> -n <my_vmss_name> > config.json`
2. Updated parameter file adding backend pools: 
`azure vmss config load-balancer-backend-address-pools set --parameter-file config.json --index 0 --ip-configurations-index 0 --network-interface-configurations-index 0 --value "test"`
3. Update existing VMSS: 
`azure vmss create -p config.json -g <my_resource_group> -n <my_vmss_name>`

Here is the [parameters file](https://gist.github.com/jpoon/aa4e2dc06fb66ed1b466b07634a71288) I am using. 

I get the _same_ parsing error when:
* using an unmodified parameters file (e.g. skipping step 2 above) 
* an empty parameters file (e.g. `azure vmss config create`)
* when my parameters file just contains `{}`

Error stack trace:

```
2016-08-12T01:38:49.131Z:
{ [SyntaxError: Unexpected token c]
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
SyntaxError: Unexpected token c
  <<< async stack >>>
    at Object.parse (native)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:760:34)
  <<< raw stack >>>
    at Object.parse (native)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:760:34)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:748:164)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:748:180)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:743:190)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:743:206)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/compute/virtualMachineScaleSets.js:733:879)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/cli.js:223:12)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
```

**Comment by jpoon** [comment]
Argh. The argument needs to be `--parameter-file`
