### ISSUE TITLE
Issue with ASM mode hdinsight.

### ISSUE THREAD

**Issue by bbetstcw** [Azure/azure-xplat-cli#3121]
When I run hdinsight command in ASM mode, I always get the following error.

	info:    Executing command hdinsight cluster list
	verbose: Getting HDInsight servers
	error:   Cannot read property 'showAsmDeprecationWarning' of undefined
	silly:   {
	silly:       __frame: {
	silly:           name: 'listClustersCommand__3',
	silly:           line: 377,
	silly:           file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js',
	silly:           prev: undefined,
	silly:           calls: 1,
	silly:           active: false,
	silly:           offset: 2,
	silly:           col: 32
	silly:       },
	silly:       message: "Cannot read property 'showAsmDeprecationWarning' of undefined",
	silly:       rawStack: "TypeError: Cannot read property 'showAsmDeprecationWarning' of undefined\n    at __$listClusters__7 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:209:16)\n    at __func (C:
	\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\streamline\\lib\\callbacks\\runtime.js:47:5)\n    at listClusters__7 [as listClusters] (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.j
	s:208:150)\n    at __$listClustersCommand__3 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:379:29)\n    at __func (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\streamline\\li
	b\\callbacks\\runtime.js:47:5)\n    at AzureCli.listClustersCommand__3 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:377:166)\n    at AzureCli.<anonymous> (C:\\Program Files (x86)\\Microsoft SDKs\
	\Azure\\CLI\\lib\\cli.js:223:12)\n    at AzureCli.<anonymous> (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\commander\\lib\\commander.js:235:8)\n    at emitTwo (events.js:87:13)\n    at AzureCli.emit (events.js:172:
	7)",
	silly:       stack: "TypeError: Cannot read property 'showAsmDeprecationWarning' of undefined\n  <<< async stack >>>\n    at listClusters__7 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:209:16)\n
	  at listClustersCommand__3 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:379:33)\n  <<< raw stack >>>\n    at __$listClusters__7 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\command
	s\\asm\\hdinsight.js:209:16)\n    at __func (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\streamline\\lib\\callbacks\\runtime.js:47:5)\n    at listClusters__7 [as listClusters] (C:\\Program Files (x86)\\Microsoft SD
	Ks\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:208:150)\n    at __$listClustersCommand__3 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:379:29)\n    at __func (C:\\Program Files (x86)\\Microsoft
	 SDKs\\Azure\\CLI\\node_modules\\streamline\\lib\\callbacks\\runtime.js:47:5)\n    at AzureCli.listClustersCommand__3 (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\hdinsight.js:377:166)\n    at AzureCli.<anony
	mous> (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\cli.js:223:12)\n    at AzureCli.<anonymous> (C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\node_modules\\commander\\lib\\commander.js:235:8)\n    at emitTwo (events.
	js:87:13)\n    at AzureCli.emit (events.js:172:7)"
	silly:   }
	error:   Error information has been recorded to C:\Users\v-dazen\.azure\azure.err
	verbose: TypeError: Cannot read property 'showAsmDeprecationWarning' of undefined
	  <<< async stack >>>
		at listClusters__7 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:209:16)
	  at listClustersCommand__3 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:379:33)
	  <<< raw stack >>>
		at __$listClusters__7 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:209:16)
		at __func (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:47:5)
		at listClusters__7 [as listClusters] (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:208:150)
		at __$listClustersCommand__3 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:379:29)
		at __func (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:47:5)
		at AzureCli.listClustersCommand__3 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\hdinsight.js:377:166)
		at AzureCli.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\cli.js:223:12)
		at AzureCli.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\commander\lib\commander.js:235:8)
		at emitTwo (events.js:87:13)
		at AzureCli.emit (events.js:172:7)
	error:   hdinsight cluster list command failed

I am running 0.10.3. If I roll back to 0.9.20, everything is good.

**Comment by amarzavery** [comment]
@bbetstcw - We will be removing support for HDINSIGHT commands in ASM mode by the end of the year. I would recommend you to use the HDINSIGHT commands in ARM mode (azure config mode arm)
azure hdinsight -h

**Comment by bbetstcw** [comment]
Hi, @amarzavery - that is not a option for me, because I am using Azure China, and ARM HDInsight is not available in Azure China yet.
