### ISSUE TITLE
Azure Account Keys with forward slash (/) does not work with CLI

### ISSUE THREAD

**Issue by dstolts** [Azure/azure-xplat-cli#3135]
CLI Version: **0.9.X**
OS Type:  Linux (Ubuntu 14, latest 14 build on new portal)

Installation via:  npm 

Mode: **ARM 

Environment: **AzureCloud**

Description:
azure storage account keys list command will output the AccountKey but if the AccountKey has a forward slash (/) in it, the character gets stripped out by bash when setting it to a variable. 

This is a standard "feature" of bash so the AccountKey should not use a forward slash (/)
reproduce in bash.. 
echo "abc/123"
myTest="abc/123"
echo $myTest
myTest="abc//123"
echo $myTest
Notice that the forward slashes are automatically converted to spaces.  This also happens with the output from an Azure AccountKey or other Key.
![azure cli accountkey with forward slash character](https://cloud.githubusercontent.com/assets/7460856/18224409/01c8d69a-71a2-11e6-93e8-365e4ae4a6b0.png)

Steps to reproduce:
1) Using an account that has a forward slash in the AccountKey Run 
$DEST_CONN=$(azure storage account connectionstring show --resource-group $resourceGroupName $storageAccountName --json | jq '. | .string' | sed -e 's/^"//' -e 's/"$//')
echo $DEST_CONN
2) echo $DEST_CONN
3) run 
azure storage account connectionstring show --resource-group $resourceGroupName $storageAccountName --json | jq '. | .string' | sed -e 's/^"//' -e 's/"$//'
4) Note that the variable $DEST_CONN does not have the full AccountKey (it is truncated at the forward slash)
5) run azure storage container create -c $DEST_CONN $DEST_CONTAINER
Note that it will fail because the AccountKey is truncated

Error stack trace:

guruadmin@ubuntu16:~/azure_vm_deployment/Archive$ azure storage container create -c $DEST_CONN $DEST_CONTAINER
info:    Executing command storage container create
error:   The provided account key 0M0YSDIh5dWtStcwVCIJvMsNIqkqFc5 is not a valid base64 string.
error:   Error information has been recorded to /home/guruadmin/.azure/azure.err
error:   storage container create command failed
p
**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

2016-09-03T10:51:21.224Z:
{ [SyntaxError: The provided account key 0M0YSDIh5dWtStcwVCIJvMsNIqkqFc5 is not a valid base64 string.]
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
SyntaxError: The provided account key 0M0YSDIh5dWtStcwVCIJvMsNIqkqFc5 is not a valid base64 string.
  <<< async stack >>>
  <<< raw stack >>>
    at exports.isBase64Encoded (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/validate.js:152:11)
    at Array.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/servicesettings.js:137:25)
    at Object.exports.matchedSpecification (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/servicesettings.js:250:54)
    at Function.StorageServiceSettings.createFromSettings (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageservicesettings.js:196:34)
    at Function.StorageServiceSettings.createFromConnectionString (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageservicesettings.js:114:35)
    at StorageServiceClient.getStorageSettings (/usr/local/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/services/storageserviceclient.js:784:53)
    at adjustConnectionStringWithEnvironment (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util.js:1540:7)
    at getStorageServiceSettings (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util.js:1457:24)
    at StorageUtil.getBlobService (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util.js:364:25)
    at Object.StorageUtil.getServiceClient (/usr/local/lib/node_modules/azure-cli/lib/util/storage.util.js:787:23)

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by dstolts** [comment]
Additional research shows that about 80% of the storage account keys have at least one forward slash in them.  Here is a script that allows you to run repeatedly to create storage accounts and check the key...

athena_user="dls"
resourceGroupName="MITClassRG8"
#Create UniqueID
azUniqueId=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 12 | head -n 1)
azUniqueName="${athena_user}${azUniqueId}" 
export AZURE_UNIQUE_ID=$azUniqueName
echo "UniqueID: "$azUniqueName
# DEBUG then you can test it with...
#   (azure storage account check -v $azUniqueName) 

#Create resource group
resourceLocation="eastus2"
echo "Creating a new resource group... '$resourceGroupName' '$resourceLocation'" 
azure group create --name $resourceGroupName --location $resourceLocation

# create the storage account if it doesn't exist
storageAccountName=$azUniqueName"stor"
echo $storageAccountName 
DEST_CONTAINER="studentimage"
a=$(azure storage account show -g $resourceGroupName $storageAccountName --json | jq ".name")
if [[ -z $a ]]; then
   echo 'create Storage account'
   azure storage account create \
      --location $resourceLocation \
	  --sku-name "LRS" \
	  --resource-group $resourceGroupName \
	  --kind "Storage" \
	  $storageAccountName
      azure storage account keys list -g $resourceGroupName $storageAccountName
fi

**Comment by amarzavery** [comment]
@hasonmsft @vincentjiang - Please take a look at this issue.

**Comment by hasonmsft** [comment]
@dstolts , I cannot repro this issue. I'm running on: 

Linux 4.4.0-36-generic x86_64
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)

**Comment by dstolts** [comment]
Do you have a slash in your account ID?  If not, you would not be able to reproduce it.  It only happens in cases where there happens to be a forward slash in the accountID field.

Happy to work with you using my account so you can see it.

**Comment by hasonmsft** [comment]
@dstolts , you mean having slash in account key, right? My account has several slashes. 

Test the simple repro steps you provided above and here is my result: 
```
echo "abc/123"
=>   abc/123

myTest="abc/123"
echo $myTest
=> abc/123

myTest="abc//123"
=> abc//123
```

**Comment by dstolts** [comment]
Interesting.  Will look at it closer.
