### ISSUE TITLE
Azure login device flow does not work for AzureGermanCloud

### ISSUE THREAD

**Issue by n01d** [Azure/azure-xplat-cli#3137]
CLI Version: **0.10.1 (node: 4.2.4)**
OS Type: Win
Installation via:  win-or-mac installer

Mode: **ARM / ASM**

Environment: Blackforest / AzureGermanCloud

Description:
'azure login -e AzureGermanCloud' fails without a meaningful error. Simimar to 
https://github.com/Azure/azure-xplat-cli/issues/2357. There should be a meaningful error message if the feature is not deployed yet.

info:    Executing command login
- Authenticating...
  error:   wireResponse is missing expires_in
  info:    Error information has been recorded to C:\Users\malantin.azure\azure.err
  error:   login command failed

Steps to reproduce:
1) run 'azure login -e AzureGermanCloud'

Error stack trace:

.azure\azure.err:

2016-09-05T14:12:29.745Z:
{ [Error: wireResponse is missing expires_in]
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 49,
     file: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 64,
     col: 27 },
  rawStack: [Getter] }
Error: wireResponse is missing expires_in
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:113:28)
  <<< raw stack >>>
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:201:13)
    at OAuth2Client._validateDeviceCodeResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:319:23)
    at OAuth2Client._handleGetDeviceCodeResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:392:33)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\oauth2client.js:521:16
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:137:5)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1036:10)
    at emitOne (events.js:82:20)

**Comment by amarzavery** [comment]
sure we will provide a better error message.
/cc @mayurid, @yugangw-msft - FYI, A scenario to be handled in py.

**Comment by bingosummer** [comment]
@n01d Does it work now? Just out of curiosity.

**Comment by amarzavery** [comment]
Closing this issue in favor of #3391
