### ISSUE TITLE
[OSX] utils.format is not a function

### ISSUE THREAD

**Issue by yshahin** [Azure/azure-xplat-cli#3145]
CLI Version: **0.10.3**
OS Type: Mac
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
When trying to delete an auto scaling rule on a cloud service I get this error

info:    Executing command insights autoscale setting delete
error:   utils.format is not a function
error:   Error information has been recorded to <location>
error:   insights autoscale setting delete command failed

Steps to reproduce:
1) Run `azure insights autoscale setting delete <RG> <Name>`

Error stack trace:

2016-09-07T19:29:05.903Z:
{ TypeError: utils.format is not a function
  <<< async stack >>>
    at insightsAutoscaleSettingCommand__executeDeleteCmd__8 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:281:49)
  at insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:93:10)
  at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:45:39)
  <<< raw stack >>>
    at __$insightsAutoscaleSettingCommand__executeDeleteCmd__8 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:281:49)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.insightsAutoscaleSettingCommand__executeDeleteCmd__8 [as _executeDeleteCmd] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:280:289)
    at __$insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:93:21)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 [as _prepareAndExecuteDelete] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:82:304)
    at __$__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:45:46)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:39:434)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/cli.js:223:12)
  stack: [Getter/Setter],
  __frame: 
   { name: 'insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5',
     line: 82,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js',
     prev: 
      { name: '__2',
        line: 44,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 1,
        col: 38 },
     calls: 1,
     active: false,
     offset: 11,
     col: 9 },
  rawStack: [Getter] }
TypeError: utils.format is not a function
  <<< async stack >>>
    at insightsAutoscaleSettingCommand__executeDeleteCmd__8 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:281:49)
  at insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:93:10)
  at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:45:39)
  <<< raw stack >>>
    at __$insightsAutoscaleSettingCommand__executeDeleteCmd__8 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:281:49)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.insightsAutoscaleSettingCommand__executeDeleteCmd__8 [as _executeDeleteCmd] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:280:289)
    at __$insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:93:21)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 [as _prepareAndExecuteDelete] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:82:304)
    at __$__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:45:46)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:39:434)
    at AzureCli.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/cli.js:223:12)

**Comment by amarzavery** [comment]
@gucalder - Can you take a look at this issue?

**Comment by goodwill** [comment]
+1, come across this today as well
