### ISSUE TITLE
[ARM]: SSH2 and RSA public keys in .pem files fail with vm quick-create

### ISSUE THREAD

**Issue by vlivech** [Azure/azure-xplat-cli#3230]
CLI Version: 0.10.2
OS Type: Mac
Installation via:  brew

Mode: ARM

Environment: AzureCloud

Description:
`azure vm quick-create` errors out when using SSH2 or RSA public keys in .pem format

Steps to reproduce:
SSH2
```
azure vm quick-create -g rbg sshkeytest -l westus -y Linux -Q Debian -u chrisl -M id_rsa_ssh2.pem
info:    Executing command vm quick-create
+ Listing virtual machine sizes available in the location "westus"
+ Looking up the VM "sshkeytest"
info:    Verifying the public key SSH file: id_rsa_ssh2.pem
error:   Specified SSH certificate is not in PEM or SSH RSA format
error:   Error information has been recorded to /Users/spudbud/.azure/azure.err
error:   vm quick-create command failed
```

```
cat id_rsa_ssh2.pem
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "2048-bit RSA, converted by spudbud@smallsmacbookspros.local "
AAAAB3NzaC1yc2EAAAADAQABAAABAQCV45zL6maw6quAl/aGwjs9vu3IAkc/mQrlDB//6e
LFjDTV1u9UijsVs4bTJZrLzr20tJ14/4BOW5dZQksxZrvMMAshAlpyxplqOU0m3cRlOjyG
e57+Nn9P8oGc8UKaLRs1kAn+UAMfy1Ioy4fUQt8Estpyx2pHyiO2IwgVifov+5r2Veg9jX
QXu3BzSZyzam2lrVJccyF+r/fZyjwkgDVxcytYoBlaNXhgmbQVMwcaM9L+0L3yZi+JYyTE
bWgemr7CZt9ZXbjRjmc8nse9bcdd0yeoE1AyRCKBzPAx6MKPYVUIcyNupUhM92mxdrfEqR
jCLHgBIQB1B8VdehIhWwX7
---- END SSH2 PUBLIC KEY ----
```

RSA
```
azure vm quick-create -g rbg sshkeytest -l westus -y Linux -Q Debian -u chrisl -M id_rsa_pem.pem
info:    Executing command vm quick-create
+ Listing virtual machine sizes available in the location "westus"
+ Looking up the VM "sshkeytest"
info:    Verifying the public key SSH file: id_rsa_pem.pem
error:   Specified SSH certificate is not in PEM or SSH RSA format
error:   Error information has been recorded to /Users/spudbud/.azure/azure.err
error:   vm quick-create command failed
```

```
cat id_rsa_pem.pem
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAleOcy+pmsOqrgJf2hsI7Pb7tyAJHP5kK5Qwf/+nixYw01dbvVIo7
FbOG0yWay869tLSdeP+ATluXWUJLMWa7zDALIQJacsaZajlNJt3EZTo8hnue/jZ/
T/KBnPFCmi0bNZAJ/lADH8tSKMuH1ELfBLLacsdqR8ojtiMIFYn6L/ua9lXoPY10
F7twc0mcs2ptpa1SXHMhfq/32co8JIA1cXMrWKAZWjV4YJm0FTMHGjPS/tC98mYv
iWMkxG1oHpq+wmbfWV240Y5nPJ7HvW3HXdMnqBNQMkQigczwMejCj2FVCHMjbqVI
TPdpsXa3xKkYwix4ASEAdQfFXXoSIVsF+wIDAQAB
-----END RSA PUBLIC KEY-----
```

Error stack trace:
```
cat ~/.azure/azure.err
2016-10-06T18:07:58.956Z:
{ Error: Specified SSH certificate is not in PEM or SSH RSA format
  <<< async stack >>>
    at VMOSProfile.__.extend._parseSSHPublicKeyFile (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:249:13)
    at _parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:216:40)
  at _parseOSProfileParams__2 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:64:48)
  at generateOSProfile__1 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:32:26)
  at generateVMProfile__1 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmProfile._js:45:41)
  at quickCreateVM__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:334:37)
  at __2 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:176:16)
  <<< raw stack >>>
    at VMOSProfile.__.extend._parseSSHPublicKeyFile (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:249:13)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:216:40)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:204:15)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:207:13)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:168:17)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:177:15)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:183:11)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:159:11)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:162:9)
    at __func (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)

  stack: [Getter/Setter],
  __frame:
   { name: '_parseOSProfileParams__2',
     line: 38,
     file: '/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js',
     prev:
      { name: 'generateOSProfile__1',
        line: 31,
        file: '/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 1,
        col: 25 },
     calls: 1,
     active: false,
     offset: 26,
     col: 47 },
  rawStack: [Getter] }
Error: Specified SSH certificate is not in PEM or SSH RSA format
  <<< async stack >>>
    at VMOSProfile.__.extend._parseSSHPublicKeyFile (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:249:13)
    at _parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:216:40)
  at _parseOSProfileParams__2 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:64:48)
  at generateOSProfile__1 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:32:26)
  at generateVMProfile__1 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmProfile._js:45:41)
  at quickCreateVM__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:334:37)
  at __2 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:176:16)
  <<< raw stack >>>
    at VMOSProfile.__.extend._parseSSHPublicKeyFile (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:249:13)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:216:40)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:204:15)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:207:13)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:168:17)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:177:15)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:183:11)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:159:11)
    at __$_parseLinuxConfiguration__4 (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmOsProfile._js:162:9)
    at __func (/usr/local/Cellar/azure-cli/HEAD-59e0c2a/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
```

**Comment by jacool** [comment]
Still fails...
