### ISSUE TITLE
"network dns record-set add-record" fails for new CNAME record set.

### ISSUE THREAD

**Issue by jdhuntington** [Azure/azure-xplat-cli#3242]
CLI Version: **0.10.5**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure network dns record-set add-record` command fails for new CNAME record

1. Create a new record-set

    `azure network dns record-set create --resource-group sampleresourcegroup --dns-zone-name example.com --name "foo2" --type CNAME`

2. Set value of CNAME

    `azure network dns record-set add-record -v --resource-group sampleresourcegroup --dns-zone-name example.com --record-set-name "foo2" --type CNAME --cname "foo.com"`

3. Observe the following error (instead of the expected setting of the CNAME). Some lines are off-by-one as I have a `console.log` in `dnsZone.js` to debug.

    `info:    Executing command network dns record-set add-record
    verbose: Looking up the dns zone "example.com"
    verbose: Looking up the DNS Record Set "foo2" of type "CNAME"
    { id: '/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/sampleresourcegroup/providers/Microsoft.Network/dnszones/example.com/CNAME/foo2',
      name: 'foo2',
      type: 'Microsoft.Network/dnszones/CNAME',
      etag: 'xxxxxxxxxxxxxxxxxxxxx',
      tTL: 3600 }
    error:   Cannot read property 'cname' of undefined
    error:   Error information has been recorded to /Users/jedediah/.azure/azure.err
    verbose: TypeError: Cannot read property 'cname' of undefined
      <<< async stack >>>
        at addRecord__20 (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:537:352)
      at __85 (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/network.js:1777:15)
      <<< raw stack >>>
        at __$addRecord__20 (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:537:352)
        at __$addRecord__20 (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:537:476)
        at ___ (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:543:111)
        at ___ (/Users/jedediah/local/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
        at ___ (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:507:129)
        at __tryCatch (/Users/jedediah/local/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
        at ___ (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:507:65)
        at __$getRecordSet__18 (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:507:31)
        at __tryCatch (/Users/jedediah/local/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
        at ___ (/Users/jedediah/local/azure-cli/node_modules/azure-cli/lib/commands/arm/network/dnsZone.js:505:237)
    error:   network dns record-set add-record command failed`

Looking at the location of the stacktrace (`lib/commands/arm/network/dnsZone.js`), I determined that `recordSet.cnameRecord.cname` is being called without checking if `recordSet.cnameRecord` is undefined. Setting a CNAME manually via the portal causes that value to be set, and causes further calls to `add-record` to work as expected.

**Comment by MikhailTryakhov** [comment]
Thank you @jdhuntington 
It's fixed and would be published in next release

**Comment by jdhuntington** [comment]
Thanks @MikhailTryakhov
