### ISSUE TITLE
0.10.5 issue with network nic list

### ISSUE THREAD

**Issue by squaint** [Azure/azure-xplat-cli#3251]
CLI Version: **0.10.X**
OS Type:  Linux (Ubuntu, RedHat, etc.)
Installation via:  npm 
Mode: **ARM / ASM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description: After updating to 0.10.5 the network nic list command fails when specifying the resource group and vmss
 azure network nic list -g xxxxxxx -m yyyyyy --json
error: No registered resource provider found for location 'southcentralus' and API version '2016-09-01' for type 'virtualMachineScaleSets/networkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.

Steps to reproduce:
1) Run `azure network nic list -g xxxxxxx -m yyyyyy --json`
`

Error stack trace:

2016-10-12T14:16:06.587Z:
{ [Error: No registered resource provider found for location 'southcentralus' and API version '2016-09-01' for type 'virtualMachineScaleSets/networkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.]
  stack: [Getter/Setter],
  statusCode: 400,
  request:
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers:
      { 'x-ms-client-request-id': '4b11f735-b0ae-4b84-864a-14912f33bdac',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.10.5' },
     url: 'https://management.azure.com/subscriptions/dab074d8-de5d-4eee-9ef0-e7f31dd651b4/resourceGroups/ZSCRG-APP-CAE01/providers/microsoft.Compute/virtualMachineScaleSets/hpcnodex2/networkInterfaces?api-version=2016-09-01',
     body: null },
  response:
   { body: '{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location \'southcentralus\' and API version \'2016-09-01\' for type \'virtualMachineScaleSets/networkInterfaces\'. The supported api-versions are \'2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview\'. The supported locations are \'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest\'."}}',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '76deb5c5-d97f-4582-ba84-718ac19b4ae8',
        'x-ms-correlation-request-id': '76deb5c5-d97f-4582-ba84-718ac19b4ae8',
        'x-ms-routing-request-id': 'CANADACENTRAL:20161012T141606Z:76deb5c5-d97f-4582-ba84-718ac19b4ae8',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Wed, 12 Oct 2016 14:16:05 GMT',
        'content-length': '629' },
     statusCode: 400 },
  code: 'NoRegisteredProviderFound',
  body:
   { code: 'NoRegisteredProviderFound',
     message: 'No registered resource provider found for location \'southcentralus\' and API version \'2016-09-01\' for type \'virtualMachineScaleSets/networkInterfaces\'. The supported api-versions are \'2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview\'. The supported locations are \'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest\'.' },
  __frame:
   { name: 'list__3',
     line: 91,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/network/nic.js',
     prev:
      { name: '__47',
        line: 980,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/network/network.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 4,
        col: 10 },
     calls: 0,
     active: false,
     offset: 12,
     col: 66 },
  rawStack: [Getter] }
Error: No registered resource provider found for location 'southcentralus' and API version '2016-09-01' for type 'virtualMachineScaleSets/networkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.
  <<< async stack >>>
  at list__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/nic.js:103:67)
  at __47 (/usr/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:984:11)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-arm-network/lib/operations/networkInterfaces.js:1049:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:587:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:564:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:339:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)

**Comment by amarzavery** [comment]
@deepakrajendranmsft @huangpf - Can you guys take a look at this issue?

**Comment by huangpf** [comment]
It's related to the networking spec that somehow has a compute API version inside:https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/network.json

**Comment by DeepakRajendranMsft** [comment]
Hi @	squaint, thanks for bringing this up. we are working on this currently to fix it. Will keep you updated
Thanks,
Deepak.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/570
