### ISSUE TITLE
nsg functions need to be able to retry when they hit EAGAIN

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3292]
0.10.6 / npm / linux

This is generally triggered by running lots of operations in parallel - such as to quickyl update a bunch of security rules. Ideally the app should have retry a few times (tunable on command line?) with backoff. Likely exists in other subsystems as well, but the NSG ones are most visible to me cause of the volume of them. 

```

2016-11-02T20:59:57.981Z:
{ [Error: EAGAIN: resource temporarily unavailable, write]
  stack: [Getter/Setter],
  errno: -11,
  code: 'EAGAIN',
  syscall: 'write',
  __frame: 
   { name: 'createRule__7',
     line: 154,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js',
     prev: 
      { name: '__66',
        line: 1385,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 8,
        col: 10 },
     calls: 1,
     active: false,
     offset: 6,
     col: 19 },
  rawStack: [Getter] }
Error: EAGAIN: resource temporarily unavailable, write
  <<< async stack >>>
    at Error (native)
    at Object.fs.writeSync (fs.js:664:18)
    at Interactor.__.extend.progress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:134:8)
    at get__6 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:137:35)
  at createRule__7 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:160:20)
  at __66 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:1393:11)
  <<< raw stack >>>
    at Error (native)
    at Object.fs.writeSync (fs.js:664:18)
    at Interactor.__.extend.progress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:134:8)
    at __$get__6 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:137:35)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.get__6 [as get] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:135:149)
    at __$createRule__7 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:160:19)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.createRule__7 [as createRule] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:154:207)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:1393:26)

```

**Comment by nneul** [comment]
Looking closer this looks to not actually have anything to do with nsg's, but rather just bulk IO. 

Looks like the code is attempting synchronous writes to the console and there is nothing in the code to trap/handle an EAGAIN from the underlying fs.writeSync call. 

This could probably be alleviated by having an option to reduce the output - such as not producing a spinner if AZURE_NON_INTERACTIVE_MODE is set.

**Comment by nneul** [comment]
Another option (possibly more useful) would be to just significantly reduce the activeProgressTimer value while running non-interactive. 

The referenced PR improves behavior and output for me significantly in batch jobs.
