### ISSUE TITLE
'azure sb namespace show' fails

### ISSUE THREAD

**Issue by laurencee** [Azure/azure-xplat-cli#3305]
CLI Version: 0.10.7 (node 7.0.0)
OS Type: Win 10 x64
Installation via:  npm

Mode: ASM

Environment: AzureCloud

Description:
`azure sb namespace show' throws an error.

Steps to reproduce:
1) Run `azure sb namespace show <name>`

Error stack trace:
```js
2016-11-08T22:35:58.318Z:
{ Error
  <<< async stack >>>
  at __2 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\sb.js:77:40)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\serviceclient.js:814:23)
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:1044:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:965:12)
  stack: [Getter],
  string: 'Request to a downlevel service failed.',
  statusCode: 404,
  __frame: 
   { name: '__2',
     line: 68,
     file: 'C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\asm\\sb.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 9,
     col: 39 },
  rawStack: [Getter] }
Error
  <<< async stack >>>
  at __2 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\sb.js:77:40)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\serviceclient.js:814:23)
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:1044:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:965:12)
```

**Comment by amarzavery** [comment]
@sazeesha - Can you take a look at this issue? 
The error message is : `string: 'Request to a downlevel service failed.',
  statusCode: 404,`

**Comment by sazeesha** [comment]
adding @jtaubensee

**Comment by jtaubensee** [comment]
@laurencee - I am unable to reproduce the issue. Can you submit a support ticket through the portal so that you can share your namespace, etc.?

**Comment by laurencee** [comment]
Seems to be working from this PC, I'll test again when I'm back on a work PC.

On a side note, is there a way to get the connection string of the service bus through azure cli?
