### ISSUE TITLE
arm - adding hostname to webapp fails with JS error

### ISSUE THREAD

**Issue by slowtick** [Azure/azure-xplat-cli#3386]
CLI Version: 0.10.7 (node: 4.2.4)
OS Type: Mac
Installation via:  mac installer

Mode: ARM

Environment: AzureCloud

Description:
`azure webapp config hostnames add` command fails with JavaScript error - log.format is not a function

Steps to reproduce:
1) Run `azure webapp config hostnames add --resource-group GROUP_NAME --name WEBAPP_NAME -v --hostnames CUSTOM_DOMAIN_NAME`

Error stack trace:

2016-12-12T06:10:51.141Z:
{ [TypeError: log.format is not a function]
  stack: [Getter/Setter],
  __frame: 
   { name: '__7',
     line: 487,
     file: '/usr/local/azure/lib/commands/arm/webapp/webapp.config.js',
     prev: undefined,
     calls: 0,
     active: true,
     offset: 0,
     col: 0 },
  rawStack: [Getter] }
TypeError: log.format is not a function
  <<< async stack >>>
    at Interactor.__.extend.progress (/usr/local/azure/lib/util/interaction.js:119:31)
    at __7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:517:44)
  at __7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:487:1)
  <<< raw stack >>>
    at Interactor.__.extend.progress (/usr/local/azure/lib/util/interaction.js:119:31)
    at __$__7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:517:44)
    at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:525:307)
    at __$__7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:525:352)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:177)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:110)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:65)

Verbose logs:

info:    Executing command webapp config hostnames add
verbose: Getting webapp hostnames
error:   log.format is not a function
error:   Error information has been recorded to /Users/slowtick/.azure/azure.err
verbose: TypeError: log.format is not a function
  <<< async stack >>>
    at Interactor.__.extend.progress (/usr/local/azure/lib/util/interaction.js:119:31)
    at __7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:517:44)
  at __7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:487:1)
  <<< raw stack >>>
    at Interactor.__.extend.progress (/usr/local/azure/lib/util/interaction.js:119:31)
    at __$__7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:517:44)
    at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:525:307)
    at __$__7 (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:525:352)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:177)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:110)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/webapp/webapp.config.js:508:65)
error:   webapp config hostnames add command failed

**Comment by amarzavery** [comment]
@LukaszStem - Can you take a look at this issue?

**Comment by dugept** [comment]
BTW, I have another error trying to list the hostnames:

```
info:    Executing command webapp config hostnames list
+ Getting webapp hostnames
error:   Cannot read property 'length' of undefined
error:   Error information has been recorded to C:\Users\xxx\.azure\azure.err
error:   webapp config hostnames list command failed
```
