### ISSUE TITLE
login to AzureGermanCloud fails

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-xplat-cli#3391]
CLI Version: **0.10.7 (node: 4.2.6)**
OS Type: Ubuntu
Installation via:  npm

Mode: **ARM*

Environment: **Blackforest**

Description:
`azure login` 2FA flow returns "We don't recognize the code" in the browser:

![image](https://cloud.githubusercontent.com/assets/1448593/21122119/33c424ce-c085-11e6-974c-ea8a9dc45812.png)

Steps to reproduce:
1) clear current credentials in the CLI
2) run `azure login -e AzureGermanCloud`
3) Follow the link in a browser and input the code given by the CLI (I tried Chrome and IE, so it seems to be browser-independent). You should see the error above

Error stack trace:

negat@jumpbox:~$ AZURE_ADAL_LOGGING_ENABLED=1 azure login -e AzureGermanCloud
info:    Executing command login
- Authenticating...Tue, 13 Dec 2016 00:14:21 GMT:4d421df9-1a05-4dad-a493-1ec7a65501cd - Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.de/common
Tue, 13 Dec 2016 00:14:21 GMT:4d421df9-1a05-4dad-a493-1ec7a65501cd - Authority: VERBOSE: Performing static instance discovery
Tue, 13 Dec 2016 00:14:21 GMT:4d421df9-1a05-4dad-a493-1ec7a65501cd - Authority: VERBOSE: Authority validated via static instance discovery.
Tue, 13 Dec 2016 00:14:21 GMT:4d421df9-1a05-4dad-a493-1ec7a65501cd - DeviceCodeRequest: INFO: Getting user code info.
/Tue, 13 Dec 2016 00:14:21 GMT:4d421df9-1a05-4dad-a493-1ec7a65501cd - OAuth2Client: INFO: Get Device Code Server returned this correlationId: 4d421df9-1a05-4dad-a493-1ec7a65501cd
info:    To sign in, use a web browser to open the page https://login.microsoftonline.de/common/oauth2/deviceauth and enter the code REDACTEDto authenticate.
Tue, 13 Dec 2016 00:14:21 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.de/common
Tue, 13 Dec 2016 00:14:21 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - Authority: VERBOSE: Performing static instance discovery
Tue, 13 Dec 2016 00:14:21 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - Authority: VERBOSE: Authority validated via static instance discovery.
Tue, 13 Dec 2016 00:14:21 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - TokenRequest: INFO: Getting a token via device code
|Tue, 13 Dec 2016 00:14:22 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - OAuth2Client: INFO: Get TokenServer returned this correlationId: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b
Tue, 13 Dec 2016 00:14:22 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: be8c58d7-d42b-43bf-be63-f78d8aa2a13f\r\nCorrelation ID: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b\r\nTimestamp: 2016-12-13 00:14:22Z","error_codes":[70016],"timestamp":"2016-12-13 00:14:22Z","trace_id":"be8c58d7-d42b-43bf-be63-f78d8aa2a13f","correlation_id":"86b3e5e8-459f-4cf2-8362-65f40e4c4d6b"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: be8c58d7-d42b-43bf-be63-f78d8aa2a13f\r\nCorrelation ID: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b\r\nTimestamp: 2016-12-13 00:14:22Z","error_codes":[70016],"timestamp":"2016-12-13 00:14:22Z","trace_id":"be8c58d7-d42b-43bf-be63-f78d8aa2a13f","correlation_id":"86b3e5e8-459f-4cf2-8362-65f40e4c4d6b"}
    at Logger.createError (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:201:13)
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:133:25)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
[Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: be8c58d7-d42b-43bf-be63-f78d8aa2a13f\r\nCorrelation ID: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b\r\nTimestamp: 2016-12-13 00:14:22Z","error_codes":[70016],"timestamp":"2016-12-13 00:14:22Z","trace_id":"be8c58d7-d42b-43bf-be63-f78d8aa2a13f","correlation_id":"86b3e5e8-459f-4cf2-8362-65f40e4c4d6b"}]
\Tue, 13 Dec 2016 00:14:28 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - OAuth2Client: INFO: Get TokenServer returned this correlationId: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b
Tue, 13 Dec 2016 00:14:28 GMT:86b3e5e8-459f-4cf2-8362-65f40e4c4d6b - OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: bac29fe5-602f-40db-89e8-327c706a9b1c\r\nCorrelation ID: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b\r\nTimestamp: 2016-12-13 00:14:28Z","error_codes":[70016],"timestamp":"2016-12-13 00:14:28Z","trace_id":"bac29fe5-602f-40db-89e8-327c706a9b1c","correlation_id":"86b3e5e8-459f-4cf2-8362-65f40e4c4d6b"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: bac29fe5-602f-40db-89e8-327c706a9b1c\r\nCorrelation ID: 86b3e5e8-459f-4cf2-8362-65f40e4c4d6b\r\nTimestamp: 2016-12-13 00:14:28Z","error_codes":[70016],"timestamp":"2016-12-13 00:14:28Z","trace_id":"bac29fe5-602f-40db-89e8-327c706a9b1c","correlation_id":"86b3e5e8-459f-4cf2-8362-65f40e4c4d6b"}
    at Logger.createError (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:201:13)
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:133:25)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)

**Comment by amarzavery** [comment]
I am not sure if Azure German Cloud supports interactive login. Can you try org id user login or service principal login?
@yugangw-msft - Do you know whether the German cloud supports interactive login?

**Comment by yugangw-msft** [comment]
I will connect you to AAD teams for updates. Last time the answer to the inquiry is "not yet"

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-xplat-cli/issues/3137

**Comment by balajikris** [comment]
another dupe of this:  #3448

current status update: work in progress. should be ready soon.

**Comment by ducke** [comment]
CLI Version: **0.10.5**
OS Type: Mac
Installation via:  win-or-mac installer

Mode: **ARM**

Environment: **Azure Germany Cloud**

Description:
`azure login -e AzureGermanCloud -u` command doesn't work.

Steps to reproduce:
1) Run `azure login -e AzureGermanCloud -u username@userdomain.onmicrosoft.de`

Error stack trace:

2017-02-16T17:26:15.779Z:
{ [Error: Server returned an unknown AccountType: undefined]
  stack: [Getter/Setter],
  warnToUserInteractive: true,
  __frame: 
   { name: '__1',
     line: 50,
     file: '/Users/ducke/.node/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 66,
     col: 27 },
  rawStack: [Getter] }
Error: Server returned an unknown AccountType: undefined
  <<< async stack >>>
  at __1 (/Users/ducke/.node/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Logger.createError (/Users/ducke/.node/lib/node_modules/azure-cli/node_modules/adal-node/lib/log.js:201:13)
    at /Users/ducke/.node/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:435:46
    at UserRealm._parseDiscoveryResponse (/Users/ducke/.node/lib/node_modules/azure-cli/node_modules/adal-node/lib/user-realm.js:234:3)
    at /Users/ducke/.node/lib/node_modules/azure-cli/node_modules/adal-node/lib/user-realm.js:263:12
    at Request._callback (/Users/ducke/.node/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:137:5)
    at Request.self.callback (/Users/ducke/.node/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (/Users/ducke/.node/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:78:13)
