### ISSUE TITLE
RangeError: invalid string length on storage blob list

### ISSUE THREAD

**Issue by tfmorris** [Azure/azure-xplat-cli#3418]
CLI Version: 0.10.8 (happened with 0.10.4 too, so not a new bug)
OS Type: Mac
Installation via:  docker

Mode: ARM

Environment: AzureCloud
Description:
`azure storage blob list` command returns `RangeError: invalid string length`

Steps to reproduce:

$ docker run -it microsoft/azure-cli
root@aecfe1ca7389:/# time node --max_old_space_size=32000000 /usr/bin/azure storage blob list -a $STORAGE_ACCOUNT -k $KEY 160926-e00504-0021-bh5nfjalxx
info:    Executing command storage blob list
+ Getting blobs in container 160926-e00504-0021-bh5nfjalxx                     
error:   Invalid string length
error:   Error information has been recorded to /root/.azure/azure.err
error:   storage blob list command failed

real	10m59.456s
user	8m48.856s
sys	0m8.840s

Error stack trace:

```
2016-12-28T18:39:48.972Z:
[RangeError: Invalid string length]
RangeError: Invalid string length
    at Array.join (native)
    at stringifyArray (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:165:26)
    at /usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:128:38
    at stringify (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:131:7)
    at Object.eyes.inspect (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:53:16)
    at Object.log.json (/usr/lib/node_modules/azure-cli/lib/util/logging.js:111:22)
    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:316:21)
    at __$listAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1040:29)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1024:178)
```

```
[2016-12-28T19:20:53.206Z]debug : FINAL REQUEST OPTIONS:
{ url: 'https://foo.blob.core.windows.net:443/160926-e00504-0021-bh5nfjalxx?restype=container&comp=list&include=snapshots%2Cmetadata%2Ccopy&marker=2!156!MDAwMDcyITE2MDkyNl9FMDA1MDRfMDAyMV9CSDVORkpBTFhYL1RodW1ibmFpbF9JbWFnZXMvTDAwOC9DOTcuMS9zXzhfMTEwNl90LmpwZyEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-',
  method: 'GET',
  headers: 
   { 'x-ms-client-request-id': 'bfd84760-cd32-11e6-9fc9-3d49a0f02a83',
     'user-agent': 'azure-cli/0.10.8 (Mode arm) Azure-Storage/1.3.0 (NODE-VERSION v4.7.0; Linux 3.19.0-49-generic)',
     'x-ms-version': '2015-12-11',
     'x-ms-date': 'Wed, 28 Dec 2016 19:20:53 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     'content-type': '',
     'content-length': 0,
     authorization: 'SharedKey <deleted>' },
  encoding: undefined }
[2016-12-28T19:20:53.928Z]debug : RESPONSE:
{ error: null,
  response: 
   { isSuccessful: true,
     statusCode: 200,
     body: { EnumerationResults: [Object] },
     headers: 
      { 'transfer-encoding': 'chunked',
        'content-type': 'application/xml',
        server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
        'x-ms-request-id': '08ac6824-0001-0062-673f-61f1ce000000',
        'x-ms-version': '2015-12-11',
        date: 'Wed, 28 Dec 2016 19:20:52 GMT',
        connection: 'close' },
     md5: undefined } }
error:   Invalid string length
silly:   { stack: 'RangeError: Invalid string length\n    at Array.join (native)\n    at stringifyArray (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:165:26)\n    at /usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:128:38\n    at stringify (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:131:7)\n    at Object.eyes.inspect (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:53:16)\n    at Object.log.json (/usr/lib/node_modules/azure-cli/lib/util/logging.js:111:22)\n    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:316:21)\n    at __$listAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1040:29)\n    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)\n    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1024:178)', message: 'Invalid string length' }
error:   Error information has been recorded to /root/.azure/azure.err
verbose: RangeError: Invalid string length
    at Array.join (native)
    at stringifyArray (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:165:26)
    at /usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:128:38
    at stringify (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:131:7)
    at Object.eyes.inspect (/usr/lib/node_modules/azure-cli/node_modules/eyes/lib/eyes.js:53:16)
    at Object.log.json (/usr/lib/node_modules/azure-cli/lib/util/logging.js:111:22)
    at Interactor.__.extend.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:316:21)
    at __$listAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1040:29)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1024:178)
error:   storage blob list command failed

```

**Comment by amarzavery** [comment]
@hasonmsft - Can you please take a look at this issue?
