### ISSUE TITLE
Azure group deployment fails with Template files

### ISSUE THREAD

**Issue by sxamit** [Azure/azure-xplat-cli#3429]
CLI Version: 0.10.8 (node: 0.10.25)
OS Type: Linux  - Ubuntu
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure group deployment create --name xxx --resource-group xxx --template-file template.json --parameters-file parameters.json` command throws error `Object https://management.azure.com has no method 'endsWith'`.

The template and parameter files are the files downloaded from azure portal after creating hdinsight cluster template.

Steps to reproduce:
1) Create Template for HdInsight cluster `
2) Download the template files
3) Run ./deploy.sh with the relevant params. or simply run `azure group deployment create...` command
4) Exception is thrown

Error stack trace:
```
2017-01-08T10:03:44.348Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame: 
   { name: 'exports_createDeployment__1',
     line: 71,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
     prev: 
      { name: '__1',
        line: 52,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 21,
        col: 34 },
     calls: 2,
     active: false,
     offset: 20,
     col: 31 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at Deployments.validate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1314:39)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
  at exports_createDeployment__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:32)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:73:35)
  <<< raw stack >>>
    at Deployments.validate (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1314:39)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:156)
    at Interactor.__.extend.withProgress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:30)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at __$createDeploymentParameters (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:320:16)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:198:16
```

**Comment by amarzavery** [comment]
Please update the version of node.js on your system. 0.10.25 is too old. Even node.js does not support it anymore.

For Debian and Ubuntu distributions, the following 2 commands should install the latest version in the 4.x series.

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

sudo apt-get install -y nodejs



This link<https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager> (bookmark it J) should help you install an LTS version of node.js on different Linux flavors. Latest version in the 4.x release<https://nodejs.org/dist/latest-v4.x/> (4.7.2 as of today) would be the recommended version of node.js for xplat cli.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sxamit** [comment]
@amarzavery Cheers mate
