### ISSUE TITLE
azure webapp config hostnames list fails

### ISSUE THREAD

**Issue by setevoy2** [Azure/azure-xplat-cli#3435]
CLI Version: **azure webapp config hostnames list**
OS Type: Linux (Arch Linux)
Installation via:  npm

Mode: both - **ARM / ASM**

Environment: **AzureCloud**

Description:
`azure webapp config hostnames list` returns "Cannot read property 'length' of undefined".

Steps to reproduce:
1) Run `azure login`
2) Then run `azure webapp config hostnames list -g resgrname -n webappname`

Error stack trace:

```$ cat /home/setevoy/.azure/azure.err
2017-01-11T10:08:42.124Z:
TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:598:22
    at Interactor.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:320:7)
    at __$__9 (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:596:27)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:177)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:110)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:65)
    at __$__9 (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:31)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:598:22
    at Interactor.formatOutput (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:320:7)
    at __$__9 (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:596:27)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:177)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:110)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:65)
    at __$__9 (/usr/lib/node_modules/azure-cli/lib/commands/arm/webapp/webapp.config.js:594:31)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)```

**Comment by amarzavery** [comment]
Lukasz, please take a look at this issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
