### ISSUE TITLE
no method 'endsWith' error using cli on WSL

### ISSUE THREAD

**Issue by larryms** [Azure/azure-xplat-cli#3443]
CLI Version: 0.10.8 (node: 0.10.25)
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)  Bash shell using Windows Subsystem for Linux (WSL) running on Windows 10
Installation via:  npm
Mode: ARM

Environment: AzureCloud
Description:  
'azure group create demogroup -l westus' returns error

Steps to reproduce:
1) Run 'azure group create demogroup -l westus'  in the WSL shell
Returns an error:
info:    Executing command group create
+ Getting resource group demogroup
error:   Object https://management.azure.com has no method 'endsWith'
error:   Error information has been recorded to /home/larry/.azure/azure.err
error:   group create command failed

Error stack trace:
2017-01-18T13:09:53.622Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame:
   { name: 'group_createResourceGroup__3',
     line: 81,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
     prev:
      { name: '__1',
        line: 54,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 7,
        col: 31 },
     calls: 1,
     active: false,
     offset: 6,
     col: 20 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at ResourceGroups.get (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:818:39)
    at Object.getGroup (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
  at group_createResourceGroup__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:21)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:61:32)
  <<< raw stack >>>
    at ResourceGroups.get (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:818:39)
    at Object.getGroup (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:165)
    at Interactor.__.extend.withProgress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at __$group_createResourceGroup__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:30)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.group_createResourceGroup__3 [as createResourceGroup] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:81:248)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:61:20)

**Comment by larryms** [comment]
Note that I installed the azure cli for WSL using the steps outlined here:  https://blogs.technet.microsoft.com/uktechnet/2017/01/16/install-and-run-the-azure-cli-on-the-windows-subsystem-for-linux-wsfl/

**Comment by amarzavery** [comment]
Version of node.js is the problem. It's too old. Even node.js does not support it anymore.
Please follow the instructions in this link to install the latest 4.x LTS version of node. Instructions for Ubuntu would apply for wsl as well.

https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager

In the command to install the lts version replace 6.x with 4.x

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by larryms** [comment]
That worked, thanks.
(I had previously tried apt-get ; apt-get upgrade via the shell but it didn't indicate an upgrade to node was available.  The steps you provided worked and fixed the problem.)
