### ISSUE TITLE
Object https://management.azure.com has no method 'endsWith'

### ISSUE THREAD

**Issue by setevoy2** [Azure/azure-xplat-cli#3456]
CLI Version: **0.10.8**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure provider register` command leads to the "Object https://management.azure.com has no method 'endsWith'" error.

Steps to reproduce:
1) Run `azure login`
2) Then run `azure account set`
3) `azure account set`
4) `azure provider register --namespace Microsoft.Network`

Error stack trace:

```
+
error:   Object https://management.azure.com has no method 'endsWith'
error:   Error information has been recorded to /home/travis/.azure/azure.err
error:   provider register command failed

2017-01-27T10:54:29.382Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame: 
   { name: '__3',
     line: 126,
     file: '/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 6,
     col: 6 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at Providers.register (/home/travis/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/providers.js:224:39)
    at Subscription._.extend.registerArmProvider (/home/travis/node_modules/azure-cli/lib/util/profile/subscription.js:216:22)
    at __1 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:134:31)
  at __3 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:132:7)
  <<< raw stack >>>
    at Providers.register (/home/travis/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/providers.js:224:39)
    at Subscription._.extend.registerArmProvider (/home/travis/node_modules/azure-cli/lib/util/profile/subscription.js:216:22)
    at __$__1 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:134:31)
    at __func (/home/travis/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:132:191)
    at Interactor.__.extend.withProgress (/home/travis/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at __$__3 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:132:14)
    at __func (/home/travis/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__3 (/home/travis/node_modules/azure-cli/lib/commands/arm/providers/provider.js:121:408)
    at AzureCli.<anonymous> (/home/travis/node_modules/azure-cli/lib/cli.js:223:12)
```

**Comment by henriquenn** [comment]
I'm getting the same error when i run the commands:
azure location list
azure group set <name>

Also with:
CLI Version: 0.10.8
OS Type: Linux (Ubuntu)
Installation via: npm
Mode: ARM
Environment: AzureCloud

The Stacktrace error is:
`cat .azure/azure.err 
2017-01-27T12:36:40.297Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame: 
   { name: 'group_createResourceGroup__3',
     line: 81,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
     prev: 
      { name: '__2',
        line: 73,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 4,
        col: 31 },
     calls: 1,
     active: false,
     offset: 6,
     col: 20 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at ResourceGroups.get (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:818:39)
    at Object.getGroup (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
  at group_createResourceGroup__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:21)
  at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:77:32)
  <<< raw stack >>>
    at ResourceGroups.get (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:818:39)
    at Object.getGroup (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:165)
    at Interactor.__.extend.withProgress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at __$group_createResourceGroup__3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:30)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.group_createResourceGroup__3 [as createResourceGroup] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:81:248)
    at __$__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:77:20)
`

**Comment by henriquenn** [comment]
Just found the solution here:
https://github.com/Azure/azure-xplat-cli/issues/3443
Look for amarzavery post.

**Comment by setevoy2** [comment]
@henriquenn Thanks, looks like this is the key, here is my build log:

> npm WARN engine azure-cli@0.10.8: wanted: {"node":">= 4.2.4"} (current: {"node":"0.10.36","npm":"1.4.28"})

`Node.js v0.10.36		2015-01-26	3.14.5.9`

Will try update it (it's TravisCI build).

**Comment by balajikris** [comment]
That's right guys. I've seen too many reports now of the kind- "method not found", "method missing" , which means the framework/runtime library (node in our case) is outdated. I'd recommend switching to the latest 4.x LTS (Node.js v4.7.2 from https://nodejs.org/dist/latest-v4.x/) which is the official version we support.

**Comment by balajikris** [comment]
@setevoy2 :  If the above suggestions worked, can I close this issue? Or do you still need help with this?

**Comment by setevoy2** [comment]
@balajikris Sorry - still had no chance to check it, big project.
Please - feel free to close it.
Thanks for coming up here)
