### ISSUE TITLE
name of webresource.js is incorrect

### ISSUE THREAD

**Issue by tsukashusan** [Azure/azure-xplat-cli#3463]
CLI Version: **0.10.8**
OS Type: bash on Ubuntu on Windows
Installation via:  npm 

Mode: **ARM / ASM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
`azure login`
error:   Cannot find module './webResource'

Steps to reproduce:
1) Run `azure login`
2) Then run `azure login show ...`

Error stack trace:
azure login
error:   Cannot find module './webResource'
error:   Error information has been recorded to /home/ubuntu/.azure/azure.err

**2017-02-02T10:37:17.193Z:
{ [Error: Cannot find module './webResource'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './webResource'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/msRest.js:7:23)
    at Module._compile (module.js:456:26)
    at Module.pModule._compile (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)**

filename is mistake.
webresource.js

The correct file name is web**R**esource.js.

>ls /usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/
constants.js  filters                   index.d.ts  requestPipeline.js  serviceClient.js  webresource.js
credentials   httpOperationResponse.js  msRest.js   serialization.js    utils.js

**Comment by amarzavery** [comment]
@tsukashusan - Sorry for the inconvenience. A new version of ms-rest (dependency of azure-xplat-cli) has been published to npm. Please uninstall the azure-cli and install it again.

Let me know if you see further issues.
