### ISSUE TITLE
azure location list -- error:  Object https://management.azure.com has no method 'endsWith'

### ISSUE THREAD

**Issue by tsukashusan** [Azure/azure-xplat-cli#3464]
CLI Version: **0.10.8**
OS Type: Win(bash on Ubuntu on Windows)
Installation via:  npm
Mode: **ARM**

Environment: **local machine**

Description:
`azure location list`
info:    Executing command location list
+ Getting ARM registered providers
error:   Object https://management.azure.com has no method 'endsWith'
error:   Error information has been recorded to /home/ubuntu/.azure/azure.err
error:   location list command failed

Steps to reproduce:
1) Run `azure location list
`2) Then run `azure vm show ...`

Error stack trace:

*2017-02-02T10:46:44.159Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame:
   { name: '__1',
     line: 44,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js',
     prev:
      { name: '__1',
        line: 36,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 7,
        col: 6 },
     calls: 1,
     active: false,
     offset: 1,
     col: 36 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at Providers.list (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/providers.js:373:39)
    at getAllProviders (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/providers/providerUtils.js:19:29)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js:45:37)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js:43:7)
  <<< raw stack >>>
    at Providers.list (/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/providers.js:373:39)
    at __$getAllProviders (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/providers/providerUtils.js:19:29)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.getAllProviders (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/providers/providerUtils.js:1:407)
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js:45:34)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js:43:139)
    at Interactor.__.extend.withProgress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/location/location.js:43:16)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)* 

This issue of patch is as below.
```
/usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/providers.js
 85c85,90
<   var requestUrl = baseUrl + (baseUrl.endsWith('/') ? '' : '/') + 'subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}/unregister';
---
>   var requestUrl = "";
>   if ( baseUrl.lastIndexOf('/') != baseUrl.length){
>       requestUrl = baseUrl + '/' + 'subscriptions/{subscriptionId}/providers';
>   }else{
>       requestUrl = baseUrl  + 'subscriptions/{subscriptionId}/providers';
>   }
```

**Comment by amarzavery** [comment]
The version of node.js on the linux subsystem is very old. 
Please follow the instructions over [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) to install the latest version in 4.x range.

The doc shows the command to install latest version in 6.x range. Instead of 6.x modify it to 4.x before executing the command.

Then you should be good to go.

**Comment by Mohamed-Garrana** [comment]
Thanks, Had the same issue and was solved by installing Node.js v7
