### ISSUE TITLE
azure CLI calling ARM template for webapp with asp.net 

### ISSUE THREAD

**Issue by nm7427** [Azure/azure-xplat-cli#3507]
CLI Version: 0.10.9 (node: 7.5.0)
OS Type: Linux (Ubuntu, RedHat, etc.)  4.8.0-37-generic #39-Ubuntu
Installation via:  npm /  github repo

Mode: ARM 

Environment: **AzureCloud/

Description:
I am executing the script 
azure login --service-principal -u 498e8018-f996-45ef-a574-23c25134149b -p XXXXXX --tenant acpcloud783hotmail.onmicrosoft.com
azure group create -n 'myrgdoctest' -l EastUS
#
#azure group template validate -f /home/nmish/webdeploy.json -p "{\"siteName\":{\"value\":\"tan1\"},\"hostingPlanName\":{\"value\":\"F1\"}}" -g 'myrgdoctest'
azure group deployment create -f /home/nmish/webdeploy.json -p "{\"siteName\":{\"value\":\"tan1\"},\"hostingPlanName\":{\"value\":\"F1\"}}" -g 'myrgdoctest' -n 'Webappurllinux'

#echo "webappurl = http://tan1.azurewebsites.net"

I am executing this script from the Ubuntu Linux VM and I get this error 
"nmish@doctest1:~$ ./webapplin2.ps1
info:    Executing command login
|info:    Added subscription Microsoft Azure Enterprise
+
info:    login command OK
info:    Executing command group create
+ Getting resource group myrgdoctest
+ Updating resource group myrgdoctest
info:    Updated resource group myrgdoctest
data:    Id:                  /subscriptions/e085aac0-d745-4d5f-9ab7-18da8eeb036d/resourceGroups/myrgdoctest
data:    Name:                myrgdoctest
data:    Location:            eastus
data:    Provisioning State:  Succeeded
data:    Tags: null
data:
info:    group create command OK
info:    Executing command group deployment create
+ Initializing template configurations and parameters
+ Creating a deployment
error:   "deploymentName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
error:   Error information has been recorded to /home/nmish/.azure/azure.err
error:   group deployment create command failed

./webapplin2.ps1: line 8: $'\r': command not found
./webapplin2.ps1: line 9: $'\r': command not found
./webapplin2.ps1: line 11: $'\r': command not found

Now when I execute the same commands from one by one , I do not get any error message ,
This script is calling webdeploy.json file . 
:
1) Run `azure vm create ...`
2) Then run `azure vm show ...`

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**
nmish@doctest1:~$ cat /home/nmish/.azure/azure.err
2017-02-16T12:05:00.190Z:
{ Error: "deploymentName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
  <<< async stack >>>
    at Deployments.validate (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1293:15)
    at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:41)
  at exports_createDeployment__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:32)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:73:35)
  <<< raw stack >>>
    at Deployments.validate (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1293:15)
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:156)
    at Interactor.withProgress (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:30)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at __$createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:320:16)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/lib/node_modules/azure-cli/lib/util/interaction.js:198:16
  stack: [Getter],
  __frame:
   { name: '__1',
     line: 92,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
     prev:
      { name: 'exports_createDeployment__1',
        line: 71,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 20,
        col: 31 },
     calls: 0,
     active: false,
     offset: 1,
     col: 40 },
  rawStack: [Getter] }
Error: "deploymentName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
  <<< async stack >>>
    at Deployments.validate (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1293:15)
    at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:41)
  at exports_createDeployment__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:32)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:73:35)
  <<< raw stack >>>
    at Deployments.validate (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/deployments.js:1293:15)
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:93:37)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:156)
    at Interactor.withProgress (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:195:12)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:91:30)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at __$createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:320:16)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/lib/node_modules/azure-cli/lib/util/interaction.js:198:16

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).
nmish@doctest1:~$ ./webapplin2.ps1
info:    Executing command login
|info:    Added subscription Microsoft Azure Enterprise
+
info:    login command OK
info:    Executing command group create
+ Getting resource group myrgdoctest
+ Updating resource group myrgdoctest
info:    Updated resource group myrgdoctest
data:    Id:                  /subscriptions/e085aac0-d745-4d5f-9ab7-18da8eeb036d/resourceGroups/myrgdoctest
data:    Name:                myrgdoctest
data:    Location:            eastus
data:    Provisioning State:  Succeeded
data:    Tags: null
data:
info:    group create command OK
info:    Executing command group deployment create
+ Initializing template configurations and parameters
+ Creating a deployment
error:   "deploymentName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
error:   Error information has been recorded to /home/nmish/.azure/azure.err
error:   group deployment create command failed

./webapplin2.ps1: line 8: $'\r': command not found
./webapplin2.ps1: line 9: $'\r': command not found
./webapplin2.ps1: line 11: $'\r': command not found

**Comment by nm7427** [comment]
I have attached the webdeploy.json template here

**Comment by nm7427** [comment]
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "siteName": {
      "type": "string",
      "metadata": {
        "description": "The name of the web app that you wish to create."
      }
    },
    "hostingPlanName": {
      "type": "string",
      "metadata": {
        "description": "The name of the App Service plan to use for hosting the web app."
      }
    },
    "sku": {
      "type": "string",
      "allowedValues": [
        "F1",
        "D1",
        "B1",
        "B2",
        "B3",
        "S1",
        "S2",
        "S3",
        "P1",
        "P2",
        "P3",
        "P4"
      ],
      "defaultValue": "S1",
      "metadata": {
        "description": "The pricing tier for the hosting plan."
      }
    },
    "workerSize": {
      "type": "string",
      "allowedValues": [
        "0",
        "1",
        "2"
      ],
      "defaultValue": "0",
      "metadata": {
        "description": "The instance size of the hosting plan (small, medium, or large)."
      }
    },
    "repoURL": {
      "type": "string",
      "defaultValue": "https://github.com/davidebbo-test/Mvc52Application.git",
      "metadata": {
        "description": "The URL for the GitHub repository that contains the project to deploy."
      }
    },
    "branch": {
      "type": "string",
      "defaultValue": "master",
      "metadata": {
        "description": "The branch of the GitHub repository to use."
      }
    }
  },
  "resources": [
    {
      "apiVersion": "2015-08-01",
      "name": "[parameters('hostingPlanName')]",
      "type": "Microsoft.Web/serverfarms",
      "location": "[resourceGroup().location]",
      "sku": {
        "name": "[parameters('sku')]",
        "capacity": "[parameters('workerSize')]"
      },
      "properties": {
        "name": "[parameters('hostingPlanName')]"
      }
    },
    {
      "apiVersion": "2015-08-01",
      "name": "[parameters('siteName')]",
      "type": "Microsoft.Web/sites",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', parameters('hostingPlanName'))]"
      ],
      "properties": {
        "serverFarmId": "[parameters('hostingPlanName')]"
      },
      "resources": [
        {
          "apiVersion": "2015-08-01",
          "name": "web",
          "type": "sourcecontrols",
          "dependsOn": [
            "[resourceId('Microsoft.Web/Sites', parameters('siteName'))]"
          ],
          "properties": {
            "RepoUrl": "[parameters('repoURL')]",
            "branch": "[parameters('branch')]",
            "IsManualIntegration": true
          }
        }
      ]
    }
  ]
}

>

**Comment by nm7427** [comment]
I was able to execute the script I did use dos2unix command on the script then it started working
