### ISSUE TITLE
Default API version for Microsoft.Compute breaking AzureChinaCloud v0.10.9

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-xplat-cli#3513]
CLI Version: 0.10.9
OS Type: Ubuntu
Installation via:  npm
Mode: ARM
Environment: Azure China Cloud

Description:
Default API version with v0.10.9 uses 2016-04-30-preview which is not supported on Azure China.

Steps to reproduce:
1) Run `azure vm list`

Reverting back to 0.10.8 and it works fine.

Error stack trace:
2017-02-22T07:48:18.510Z:
{ Error: The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30'.
  <<< async stack >>>
  at getVMList__5 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js:77:75)
  at listVM__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:393:36)
  at __3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:190:16)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:1166:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:605:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:582:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:339:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:126:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
  stack: [Getter/Setter],
  statusCode: 404,
  request: 
   { rawResponse: false,
     queryString: {},
     url: 'https://management.chinacloudapi.cn/subscriptions/272631ec-fd52-4aad-99e9-be7536523148/providers/Microsoft.Compute/virtualMachines?api-version=2016-04-30-preview',
     method: 'GET',
     headers: 
      { 'x-ms-client-request-id': '55656f08-f467-4a02-a60f-35eab231a908',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'x-ms-command-name': 'vm list',
        'x-ms-parameter-set-name': '',
        'user-agent': 'AzureXplatCLI/0.10.9;osType:Linux;osVersion:4.10.0-041000-generic;nodeVersion:v6.10.0;installationType:NPM;userId:50d17f86aa34682cd0461d89ac7145f74f2dd213f3865af408253172b8dac88a;subscriptionId:272631ec-fd52-4aad-99e9-be7536523148;userType:user;mode:arm' },
     body: null },
  response: 
   { body: '{"error":{"code":"InvalidResourceType","message":"The resource type \'virtualMachines\' could not be found in the namespace \'Microsoft.Compute\' for api version \'2016-04-30-preview\'. The supported api-versions are \'2015-05-01-preview,2015-06-15,2016-03-30\'."}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '9cf0a1bd-521e-453c-a31d-d33c6f4d74b6',
        'x-ms-correlation-request-id': '9cf0a1bd-521e-453c-a31d-d33c6f4d74b6',
        'x-ms-routing-request-id': 'CHINAEAST:20170222T074818Z:9cf0a1bd-521e-453c-a31d-d33c6f4d74b6',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Wed, 22 Feb 2017 07:48:18 GMT',
        connection: 'close',
        'content-length': '257' },
     statusCode: 404 },
  code: 'InvalidResourceType',
  body: 
   { code: 'InvalidResourceType',
     message: 'The resource type \'virtualMachines\' could not be found in the namespace \'Microsoft.Compute\' for api version \'2016-04-30-preview\'. The supported api-versions are \'2015-05-01-preview,2015-06-15,2016-03-30\'.' },
  __frame: 
   { name: 'getVMList__5',
     line: 67,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js',
     prev: 
      { name: 'listVM__6',
        line: 388,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 5,
        col: 35 },
     calls: 0,
     active: false,
     offset: 10,
     col: 74 },
  rawStack: [Getter] }
Error: The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30'.
  <<< async stack >>>
  at getVMList__5 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js:77:75)
  at listVM__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:393:36)
  at __3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:190:16)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:1166:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:605:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:582:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:339:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:126:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)

**Comment by amarzavery** [comment]
@singhkays @huangpf - Any ETA for the 2016-04-30-preview api version being deployed in Moon Cake.

**Comment by hunter-xue** [comment]
2016-04-30-preview is the biggest issue of AzureChina. Most of lastest APIs and SDK are unavailable on AzureChina.

**Comment by huangpf** [comment]
@hunter-xue 
CLI's release is in fact regional in that the current latest version is not yet available for all regions or national clouds, including AzureChina in this case.

@amarzavery who owns the release process shall provide a way to tag whether a specific version of CLI is available for which cloud.

**Comment by kfiresmith** [comment]
Um, could it possibly be that '2016-04-30-preview' isn't supported yet by AzureUSGovernment either?  Madness!

bash-4.3# az disk list
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.

Further - how is there not an Azure API compatibility check during 'az login' to save us from having to discover this the hard way?

**Comment by zp-j** [comment]
Is there any way to alter the API version to an older one to bypass the issue? Thanks!

**Comment by AlexieUrsache** [comment]
Hi,
We have a similar issue using the version '2017-03-30' (azure sdk 3.0):
The Error is:
The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2017-03-30'. The supported api-versions are '2015-06-15,2016-03-30'.

Question: We are pointing to AzureStack Will there be support for '2017-03-30' ?

**Comment by amarzavery** [comment]
This project is in it's end of support life for commands in ARM mode. All the new development is happening in CLI 2.0. Please use the new python based CLI [Azure CLI 2.0](https://github.com/azure/azure-cli).
