### ISSUE TITLE
azure storage account listing has error

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#3529]
CLI Version: **0.10.10**
OS Type:  Linux (CentOS release 6.8 (Final))
Installation via:  npm 

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure storage account list` command doesn't output storage accounts.

Steps to reproduce:
1) Run `azure login` and successfully login with account
2) Then run `azure storage account list`

Error stack trace:

**2017-03-05T09:10:34.155Z:
{ [TypeError: Object https://management.azure.com has no method 'endsWith']
  stack: [Getter/Setter],
  __frame: 
   { name: 'storageAccount_listCommand__1',
     line: 480,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 3,
     col: 26 },
  rawStack: [Getter] }
TypeError: Object https://management.azure.com has no method 'endsWith'
  <<< async stack >>>
    at StorageAccounts.list (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-storage/lib/operations/storageAccounts.js:954:39)
    at listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:277:58)
  at storageAccount_listCommand__1 (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:483:27)
  <<< raw stack >>>
    at StorageAccounts.list (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-storage/lib/operations/storageAccounts.js:954:39)
    at __$listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:277:58)
    at __$listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:277:174)
    at __$listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:280:175)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:269:113)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:280:236)
    at __$listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:283:166)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at listAccounts (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.account.js:268:143)
**

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by balajikris** [comment]
@infosatheesh2020 This typically means you're running an outdated version of nodejs. can you install the latest 4.x LTS version of nodejs and see if this goes away? 

Note: you can also see all the duplicates of this bug on this repo [here](https://github.com/Azure/azure-xplat-cli/issues?q=is%3Aissue+endsWith+is%3Aclosed)

**Comment by infosatheesh2020** [comment]
Thanks!
