### ISSUE TITLE
azure login fails if there are disabled logins associated with account

### ISSUE THREAD

**Issue by brewt** [Azure/azure-xplat-cli#3538]
CLI Version: 0.10.10
OS Type: Gentoo Linux
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
`azure login` fails if there's a disabled login associated with the account.

By disabled login, I mean that when you're at https://portal.azure.com/, and you click on the user e-mail/icon at the top right, it shows multiple Directories (?) in that list, and where one of those is an account you don't have access to anymore.

Steps to reproduce:
1) Run `azure login`

Error stack trace:

```
2017-03-14T19:09:42.932Z:
{ Error: We don't have a valid access token. Please run "azure login" again.
  <<< async stack >>>
  at __1 (/home/brewt/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at _polishError (/home/brewt/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:64:10)
    at /home/brewt/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:48:25
    at /home/brewt/node_modules/azure-cli/lib/util/authentication/token-cache.js:107:9
    at FSReqWrap.oncomplete (fs.js:123:15)
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 50,
     file: '/home/brewt/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 66,
     col: 27 },
  rawStack: [Getter] }
Error: We don't have a valid access token. Please run "azure login" again.
  <<< async stack >>>
  at __1 (/home/brewt/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at _polishError (/home/brewt/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:64:10)
    at /home/brewt/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:48:25
    at /home/brewt/node_modules/azure-cli/lib/util/authentication/token-cache.js:107:9
    at FSReqWrap.oncomplete (fs.js:123:15)
```

After enabling AZURE_ADAL_LOGGING_ENABLED it was apparent what the problem was.  Specifying the tenant with the --tenant allows it to login, but the error message from above isn't any help.

```
Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Authority: VERBOSE: Performing static instance discovery
Authority: VERBOSE: Authority validated via static instance discovery.
TokenRequest: INFO: Getting token from cache with refresh if necessary.
CacheDriver: VERBOSE: finding with query:{"clientId":"yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy","userId":"user@example.com"}
CacheDriver: VERBOSE: Looking for potential cache entries:
CacheDriver: VERBOSE: {"_clientId":"yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy","userId":"user@example.com"}
CacheDriver: VERBOSE: Found 2 potential entries.
CacheDriver: VERBOSE: No resource specific cache entries found.
CacheDriver: VERBOSE: Found an MRRT token.
CacheDriver: VERBOSE: Returning token from cache lookup, AccessTokenId: aa+aa+aaaaaaaaaaaaaaaa+aaaaaaaaaaaaaaaaaaaa=, RefreshTokenId: bbbbbbbbbbbb/bbbbb/bbbbbbbbbbbbbbbbbbbbbbbb=
CacheDriver: INFO: Acquiring new access token from MRRT token.
TokenRequest: VERBOSE: Called to refresh a token from the cache.
TokenRequest: INFO: Getting a new token from a refresh token.
OAuth2Client: INFO: Get TokenServer returned this correlationId: zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz
OAuth2Client: ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50057: User account is disabled.\r\nTrace ID: wwwwwwww-wwww-wwww-wwww-wwwwwwwwwwww\r\nCorrelation ID: zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz\r\nTimestamp: 2017-03-14 20:16:06Z","error_codes":[50057],"timestamp":"2017-03-14 20:16:06Z","trace_id":"zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz","correlation_id":"zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"}
Stack:
Error: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50057: User account is disabled.\r\nTrace ID: wwwwwwww-wwww-wwww-wwww-wwwwwwwwwwww\r\nCorrelation ID: zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz\r\nTimestamp: 2017-03-14 20:16:06Z","error_codes":[50057],"timestamp":"2017-03-14 20:16:06Z","trace_id":"wwwwwwww-wwww-wwww-wwww-wwwwwwwwwwww","correlation_id":"zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"}
    at Logger.createError (/home/brewt/node_modules/adal-node/lib/log.js:201:13)
    at Request._callback (/home/brewt/node_modules/adal-node/lib/util.js:133:25)
    at Request.self.callback (/home/brewt/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/brewt/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/brewt/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
```

**Comment by amarzavery** [comment]
I understand your scenario. Have never seen something like that before. Will contact the adal service team to find out what is going on.

It would be nice if you provide us the `correlation id` and the `trace id`. That will help the service team figure out what exactly went wrong.

**Comment by brewt** [comment]
Thanks, here you go:

Trace ID: 486bb9b8-7a40-4e5c-a04e-ee7bd53b33d4
Correlation ID: 46749634-36f3-4a3e-9cf1-009d28637b5a
