### ISSUE TITLE
The cli can no longer connect to the Azure US Government Cloud

### ISSUE THREAD

**Issue by OpusDude** [Azure/azure-xplat-cli#3539]
CLI Version: 0.10.10 (node: 7.2.1)
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: ARM

Environment: US Government

Description:
`azure login` command times out when trying to connect to the US Gov Cloud. It has no issues connecting to the Azure Public Cloud. This worked last Friday on the US Gov Cloud but now fails every time. I can connect to the US Gov Cloud using the same command and subscription from a Windows system using the Azure PowerShell cli.

Steps to reproduce:
1) Run `azure login --username $CLIENT_ID --password $CLIENT_SECRET --service-principal --tenant $TENANT_ID --environment "AzureUSGovernment"`

info:    Executing command login
+ Authenticating...
error:   connect ETIMEDOUT 23.97.27.241:443
error:   Error information has been recorded to /home/xxxxxxx/.azure/azure.err
error:   login command failed

Error stack trace:

2017-03-14T22:32:18.010Z:
{ Error: connect ETIMEDOUT 23.97.27.241:443
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  stack: [Getter],
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '23.97.27.241',
  port: 443,
  innerError:
   { Error: connect ETIMEDOUT 23.97.27.241:443
       at Object.exports._errnoException (util.js:1022:11)
       at exports._exceptionWithHostPort (util.js:1045:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '23.97.27.241',
     port: 443,
     innerError:
      { Error: connect ETIMEDOUT 23.97.27.241:443
          at Object.exports._errnoException (util.js:1022:11)
          at exports._exceptionWithHostPort (util.js:1045:20)
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
        code: 'ETIMEDOUT',
        errno: 'ETIMEDOUT',
        syscall: 'connect',
        address: '23.97.27.241',
        port: 443 } },
  __frame:
   { name: '__1',
     line: 50,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 66,
     col: 27 },
  rawStack: [Getter] }
Error: connect ETIMEDOUT 23.97.27.241:443
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by amarzavery** [comment]
That seems weird. 
@yugangw-msft - do you have any idea about this?

**Comment by yugangw-msft** [comment]
> connect ETIMEDOUT 23.97.27.241:443

Nextwork issues or server host issues. Suggest retry
