### ISSUE TITLE
Object linux has no method 'startsWith'

### ISSUE THREAD

**Issue by carlhoerberg** [Azure/azure-xplat-cli#3546]
You introduced a bug that makes the cli unusable with: 
https://github.com/Azure/azure-xplat-cli/pull/3520/files#diff-86151976d357827c3ab35a7c508b9524R318

`os.platform()` returns an object, not a string! 

```
$ azure telemetry --disable

/usr/local/lib/node_modules/azure-cli/lib/util/telemetry.js:318
  if (os.platform().startsWith('win')) {
                    ^
TypeError: Object linux has no method 'startsWith'
    at _getMacAddressHash (/usr/local/lib/node_modules/azure-cli/lib/util/telemetry.js:318:21)
    at Object.exports.start (/usr/local/lib/node_modules/azure-cli/lib/util/telemetry.js:246:24)
    at /usr/local/lib/node_modules/azure-cli/bin/azure.js:30:19
    at Object.exports.isTelemetryEnabled (/usr/local/lib/node_modules/azure-cli/lib/util/utilsCore.js:174:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by balajikris** [comment]
Nope. its likely that the version of node.js on your box is very old. Check `node -v` and then check this [doc](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) on how to get the latest stable version of node.js installed on your box. This application requires atleast LTS 4.x to be fully functional. Once you have an updated version then you should be good to go.
