### ISSUE TITLE
Error: We don't have a valid access token. Please run "azure login" again.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#3553]
CLI Version: **0.10.11**
OS Type: Ubuntu 14.04.4 LTS
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
I can access portal.azure.com successfully with my account. I run `azure login` and finish the authentication in my browser successfully but I get below error result in command line. Even if I reinstalled azure-cli and deleted `~/.azure`, I still hit the same error.

```
info:    Executing command login
\info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXXX to authenticate.
+
error:   We don't have a valid access token. Please run "azure login" again.
error:   Error information has been recorded to /home/user/.azure/azure.err
error:   login command failed

```

Steps to reproduce:
1) Run `azure login`

Error stack trace:
```
2017-04-06T01:59:44.703Z:
{ Error: We don't have a valid access token. Please run "azure login" again.
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:118:28)
  <<< raw stack >>>
    at _polishError (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:64:10)
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:48:25
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:107:9
    at FSReqWrap.oncomplete (fs.js:114:15)
  stack: [Getter],
  __frame:
   { name: '__1',
     line: 50,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 68,
     col: 27 },
  rawStack: [Getter] }
Error: We don't have a valid access token. Please run "azure login" again.
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:118:28)
  <<< raw stack >>>
    at _polishError (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:64:10)
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:48:25
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:107:9
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by amarzavery** [comment]
Please use [azure cli 2.0](https://github.com/Azure/azure-cli/releases)
