### ISSUE TITLE
Setting tags with Resource ID fails and gives incorrect resolution

### ISSUE THREAD

**Issue by esell** [Azure/azure-xplat-cli#3611]
CLI Version: **0.10.13**
OS Type: Linux (bash on windows)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure resource set -t` command doesn't take just a resource ID and gives incorrect resolution information.

Steps to reproduce:
1) Run `azure resource set -t owner=it -i "/subscriptions/SUBID/resourcegroups/autotest/providers/Microsoft.Automation/automationAccounts/autotest/runbooks/AzureClassicAutomationTutorialScript"`
2) Response is: 
```
info:    Executing command resource set
error: missing required argument `resourceGroup'
```
3) Run `azure resource set -t owner=it -i "/subscriptions/SUBID/resourcegroups/autotest/providers/Microsoft.Automation/automationAccounts/autotest/runbooks/AzureClassicAutomationTutorialScript" -g autotest`
4) Response is:
```
info:    Executing command resource set
error:   Cannot use both resource parameters {resourceGroup, name, resourceType} and {resource id} in the same operation. Please provide one of the two.
error:   Error information has been recorded to /home/esell/.azure/azure.err
error:   resource set command failed
```

As you can see, if you run with just the resource ID it tells you to provide a resource group name. If you run it with the resource ID + the resource group name it tells you that you can't have both in the same command. Step 3 is the only one that creates a stack trace (see below)

Error stack trace:

```
2017-06-07T16:17:14.316Z:
{ Error: Cannot use both resource parameters {resourceGroup, name, resourceType} and {resource id} in the same operation. Please provide one of the two.
  <<< async stack >>>
    at getValuesForCommand (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:362:13)
    at __2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:76:16)
  <<< raw stack >>>
    at getValuesForCommand (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:362:13)
    at __$__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:76:16)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:58:1575)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/lib/cli.js:223:12)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at emitTwo (events.js:106:13)
    at AzureCli.emit (events.js:191:7)
    at AzureCli.Command.parseArgs (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:405:12)
    at AzureCli.Command.parse (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:351:15)
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
Error: Cannot use both resource parameters {resourceGroup, name, resourceType} and {resource id} in the same operation. Please provide one of the two.
  <<< async stack >>>
    at getValuesForCommand (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:362:13)
    at __2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:76:16)
  <<< raw stack >>>
    at getValuesForCommand (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:362:13)
    at __$__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:76:16)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__2 (/usr/lib/node_modules/azure-cli/lib/commands/arm/resource/resource.js:58:1575)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/lib/cli.js:223:12)
    at AzureCli.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at emitTwo (events.js:106:13)
    at AzureCli.emit (events.js:191:7)
    at AzureCli.Command.parseArgs (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:405:12)
    at AzureCli.Command.parse (/usr/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:351:15)
```

**Comment by esell** [comment]
Looks like the issue is at https://github.com/Azure/azure-xplat-cli/blob/release-0.10.13/lib/commands/arm/resource/resource._js#L372.

It appears to be case sensitive. I changed my example to use `resourceGroup` instead of `resourcegroup` and things seem to be working...

**Comment by balajikris** [comment]
@vivsriaus - Hi Vivek, can you please take a look at this? Seems a like a legit bug based on the findings above.

**Comment by vivsriaus** [comment]
Adding @ravbhatnagar to triage

**Comment by amarzavery** [comment]
This CLI is deprecated. Please use the new CLI https://github.com/Azure/azure-cli/releases.
