### ISSUE TITLE
While Creating an Azure Active Directory (AAD) Application using Azure CLI getting error

### ISSUE THREAD

**Issue by anandhs191** [Azure/azure-xplat-cli#3624]
CLI Version: 0.10.14
OS Type:  Win 10
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM"

Environment: **AzureCloud**

Description:
azure ad app create --name "Service Principal for BOSH" --password "PASSWORD" --home-page "http://BOSHAzureCPI" --identifier-uris "http://BOSHAzureCPI" command has error

info:    Executing command ad app create
error:   Cannot find module 'is-stream'
error:   Error information has been recorded to C:\Users\USERNAME\.azure\azure.err
error:   ad app create command failed

Error stack trace:

{ Error: Cannot find module 'is-stream'
  <<< async stack >>>
  at exports_createApplication__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\ad\adUtils.js:58:17)  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\ad\ad.application.js:47:33)
  <<< raw stack >>>
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-graph\node_modules\ms-rest\lib\serialization.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  stack: [Getter/Setter],
  code: 'MODULE_NOT_FOUND',
  __frame:
   { name: 'exports_createApplication__1',
     line: 28,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\ad\\adUtils.js',
     prev:
      { name: '__1',
        line: 46,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\ad\\ad.application.js',
        prev: undefined,
        calls: 1,
active: false,
        offset: 1,
        col: 32 },
     calls: 0,
     active: true,
     offset: 30,
     col: 16 },
  rawStack: [Getter] }
Error: Cannot find module 'is-stream'
  <<< async stack >>>
  at exports_createApplication__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\ad\adUtils.js:58:17)  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\ad\ad.application.js:47:33)
  <<< raw stack >>>
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-graph\node_modules\ms-rest\lib\serialization.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by balajikris** [comment]
@anandhs191 
1. I see you're running windows, can you please tell us how you installed this product? Installation via: npm / win installer / docker / github repo ?
1. can you please share nodejs version and npm version on your machine? you can obtain this info by running `node -v` and `npm -v` respectively.
1. If you installed this via windows installer, can you please try installing this from npm by using `npm install -g azure-cli` and see if that unblocks you while we figure out and fix this problem?

**Comment by balajikris** [comment]
@anandhs191 -- I'm unable to reproduce this locally. Can you please clarify my questions above? It will help us track this down

**Comment by balajikris** [comment]
Yep, was able to reproduce with Windows Installer. Tested a fix that makes it work. Will send a PR shortly

**Comment by balajikris** [comment]
should be fixed in the next release 0.10.15. until then please install from npm (`npm install -g azure-cli`) to unblock yourself.

**Comment by balajikris** [comment]
Preparing the 0.10.15 installer currently and I can already see this command now works as expected. :shipit:
