### ISSUE TITLE
Keyvault Create Certificate returns "Request body not specified"

### ISSUE THREAD

**Issue by kensykora** [Azure/azure-xplat-cli#3631]
CLI Version: **0.10.13 (Node 8.1.3)**
OS Type: Mac
Installation via:  brew

Mode: ARM

Environment: AzureCloud

Description:
`azure keyvault certificate create kms-test mycert` command returns error "Request body not specified"

Steps to reproduce:
1) Create a new keyvault `azure keyvault create azure-cli-test -g kms-test -l eastus`
2) Create a certificate policy `azure keyvault certificate policy create azure-cli-test mypolicy`
3) Create a certificate `azure keyvault certificate create azure-cli-test mycert`

Error stack trace:

```
2017-06-29T19:12:19.170Z:
{ Error: Request body not specified
  <<< async stack >>>
  at __5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:344:39)
  <<< raw stack >>>
    at /usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/azure-keyvault/lib/keyVaultClient.js:5617:19
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/util/utils.js:608:7
    at Request._callback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:126:16)
    at Request.self.callback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)

  stack: [Getter],
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     url: 'https://azure-cli-test.vault.azure.net/certificates/mycert/create?api-version=2015-06-01',
     method: 'POST',
     headers: 
      { 'x-ms-client-request-id': '78708013-cae6-4140-aeab-763379de249a',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'x-ms-command-name': 'keyvault certificate create',
        'x-ms-parameter-set-name': '****** ************** ******',
        'user-agent': 'AzureXplatCLI/0.10.13;osType:Darwin;osVersion:16.6.0;nodeVersion:v8.1.3;installationType:NPM;userType:user;macAddressHash:38fbdde984330e50c02382e647c576b71f41cc5c45b193d4f3177e6ee8f22a78' },
     body: '' },
  response: 
   { body: '{"error":{"code":"BadParameter","message":"Request body not specified"}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '72',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        server: 'Microsoft-IIS/8.5',
        'x-ms-keyvault-region': 'eastus',
        'x-ms-request-id': 'de73363a-2972-453a-b956-0118bbde2d3d',
        'x-ms-keyvault-service-version': '1.0.0.816',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET',
        'strict-transport-security': 'max-age=31536000;includeSubDomains',
        'x-content-type-options': 'nosniff',
        date: 'Thu, 29 Jun 2017 19:12:16 GMT',
        connection: 'close' },
     statusCode: 400 },
  code: 'BadParameter',
  body: {},
  __frame: 
   { name: '__5',
     line: 291,
     file: '/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 53,
     col: 38 },
  rawStack: [Getter] }
Error: Request body not specified
  <<< async stack >>>
  at __5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:344:39)
  <<< raw stack >>>
    at /usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/azure-keyvault/lib/keyVaultClient.js:5617:19
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/util/utils.js:608:7
    at Request._callback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:126:16)
    at Request.self.callback (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)

```

If I try to explicitly specify the policy (`azure keyvault certificate create -p mypolicy azure-cli-test mycert`), I get this error:

```
bash-3.2$ azure keyvault certificate create -p mypolicy azure-cli-test mycert
info:    Executing command keyvault certificate create
error:   Parse error on line 1:
mypolicy
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
error:   Error information has been recorded to /Users/kensykora/.azure/azure.err
error:   keyvault certificate create command failed



2017-06-29T19:14:50.596Z:
{ Error: Parse error on line 1:
mypolicy
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
  <<< async stack >>>
    at Object.parseError (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at __5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:487:40)
  <<< raw stack >>>
    at Object.parseError (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at __$__5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:487:40)
    at __func (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:457:12)
    at AzureCli.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/cli.js:223:12)
    at AzureCli.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at emitTwo (events.js:125:13)
    at AzureCli.emit (events.js:213:7)
 stack: [Getter], __frame: undefined, rawStack: [Getter] }
Error: Parse error on line 1:
mypolicy
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
  <<< async stack >>>
    at Object.parseError (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at __5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:487:40)
  <<< raw stack >>>
    at Object.parseError (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at __$__5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:487:40)
    at __func (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__5 (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/commands/arm/keyvault/keyvault.certificate._js:457:12)
    at AzureCli.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/lib/cli.js:223:12)
    at AzureCli.<anonymous> (/usr/local/Cellar/azure-cli/0.10.14/libexec/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:235:8)
    at emitTwo (events.js:125:13)
    at AzureCli.emit (events.js:213:7)


```

**Comment by amarzavery** [comment]
Please use [azure cli 2.0](https://github.com/Azure/azure-cli/releases)
