### ISSUE TITLE
azure account import fails with error "4 == 3"

### ISSUE THREAD

**Issue by nmikuni** [Azure/azure-xplat-cli#3676]
- CLI Version: **0.10.17**
- OS Type: Win
- Installation via:  msi

- Mode: **ASM**

- Environment: **AzureCloud*

- Description:
Hi,
I want to list ASM resources without interactive login procedure by Service Principal or downloading certification. I understood that as #2040 , Service Principal can't be co-administrator so that the only way is to download certification.

However, I got weird log following.
```
azure account import "[File name]"
info:    Executing command account import
error:   4 == 3
error:   Error information has been recorded to C:\Users\namikun\.azure\azure.err
error:   account import command failed
```
I found that I could import by following AzurePowerShell command.
`import-AzurePublishSettingsFile `

- Error stack trace:
```
2018-01-22T09:51:38.300Z:
{ AssertionError: 4 == 3
  <<< async stack >>>
  <<< raw stack >>>
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:352:14)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
    at PfxSafeBagDecoder.emit (events.js:188:7)
    at PfxSafeBagDecoder.Decoder.parse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\der.js:52:10)
    at PfxContentBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:123:13)
    at emitOne (events.js:96:13)
  name: 'AssertionError',
  actual: 4,
  expected: 3,
  operator: '==',
  message: '4 == 3',
  generatedMessage: true,
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
AssertionError: 4 == 3
  <<< async stack >>>
  <<< raw stack >>>
    at PfxPkcs8ShroudedKeyBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:352:14)
    at emitOne (events.js:96:13)
    at PfxPkcs8ShroudedKeyBagDecoder.emit (events.js:188:7)
    at PfxPkcs8ShroudedKeyBagDecoder.Decoder.parse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\der.js:58:8)
    at PfxSafeBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:305:27)
    at emitOne (events.js:96:13)
    at PfxSafeBagDecoder.emit (events.js:188:7)
    at PfxSafeBagDecoder.Decoder.parse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\der.js:52:10)
    at PfxContentBagDecoder.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\certificates\pkcs.js:123:13)
    at emitOne (events.js:96:13)

```

- Steps to reproduce:
```
(1)azure account download
(2) azure account import "[File name]"
```

**Comment by amarzavery** [comment]
Please use ARM APIs for managing stuff on Azure.
