### ISSUE TITLE
azure group deployment list broken

### ISSUE THREAD

**Issue by valantisdatsios** [Azure/azure-xplat-cli#3697]
- CLI Version: **0.10.20**
- OS Type: Linux (Ubuntu 16.04.3)
- Installation via:  npm

- Environment: **AzureCloud**

- Description:
`azure group deployment list` command fails with return code 1

- Error messages:
error: client.deployments.list is not a function
error: group deployment list command failed

- Error stack trace:
1049h1h=;1H▽n;1H  ;1H]11;?;56r12;25h12l25hJ25l6;1H"/var/tmp/azure_session/azure.err" 28L, 1764Cc;1H2018-11-21T10:29:38.628Z:
{ [TypeError: client.deployments.list is not a function]
 stack: [Getter/Setter],
 __frame:
  { name: '__2',;6Hline: 146,;6Hfile: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',;6Hprev: undefined,;6Hcalls: 1,0;6Hactive: false,1;6Hoffset: 9,2;6Hcol: 25 },
 rawStack: [Getter] }
TypeError: client.deployments.list is not a function
 <<< async stack >>>
   at retrieveDeployments (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:355:31)
 at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:155:26)
 <<< raw stack >>>
   at __$retrieveDeployments (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:355:31)
   at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
   at retrieveDeployments (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:350:182)
   at __$__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:155:20)
   at __tryCatch (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
   at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:152:120)
   at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:155:179)
   at __$__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:157:159)
   at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
   at AzureCli.__2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:139:621)

**Comment by amarzavery** [comment]
This CLI is deprecated. Please use the new CLI https://github.com/azure/azure-cli.
