### ISSUE TITLE
'azure group show' command error: 'client.resourceGroups.listResources is not a function'

### ISSUE THREAD

**Issue by storozhilov-dnanexus** [Azure/azure-xplat-cli#3700]
- CLI Version: **0.10.20**
- OS Type: Linux Ubuntu 16.04
- Installation via:  npm

- Mode: **ARM**

- Environment: **AzureCloud**

- Description:
`azure group show` command fails with *"client.resourceGroups.listResources is not a function"* error.

- Steps to reproduce:
1) Deploy an Ubuntu 16.04 VM in Azure and SSH into it;
2) Run the following commands:

```
$ sudo apt-get update
$ sudo apt-get upgrade -y
$ curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
$ sudo apt-get install gcc g++ make -y
$ sudo apt-get install nodejs -y
$ sudo npm install -g azure-cli
$ azure login
$ azure group create fooBarResourceGroup westus
info:    Executing command group create
+ Getting resource group fooBarResourceGroup                                   
+ Creating resource group fooBarResourceGroup                                  
info:    Created resource group fooBarResourceGroup
data:    Id:                  /subscriptions/xxxxx-yyyyy-zzzzz/resourceGroups/fooBarResourceGroup
data:    Name:                fooBarResourceGroup
data:    Location:            westus
data:    Provisioning State:  Succeeded
data:    Tags: null
data:    
info:    group create command OK
$ azure group show fooBarResourceGroup 
info:    Executing command group show
+ Getting resource group                                                       
+ Listing resources for the group                                              
error:   client.resourceGroups.listResources is not a function
error:   Error information has been recorded to /home/ubuntu/.azure/azure.err
error:   group show command failed
```

- Error stack trace:

```
TypeError: client.resourceGroups.listResources is not a function
    at __$__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:274:46)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:272:136)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:275:221)
    at __$__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:277:163)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:177)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:110)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:65)

TypeError: client.resourceGroups.listResources is not a function
    at __$__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:274:46)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:272:136)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:275:221)
    at __$__6 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:277:163)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:177)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:110)
    at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:268:65)
```

In addition to that I would like to inform that the following non-critical errors are reported during `azure-cli` npm module installation:

```
$ sudo npm install -g azure-cli
npm WARN deprecated github@0.1.6: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/usr/bin/azure -> /usr/lib/node_modules/azure-cli/bin/azure

> fibers@1.0.15 install /usr/lib/node_modules/azure-cli/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp'
gyp ERR! System Linux 4.15.0-1036-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/lib/node_modules/azure-cli/node_modules/fibers
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp'
gyp ERR! System Linux 4.15.0-1036-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/lib/node_modules/azure-cli/node_modules/fibers
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fibers@1.0.15 (node_modules/azure-cli/node_modules/fibers):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fibers@1.0.15 install: `node build.js || nodejs build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ azure-cli@0.10.20
added 334 packages from 298 contributors in 11.689s
```

**Comment by amarzavery** [comment]
This CLI has been deprecated. Please use the new cli https://github.com/azure/azure-cli
