### ISSUE TITLE
 Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+$/ - (Getting the same issue while trying to run docker)

### ISSUE THREAD

**Issue by SatyakiDe2019** [Azure/azure-xplat-cli#3704]
Guys!

I'm facing issues when I'm trying to run docker in Ubuntu VM in Azure.

Please find the command -

`sudo docker run -ti "docker4x/create-sp-azure" "en_de_cr_python_07" ["sd_rnd_group_n_a_m_e" "westus"]`

- CLI Version: **0.10.X**
- OS Type: Ubuntu

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

- Installation via:  docker

- Environment: **AzureCloud/Azure West US**

- Description:
Even using double quotes command is not working

- Steps to reproduce:
1) Run `sudo docker pull "docker4x/create-sp-azure:latest"`
2) Then run `sudo docker run -ti "docker4x/create-sp-azure" "en_de_cr_python_07" ["sd_rnd_group_n_a_m_e" "westus"]`

- Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

info:    Executing command login
\info:    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BHDQUGH48 to authenticate.
/info:    Added subscription Free Trial
info:    Setting subscription "Free Trial" as default
+
info:    login command OK
The following subscriptions were retrieved from your Azure account
1) 682b5418-713a-433e-9c57-a6552bde7ab3:Free_Trial
Please select the subscription option number to use for Docker swarm resources: 1
Using subscription 682b5418-713a-433e-9c57-a6552bde7ab3
info:    Executing command account set
info:    Setting subscription to "Free Trial" with id "682b5418-713a-433e-9c57-a6552bde7ab3".
info:    Changes saved
info:    account set command OK
Creating AD application en_de_cr_python_07
Created AD application, APP_ID=28d7919d-f482-4c07-9546-1e8f4b0f625f
Creating AD App ServicePrincipal
Created ServicePrincipal ID=d69f96b2-5f55-46a8-a11e-73b78b500c07
Create new Azure Resource Group [sd_rnd_group_n_a_m_e in westus]
info:    Executing command group create
+ Getting resource group [sd_rnd_group_n_a_m_e
error:   "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
error:   Error information has been recorded to /root/.azure/azure.err
error:   group create command failed

Resource Group creation failed. Details:
2019-06-09T03:03:53.860Z:
{ Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
  <<< async stack >>>
    at ResourceGroups._get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:473:15)
    at ResourceGroups.get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:1756:19)
    at Object.getGroup (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:36)
  at group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:21)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:61:32)
  <<< raw stack >>>
    at ResourceGroups._get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:473:15)
    at ResourceGroups.get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:1756:19)
    at Object.getGroup (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:165)
    at Interactor.withProgress (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:194:12)
    at __$group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:30)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.group_createResourceGroup__3 [as createResourceGroup] (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:81:248)

  stack: [Getter/Setter],
  __frame:
   { name: '__1',
     line: 88,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
     prev:
      { name: 'group_createResourceGroup__3',
        line: 81,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 6,
        col: 20 },
     calls: 0,
     active: false,
     offset: 1,
     col: 35 },
  rawStack: [Getter] }
Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+$/
  <<< async stack >>>
    at ResourceGroups._get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:473:15)
    at ResourceGroups.get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:1756:19)
    at Object.getGroup (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:36)
  at group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:21)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:61:32)
  <<< raw stack >>>
    at ResourceGroups._get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:473:15)
    at ResourceGroups.get (/usr/lib/node_modules/azure-cli/node_modules/azure-arm-resource/lib/resource/operations/resourceGroups.js:1756:19)
    at Object.getGroup (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils.js:33:25)
    at __$__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:89:29)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:165)
    at Interactor.withProgress (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:194:12)
    at __$group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:87:30)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.group_createResourceGroup__3 [as createResourceGroup] (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group.js:81:248)

**Comment by amarzavery** [comment]
Please use the new azure-cli https://github.com/azure/azure-cli. This CLI has been deprecated.

**Comment by mbalsam-refind** [comment]
The square brackets should not be entered. 

Bad: sudo docker run -ti "docker4x/create-sp-azure" "en_de_cr_python_07" ["sd_rnd_group_n_a_m_e" "westus"]

Good: sudo docker run -ti "docker4x/create-sp-azure" "en_de_cr_python_07" "sd_rnd_group_n_a_m_e" "westus"
